#!/usr/bin/env bash

defaults write com.apple.dock "last-analytics-stamp" '
<array>
	<real>654903925.47315705</real>
</array>
'
defaults write com.apple.dock "loc" -string 'en_GB:FR'
defaults write com.apple.dock "mod-count" -integer 5
defaults write com.apple.dock "persistent-apps" '
<array>
	<dict>
		<key>GUID</key>
		<integer>3315440934</integer>
		<key>tile-data</key>
		<dict>
			<key>book</key>
			<data>
			Ym9va0QCAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAA
			AAAAAAAAAAAAAAAAAAAAZAEAAAQAAAADAwAAAAAAIAYA
			AAABAQAAU3lzdGVtAAAMAAAAAQEAAEFwcGxpY2F0aW9u
			cw0AAAABAQAATGF1bmNocGFkLmFwcAAAAAwAAAABBgAA
			EAAAACAAAAA0AAAACAAAAAQDAAAVAAAA////DwgAAAAE
			AwAAFwAAAP///w8IAAAABAMAAMZoAAD///8PDAAAAAEG
			AABgAAAAcAAAAIAAAAAIAAAAAAQAAEHDbGIIgAAAGAAA
			AAECAAACAAAAAAAAAA8AAAAAAAAAAAAAAAAAAAAIAAAA
			AQkAAGZpbGU6Ly8vCAAAAAEBAABVbnRpdGxlZAgAAAAE
			AwAAAACHETkAAAAkAAAAAQEAAEI0OTBBMDA0LTMzMUYt
			NDkyNC05Q0M5LUIwRUU3RTI1MTQ0MhgAAAABAgAAgQAA
			AAEAAADvEwAAAQAAAAAAAAAAAAAAAQAAAAEBAAAvAAAA
			AAAAAAEFAACoAAAA/v///wEAAAAAAAAADQAAAAQQAABM
			AAAAAAAAAAUQAACQAAAAAAAAABAQAAC0AAAAAAAAAEAQ
			AACkAAAAAAAAAAIgAABQAQAAAAAAAAUgAADUAAAAAAAA
			ABAgAADkAAAAAAAAABEgAAAEAQAAAAAAABIgAAD0AAAA
			AAAAABMgAACkAAAAAAAAACAgAAAwAQAAAAAAADAgAABc
			AQAAAAAAABDQAAAEAAAAAAAAAA==
			</data>
			<key>bundle-identifier</key>
			<string>com.apple.launchpad.launcher</string>
			<key>dock-extra</key>
			<false/>
			<key>file-data</key>
			<dict>
				<key>_CFURLString</key>
				<string>file:///System/Applications/Launchpad.app/</string>
				<key>_CFURLStringType</key>
				<integer>15</integer>
			</dict>
			<key>file-label</key>
			<string>Launchpad</string>
			<key>file-mod-date</key>
			<integer>3712892177</integer>
			<key>file-type</key>
			<integer>169</integer>
			<key>is-beta</key>
			<false/>
			<key>parent-mod-date</key>
			<integer>3712892177</integer>
		</dict>
		<key>tile-type</key>
		<string>file-tile</string>
	</dict>
	<dict>
		<key>GUID</key>
		<integer>3315440935</integer>
		<key>tile-data</key>
		<dict>
			<key>book</key>
			<data>
			Ym9vaxgCAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAA
			AAAAAAAAAAAAAAAAAAAAOAEAAAQAAAADAwAAAAAAIAwA
			AAABAQAAQXBwbGljYXRpb25zCgAAAAEBAABTYWZhcmku
			YXBwAAAIAAAAAQYAABAAAAAkAAAACAAAAAQDAAB0ZAAA
			AAAAAAgAAAAEAwAAdmQAAAAAAAAIAAAAAQYAAEgAAABY
			AAAACAAAAAAEAABBw2xiCIAAABgAAAABAgAAAgAAAAAA
			AAAPAAAAAAAAAAAAAAAAAAAACAAAAAEJAABmaWxlOi8v
			LwgAAAABAQAAVW50aXRsZWQIAAAABAMAAAAAhxE5AAAA
			JAAAAAEBAABCNDkwQTAwNC0zMzFGLTQ5MjQtOUNDOS1C
			MEVFN0UyNTE0NDIYAAAAAQIAAIEAAAABAAAA7xMAAAEA
			AAAAAAAAAAAAAAEAAAABAQAALwAAAAAAAAABBQAAqAAA
			AP7///8BAAAAAAAAAA0AAAAEEAAAOAAAAAAAAAAFEAAA
			aAAAAAAAAAAQEAAAiAAAAAAAAABAEAAAeAAAAAAAAAAC
			IAAAJAEAAAAAAAAFIAAAqAAAAAAAAAAQIAAAuAAAAAAA
			AAARIAAA2AAAAAAAAAASIAAAyAAAAAAAAAATIAAAeAAA
			AAAAAAAgIAAABAEAAAAAAAAwIAAAMAEAAAAAAAAQ0AAA
			BAAAAAAAAAA=
			</data>
			<key>bundle-identifier</key>
			<string>com.apple.Safari</string>
			<key>dock-extra</key>
			<false/>
			<key>file-data</key>
			<dict>
				<key>_CFURLString</key>
				<string>file:///Applications/Safari.app/</string>
				<key>_CFURLStringType</key>
				<integer>15</integer>
			</dict>
			<key>file-label</key>
			<string>Safari</string>
			<key>file-mod-date</key>
			<integer>3712892177</integer>
			<key>file-type</key>
			<integer>41</integer>
			<key>is-beta</key>
			<false/>
			<key>parent-mod-date</key>
			<integer>258088300876289</integer>
		</dict>
		<key>tile-type</key>
		<string>file-tile</string>
	</dict>
	<dict>
		<key>GUID</key>
		<integer>3315440936</integer>
		<key>tile-data</key>
		<dict>
			<key>book</key>
			<data>
			Ym9va0ACAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAA
			AAAAAAAAAAAAAAAAAAAAYAEAAAQAAAADAwAAAAAAIAYA
			AAABAQAAU3lzdGVtAAAMAAAAAQEAAEFwcGxpY2F0aW9u
			cwwAAAABAQAATWVzc2FnZXMuYXBwDAAAAAEGAAAQAAAA
			IAAAADQAAAAIAAAABAMAABUAAAD///8PCAAAAAQDAAAX
			AAAA////DwgAAAAEAwAASIoAAP///w8MAAAAAQYAAFwA
			AABsAAAAfAAAAAgAAAAABAAAQcNsYgiAAAAYAAAAAQIA
			AAIAAAAAAAAADwAAAAAAAAAAAAAAAAAAAAgAAAABCQAA
			ZmlsZTovLy8IAAAAAQEAAFVudGl0bGVkCAAAAAQDAAAA
			AIcROQAAACQAAAABAQAAQjQ5MEEwMDQtMzMxRi00OTI0
			LTlDQzktQjBFRTdFMjUxNDQyGAAAAAECAACBAAAAAQAA
			AO8TAAABAAAAAAAAAAAAAAABAAAAAQEAAC8AAAAAAAAA
			AQUAAKgAAAD+////AQAAAAAAAAANAAAABBAAAEgAAAAA
			AAAABRAAAIwAAAAAAAAAEBAAALAAAAAAAAAAQBAAAKAA
			AAAAAAAAAiAAAEwBAAAAAAAABSAAANAAAAAAAAAAECAA
			AOAAAAAAAAAAESAAAAABAAAAAAAAEiAAAPAAAAAAAAAA
			EyAAAKAAAAAAAAAAICAAACwBAAAAAAAAMCAAAFgBAAAA
			AAAAENAAAAQAAAAAAAAA
			</data>
			<key>bundle-identifier</key>
			<string>com.apple.MobileSMS</string>
			<key>dock-extra</key>
			<false/>
			<key>file-data</key>
			<dict>
				<key>_CFURLString</key>
				<string>file:///System/Applications/Messages.app/</string>
				<key>_CFURLStringType</key>
				<integer>15</integer>
			</dict>
			<key>file-label</key>
			<string>Messages</string>
			<key>file-mod-date</key>
			<integer>3712892177</integer>
			<key>file-type</key>
			<integer>41</integer>
			<key>is-beta</key>
			<false/>
			<key>parent-mod-date</key>
			<integer>3712892177</integer>
		</dict>
		<key>tile-type</key>
		<string>file-tile</string>
	</dict>
	<dict>
		<key>GUID</key>
		<integer>3315440937</integer>
		<key>tile-data</key>
		<dict>
			<key>book</key>
			<data>
			Ym9vazwCAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAA
			AAAAAAAAAAAAAAAAAAAAXAEAAAQAAAADAwAAAAAAIAYA
			AAABAQAAU3lzdGVtAAAMAAAAAQEAAEFwcGxpY2F0aW9u
			cwgAAAABAQAATWFpbC5hcHAMAAAAAQYAABAAAAAgAAAA
			NAAAAAgAAAAEAwAAFQAAAP///w8IAAAABAMAABcAAAD/
			//8PCAAAAAQDAABNaQAA////DwwAAAABBgAAWAAAAGgA
			AAB4AAAACAAAAAAEAABBw2xiCIAAABgAAAABAgAAAgAA
			AAAAAAAPAAAAAAAAAAAAAAAAAAAACAAAAAEJAABmaWxl
			Oi8vLwgAAAABAQAAVW50aXRsZWQIAAAABAMAAAAAhxE5
			AAAAJAAAAAEBAABCNDkwQTAwNC0zMzFGLTQ5MjQtOUND
			OS1CMEVFN0UyNTE0NDIYAAAAAQIAAIEAAAABAAAA7xMA
			AAEAAAAAAAAAAAAAAAEAAAABAQAALwAAAAAAAAABBQAA
			qAAAAP7///8BAAAAAAAAAA0AAAAEEAAARAAAAAAAAAAF
			EAAAiAAAAAAAAAAQEAAArAAAAAAAAABAEAAAnAAAAAAA
			AAACIAAASAEAAAAAAAAFIAAAzAAAAAAAAAAQIAAA3AAA
			AAAAAAARIAAA/AAAAAAAAAASIAAA7AAAAAAAAAATIAAA
			nAAAAAAAAAAgIAAAKAEAAAAAAAAwIAAAVAEAAAAAAAAQ
			0AAABAAAAAAAAAA=
			</data>
			<key>bundle-identifier</key>
			<string>com.apple.mail</string>
			<key>dock-extra</key>
			<false/>
			<key>file-data</key>
			<dict>
				<key>_CFURLString</key>
				<string>file:///System/Applications/Mail.app/</string>
				<key>_CFURLStringType</key>
				<integer>15</integer>
			</dict>
			<key>file-label</key>
			<string>Mail</string>
			<key>file-mod-date</key>
			<integer>3712892177</integer>
			<key>file-type</key>
			<integer>41</integer>
			<key>is-beta</key>
			<false/>
			<key>parent-mod-date</key>
			<integer>3712892177</integer>
		</dict>
		<key>tile-type</key>
		<string>file-tile</string>
	</dict>
	<dict>
		<key>GUID</key>
		<integer>3315440938</integer>
		<key>tile-data</key>
		<dict>
			<key>book</key>
			<data>
			Ym9vazwCAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAA
			AAAAAAAAAAAAAAAAAAAAXAEAAAQAAAADAwAAAAAAIAYA
			AAABAQAAU3lzdGVtAAAMAAAAAQEAAEFwcGxpY2F0aW9u
			cwgAAAABAQAATWFwcy5hcHAMAAAAAQYAABAAAAAgAAAA
			NAAAAAgAAAAEAwAAFQAAAP///w8IAAAABAMAABcAAAD/
			//8PCAAAAAQDAABLhwAA////DwwAAAABBgAAWAAAAGgA
			AAB4AAAACAAAAAAEAABBw2xiCIAAABgAAAABAgAAAgAA
			AAAAAAAPAAAAAAAAAAAAAAAAAAAACAAAAAEJAABmaWxl
			Oi8vLwgAAAABAQAAVW50aXRsZWQIAAAABAMAAAAAhxE5
			AAAAJAAAAAEBAABCNDkwQTAwNC0zMzFGLTQ5MjQtOUND
			OS1CMEVFN0UyNTE0NDIYAAAAAQIAAIEAAAABAAAA7xMA
			AAEAAAAAAAAAAAAAAAEAAAABAQAALwAAAAAAAAABBQAA
			qAAAAP7///8BAAAAAAAAAA0AAAAEEAAARAAAAAAAAAAF
			EAAAiAAAAAAAAAAQEAAArAAAAAAAAABAEAAAnAAAAAAA
			AAACIAAASAEAAAAAAAAFIAAAzAAAAAAAAAAQIAAA3AAA
			AAAAAAARIAAA/AAAAAAAAAASIAAA7AAAAAAAAAATIAAA
			nAAAAAAAAAAgIAAAKAEAAAAAAAAwIAAAVAEAAAAAAAAQ
			0AAABAAAAAAAAAA=
			</data>
			<key>bundle-identifier</key>
			<string>com.apple.Maps</string>
			<key>dock-extra</key>
			<false/>
			<key>file-data</key>
			<dict>
				<key>_CFURLString</key>
				<string>file:///System/Applications/Maps.app/</string>
				<key>_CFURLStringType</key>
				<integer>15</integer>
			</dict>
			<key>file-label</key>
			<string>Maps</string>
			<key>file-mod-date</key>
			<integer>3712892177</integer>
			<key>file-type</key>
			<integer>41</integer>
			<key>is-beta</key>
			<false/>
			<key>parent-mod-date</key>
			<integer>3712892177</integer>
		</dict>
		<key>tile-type</key>
		<string>file-tile</string>
	</dict>
	<dict>
		<key>GUID</key>
		<integer>3315440939</integer>
		<key>tile-data</key>
		<dict>
			<key>book</key>
			<data>
			Ym9va0ACAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAA
			AAAAAAAAAAAAAAAAAAAAYAEAAAQAAAADAwAAAAAAIAYA
			AAABAQAAU3lzdGVtAAAMAAAAAQEAAEFwcGxpY2F0aW9u
			cwoAAAABAQAAUGhvdG9zLmFwcAAADAAAAAEGAAAQAAAA
			IAAAADQAAAAIAAAABAMAABUAAAD///8PCAAAAAQDAAAX
			AAAA////DwgAAAAEAwAAoL8AAP///w8MAAAAAQYAAFwA
			AABsAAAAfAAAAAgAAAAABAAAQcNsYgiAAAAYAAAAAQIA
			AAIAAAAAAAAADwAAAAAAAAAAAAAAAAAAAAgAAAABCQAA
			ZmlsZTovLy8IAAAAAQEAAFVudGl0bGVkCAAAAAQDAAAA
			AIcROQAAACQAAAABAQAAQjQ5MEEwMDQtMzMxRi00OTI0
			LTlDQzktQjBFRTdFMjUxNDQyGAAAAAECAACBAAAAAQAA
			AO8TAAABAAAAAAAAAAAAAAABAAAAAQEAAC8AAAAAAAAA
			AQUAAKgAAAD+////AQAAAAAAAAANAAAABBAAAEgAAAAA
			AAAABRAAAIwAAAAAAAAAEBAAALAAAAAAAAAAQBAAAKAA
			AAAAAAAAAiAAAEwBAAAAAAAABSAAANAAAAAAAAAAECAA
			AOAAAAAAAAAAESAAAAABAAAAAAAAEiAAAPAAAAAAAAAA
			EyAAAKAAAAAAAAAAICAAACwBAAAAAAAAMCAAAFgBAAAA
			AAAAENAAAAQAAAAAAAAA
			</data>
			<key>bundle-identifier</key>
			<string>com.apple.Photos</string>
			<key>dock-extra</key>
			<false/>
			<key>file-data</key>
			<dict>
				<key>_CFURLString</key>
				<string>file:///System/Applications/Photos.app/</string>
				<key>_CFURLStringType</key>
				<integer>15</integer>
			</dict>
			<key>file-label</key>
			<string>Photos</string>
			<key>file-mod-date</key>
			<integer>3712892177</integer>
			<key>file-type</key>
			<integer>41</integer>
			<key>is-beta</key>
			<false/>
			<key>parent-mod-date</key>
			<integer>3712892177</integer>
		</dict>
		<key>tile-type</key>
		<string>file-tile</string>
	</dict>
	<dict>
		<key>GUID</key>
		<integer>3315440940</integer>
		<key>tile-data</key>
		<dict>
			<key>book</key>
			<data>
			Ym9va0ACAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAA
			AAAAAAAAAAAAAAAAAAAAYAEAAAQAAAADAwAAAAAAIAYA
			AAABAQAAU3lzdGVtAAAMAAAAAQEAAEFwcGxpY2F0aW9u
			cwwAAAABAQAARmFjZVRpbWUuYXBwDAAAAAEGAAAQAAAA
			IAAAADQAAAAIAAAABAMAABUAAAD///8PCAAAAAQDAAAX
			AAAA////DwgAAAAEAwAA1UAAAP///w8MAAAAAQYAAFwA
			AABsAAAAfAAAAAgAAAAABAAAQcNsYgiAAAAYAAAAAQIA
			AAIAAAAAAAAADwAAAAAAAAAAAAAAAAAAAAgAAAABCQAA
			ZmlsZTovLy8IAAAAAQEAAFVudGl0bGVkCAAAAAQDAAAA
			AIcROQAAACQAAAABAQAAQjQ5MEEwMDQtMzMxRi00OTI0
			LTlDQzktQjBFRTdFMjUxNDQyGAAAAAECAACBAAAAAQAA
			AO8TAAABAAAAAAAAAAAAAAABAAAAAQEAAC8AAAAAAAAA
			AQUAAKgAAAD+////AQAAAAAAAAANAAAABBAAAEgAAAAA
			AAAABRAAAIwAAAAAAAAAEBAAALAAAAAAAAAAQBAAAKAA
			AAAAAAAAAiAAAEwBAAAAAAAABSAAANAAAAAAAAAAECAA
			AOAAAAAAAAAAESAAAAABAAAAAAAAEiAAAPAAAAAAAAAA
			EyAAAKAAAAAAAAAAICAAACwBAAAAAAAAMCAAAFgBAAAA
			AAAAENAAAAQAAAAAAAAA
			</data>
			<key>bundle-identifier</key>
			<string>com.apple.FaceTime</string>
			<key>dock-extra</key>
			<true/>
			<key>file-data</key>
			<dict>
				<key>_CFURLString</key>
				<string>file:///System/Applications/FaceTime.app/</string>
				<key>_CFURLStringType</key>
				<integer>15</integer>
			</dict>
			<key>file-label</key>
			<string>FaceTime</string>
			<key>file-mod-date</key>
			<integer>3712892177</integer>
			<key>file-type</key>
			<integer>41</integer>
			<key>is-beta</key>
			<false/>
			<key>parent-mod-date</key>
			<integer>3712892177</integer>
		</dict>
		<key>tile-type</key>
		<string>file-tile</string>
	</dict>
	<dict>
		<key>GUID</key>
		<integer>3315440941</integer>
		<key>tile-data</key>
		<dict>
			<key>book</key>
			<data>
			Ym9va0ACAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAA
			AAAAAAAAAAAAAAAAAAAAYAEAAAQAAAADAwAAAAAAIAYA
			AAABAQAAU3lzdGVtAAAMAAAAAQEAAEFwcGxpY2F0aW9u
			cwwAAAABAQAAQ2FsZW5kYXIuYXBwDAAAAAEGAAAQAAAA
			IAAAADQAAAAIAAAABAMAABUAAAD///8PCAAAAAQDAAAX
			AAAA////DwgAAAAEAwAAAR0AAP///w8MAAAAAQYAAFwA
			AABsAAAAfAAAAAgAAAAABAAAQcNsYgiAAAAYAAAAAQIA
			AAIAAAAAAAAADwAAAAAAAAAAAAAAAAAAAAgAAAABCQAA
			ZmlsZTovLy8IAAAAAQEAAFVudGl0bGVkCAAAAAQDAAAA
			AIcROQAAACQAAAABAQAAQjQ5MEEwMDQtMzMxRi00OTI0
			LTlDQzktQjBFRTdFMjUxNDQyGAAAAAECAACBAAAAAQAA
			AO8TAAABAAAAAAAAAAAAAAABAAAAAQEAAC8AAAAAAAAA
			AQUAAKgAAAD+////AQAAAAAAAAANAAAABBAAAEgAAAAA
			AAAABRAAAIwAAAAAAAAAEBAAALAAAAAAAAAAQBAAAKAA
			AAAAAAAAAiAAAEwBAAAAAAAABSAAANAAAAAAAAAAECAA
			AOAAAAAAAAAAESAAAAABAAAAAAAAEiAAAPAAAAAAAAAA
			EyAAAKAAAAAAAAAAICAAACwBAAAAAAAAMCAAAFgBAAAA
			AAAAENAAAAQAAAAAAAAA
			</data>
			<key>bundle-identifier</key>
			<string>com.apple.iCal</string>
			<key>dock-extra</key>
			<true/>
			<key>file-data</key>
			<dict>
				<key>_CFURLString</key>
				<string>file:///System/Applications/Calendar.app/</string>
				<key>_CFURLStringType</key>
				<integer>15</integer>
			</dict>
			<key>file-label</key>
			<string>Calendar</string>
			<key>file-mod-date</key>
			<integer>3712892177</integer>
			<key>file-type</key>
			<integer>41</integer>
			<key>is-beta</key>
			<false/>
			<key>parent-mod-date</key>
			<integer>3712892177</integer>
		</dict>
		<key>tile-type</key>
		<string>file-tile</string>
	</dict>
	<dict>
		<key>GUID</key>
		<integer>3315440942</integer>
		<key>tile-data</key>
		<dict>
			<key>book</key>
			<data>
			Ym9va0ACAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAA
			AAAAAAAAAAAAAAAAAAAAYAEAAAQAAAADAwAAAAAAIAYA
			AAABAQAAU3lzdGVtAAAMAAAAAQEAAEFwcGxpY2F0aW9u
			cwwAAAABAQAAQ29udGFjdHMuYXBwDAAAAAEGAAAQAAAA
			IAAAADQAAAAIAAAABAMAABUAAAD///8PCAAAAAQDAAAX
			AAAA////DwgAAAAEAwAAfzMAAP///w8MAAAAAQYAAFwA
			AABsAAAAfAAAAAgAAAAABAAAQcNsYgiAAAAYAAAAAQIA
			AAIAAAAAAAAADwAAAAAAAAAAAAAAAAAAAAgAAAABCQAA
			ZmlsZTovLy8IAAAAAQEAAFVudGl0bGVkCAAAAAQDAAAA
			AIcROQAAACQAAAABAQAAQjQ5MEEwMDQtMzMxRi00OTI0
			LTlDQzktQjBFRTdFMjUxNDQyGAAAAAECAACBAAAAAQAA
			AO8TAAABAAAAAAAAAAAAAAABAAAAAQEAAC8AAAAAAAAA
			AQUAAKgAAAD+////AQAAAAAAAAANAAAABBAAAEgAAAAA
			AAAABRAAAIwAAAAAAAAAEBAAALAAAAAAAAAAQBAAAKAA
			AAAAAAAAAiAAAEwBAAAAAAAABSAAANAAAAAAAAAAECAA
			AOAAAAAAAAAAESAAAAABAAAAAAAAEiAAAPAAAAAAAAAA
			EyAAAKAAAAAAAAAAICAAACwBAAAAAAAAMCAAAFgBAAAA
			AAAAENAAAAQAAAAAAAAA
			</data>
			<key>bundle-identifier</key>
			<string>com.apple.AddressBook</string>
			<key>dock-extra</key>
			<false/>
			<key>file-data</key>
			<dict>
				<key>_CFURLString</key>
				<string>file:///System/Applications/Contacts.app/</string>
				<key>_CFURLStringType</key>
				<integer>15</integer>
			</dict>
			<key>file-label</key>
			<string>Contacts</string>
			<key>file-mod-date</key>
			<integer>3712892177</integer>
			<key>file-type</key>
			<integer>41</integer>
			<key>is-beta</key>
			<false/>
			<key>parent-mod-date</key>
			<integer>3712892177</integer>
		</dict>
		<key>tile-type</key>
		<string>file-tile</string>
	</dict>
	<dict>
		<key>GUID</key>
		<integer>3315440943</integer>
		<key>tile-data</key>
		<dict>
			<key>book</key>
			<data>
			Ym9va0QCAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAA
			AAAAAAAAAAAAAAAAAAAAZAEAAAQAAAADAwAAAAAAIAYA
			AAABAQAAU3lzdGVtAAAMAAAAAQEAAEFwcGxpY2F0aW9u
			cw0AAAABAQAAUmVtaW5kZXJzLmFwcAAAAAwAAAABBgAA
			EAAAACAAAAA0AAAACAAAAAQDAAAVAAAA////DwgAAAAE
			AwAAFwAAAP///w8IAAAABAMAAHIOAQD///8PDAAAAAEG
			AABgAAAAcAAAAIAAAAAIAAAAAAQAAEHDbGIIgAAAGAAA
			AAECAAACAAAAAAAAAA8AAAAAAAAAAAAAAAAAAAAIAAAA
			AQkAAGZpbGU6Ly8vCAAAAAEBAABVbnRpdGxlZAgAAAAE
			AwAAAACHETkAAAAkAAAAAQEAAEI0OTBBMDA0LTMzMUYt
			NDkyNC05Q0M5LUIwRUU3RTI1MTQ0MhgAAAABAgAAgQAA
			AAEAAADvEwAAAQAAAAAAAAAAAAAAAQAAAAEBAAAvAAAA
			AAAAAAEFAACoAAAA/v///wEAAAAAAAAADQAAAAQQAABM
			AAAAAAAAAAUQAACQAAAAAAAAABAQAAC0AAAAAAAAAEAQ
			AACkAAAAAAAAAAIgAABQAQAAAAAAAAUgAADUAAAAAAAA
			ABAgAADkAAAAAAAAABEgAAAEAQAAAAAAABIgAAD0AAAA
			AAAAABMgAACkAAAAAAAAACAgAAAwAQAAAAAAADAgAABc
			AQAAAAAAABDQAAAEAAAAAAAAAA==
			</data>
			<key>bundle-identifier</key>
			<string>com.apple.reminders</string>
			<key>dock-extra</key>
			<false/>
			<key>file-data</key>
			<dict>
				<key>_CFURLString</key>
				<string>file:///System/Applications/Reminders.app/</string>
				<key>_CFURLStringType</key>
				<integer>15</integer>
			</dict>
			<key>file-label</key>
			<string>Reminders</string>
			<key>file-mod-date</key>
			<integer>3712892177</integer>
			<key>file-type</key>
			<integer>41</integer>
			<key>is-beta</key>
			<false/>
			<key>parent-mod-date</key>
			<integer>3712892177</integer>
		</dict>
		<key>tile-type</key>
		<string>file-tile</string>
	</dict>
	<dict>
		<key>GUID</key>
		<integer>3315440944</integer>
		<key>tile-data</key>
		<dict>
			<key>book</key>
			<data>
			Ym9va0ACAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAA
			AAAAAAAAAAAAAAAAAAAAYAEAAAQAAAADAwAAAAAAIAYA
			AAABAQAAU3lzdGVtAAAMAAAAAQEAAEFwcGxpY2F0aW9u
			cwkAAAABAQAATm90ZXMuYXBwAAAADAAAAAEGAAAQAAAA
			IAAAADQAAAAIAAAABAMAABUAAAD///8PCAAAAAQDAAAX
			AAAA////DwgAAAAEAwAA7KcAAP///w8MAAAAAQYAAFwA
			AABsAAAAfAAAAAgAAAAABAAAQcNsYgiAAAAYAAAAAQIA
			AAIAAAAAAAAADwAAAAAAAAAAAAAAAAAAAAgAAAABCQAA
			ZmlsZTovLy8IAAAAAQEAAFVudGl0bGVkCAAAAAQDAAAA
			AIcROQAAACQAAAABAQAAQjQ5MEEwMDQtMzMxRi00OTI0
			LTlDQzktQjBFRTdFMjUxNDQyGAAAAAECAACBAAAAAQAA
			AO8TAAABAAAAAAAAAAAAAAABAAAAAQEAAC8AAAAAAAAA
			AQUAAKgAAAD+////AQAAAAAAAAANAAAABBAAAEgAAAAA
			AAAABRAAAIwAAAAAAAAAEBAAALAAAAAAAAAAQBAAAKAA
			AAAAAAAAAiAAAEwBAAAAAAAABSAAANAAAAAAAAAAECAA
			AOAAAAAAAAAAESAAAAABAAAAAAAAEiAAAPAAAAAAAAAA
			EyAAAKAAAAAAAAAAICAAACwBAAAAAAAAMCAAAFgBAAAA
			AAAAENAAAAQAAAAAAAAA
			</data>
			<key>bundle-identifier</key>
			<string>com.apple.Notes</string>
			<key>dock-extra</key>
			<false/>
			<key>file-data</key>
			<dict>
				<key>_CFURLString</key>
				<string>file:///System/Applications/Notes.app/</string>
				<key>_CFURLStringType</key>
				<integer>15</integer>
			</dict>
			<key>file-label</key>
			<string>Notes</string>
			<key>file-mod-date</key>
			<integer>3712892177</integer>
			<key>file-type</key>
			<integer>41</integer>
			<key>is-beta</key>
			<false/>
			<key>parent-mod-date</key>
			<integer>3712892177</integer>
		</dict>
		<key>tile-type</key>
		<string>file-tile</string>
	</dict>
	<dict>
		<key>GUID</key>
		<integer>3315440945</integer>
		<key>tile-data</key>
		<dict>
			<key>book</key>
			<data>
			Ym9vazwCAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAA
			AAAAAAAAAAAAAAAAAAAAXAEAAAQAAAADAwAAAAAAIAYA
			AAABAQAAU3lzdGVtAAAMAAAAAQEAAEFwcGxpY2F0aW9u
			cwYAAAABAQAAVFYuYXBwAAAMAAAAAQYAABAAAAAgAAAA
			NAAAAAgAAAAEAwAAFQAAAP///w8IAAAABAMAABcAAAD/
			//8PCAAAAAQDAAAELQEA////DwwAAAABBgAAWAAAAGgA
			AAB4AAAACAAAAAAEAABBw2xiCIAAABgAAAABAgAAAgAA
			AAAAAAAPAAAAAAAAAAAAAAAAAAAACAAAAAEJAABmaWxl
			Oi8vLwgAAAABAQAAVW50aXRsZWQIAAAABAMAAAAAhxE5
			AAAAJAAAAAEBAABCNDkwQTAwNC0zMzFGLTQ5MjQtOUND
			OS1CMEVFN0UyNTE0NDIYAAAAAQIAAIEAAAABAAAA7xMA
			AAEAAAAAAAAAAAAAAAEAAAABAQAALwAAAAAAAAABBQAA
			qAAAAP7///8BAAAAAAAAAA0AAAAEEAAARAAAAAAAAAAF
			EAAAiAAAAAAAAAAQEAAArAAAAAAAAABAEAAAnAAAAAAA
			AAACIAAASAEAAAAAAAAFIAAAzAAAAAAAAAAQIAAA3AAA
			AAAAAAARIAAA/AAAAAAAAAASIAAA7AAAAAAAAAATIAAA
			nAAAAAAAAAAgIAAAKAEAAAAAAAAwIAAAVAEAAAAAAAAQ
			0AAABAAAAAAAAAA=
			</data>
			<key>bundle-identifier</key>
			<string>com.apple.TV</string>
			<key>dock-extra</key>
			<false/>
			<key>file-data</key>
			<dict>
				<key>_CFURLString</key>
				<string>file:///System/Applications/TV.app/</string>
				<key>_CFURLStringType</key>
				<integer>15</integer>
			</dict>
			<key>file-label</key>
			<string>TV</string>
			<key>file-mod-date</key>
			<integer>3712892177</integer>
			<key>file-type</key>
			<integer>41</integer>
			<key>is-beta</key>
			<false/>
			<key>parent-mod-date</key>
			<integer>3712892177</integer>
		</dict>
		<key>tile-type</key>
		<string>file-tile</string>
	</dict>
	<dict>
		<key>GUID</key>
		<integer>3315440946</integer>
		<key>tile-data</key>
		<dict>
			<key>book</key>
			<data>
			Ym9va0ACAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAA
			AAAAAAAAAAAAAAAAAAAAYAEAAAQAAAADAwAAAAAAIAYA
			AAABAQAAU3lzdGVtAAAMAAAAAQEAAEFwcGxpY2F0aW9u
			cwkAAAABAQAATXVzaWMuYXBwAAAADAAAAAEGAAAQAAAA
			IAAAADQAAAAIAAAABAMAABUAAAD///8PCAAAAAQDAAAX
			AAAA////DwgAAAAEAwAACZIAAP///w8MAAAAAQYAAFwA
			AABsAAAAfAAAAAgAAAAABAAAQcNsYgiAAAAYAAAAAQIA
			AAIAAAAAAAAADwAAAAAAAAAAAAAAAAAAAAgAAAABCQAA
			ZmlsZTovLy8IAAAAAQEAAFVudGl0bGVkCAAAAAQDAAAA
			AIcROQAAACQAAAABAQAAQjQ5MEEwMDQtMzMxRi00OTI0
			LTlDQzktQjBFRTdFMjUxNDQyGAAAAAECAACBAAAAAQAA
			AO8TAAABAAAAAAAAAAAAAAABAAAAAQEAAC8AAAAAAAAA
			AQUAAKgAAAD+////AQAAAAAAAAANAAAABBAAAEgAAAAA
			AAAABRAAAIwAAAAAAAAAEBAAALAAAAAAAAAAQBAAAKAA
			AAAAAAAAAiAAAEwBAAAAAAAABSAAANAAAAAAAAAAECAA
			AOAAAAAAAAAAESAAAAABAAAAAAAAEiAAAPAAAAAAAAAA
			EyAAAKAAAAAAAAAAICAAACwBAAAAAAAAMCAAAFgBAAAA
			AAAAENAAAAQAAAAAAAAA
			</data>
			<key>bundle-identifier</key>
			<string>com.apple.Music</string>
			<key>dock-extra</key>
			<false/>
			<key>file-data</key>
			<dict>
				<key>_CFURLString</key>
				<string>file:///System/Applications/Music.app/</string>
				<key>_CFURLStringType</key>
				<integer>15</integer>
			</dict>
			<key>file-label</key>
			<string>Music</string>
			<key>file-mod-date</key>
			<integer>3712892177</integer>
			<key>file-type</key>
			<integer>41</integer>
			<key>is-beta</key>
			<false/>
			<key>parent-mod-date</key>
			<integer>3712892177</integer>
		</dict>
		<key>tile-type</key>
		<string>file-tile</string>
	</dict>
	<dict>
		<key>GUID</key>
		<integer>3315440947</integer>
		<key>tile-data</key>
		<dict>
			<key>book</key>
			<data>
			Ym9va0ACAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAA
			AAAAAAAAAAAAAAAAAAAAYAEAAAQAAAADAwAAAAAAIAYA
			AAABAQAAU3lzdGVtAAAMAAAAAQEAAEFwcGxpY2F0aW9u
			cwwAAAABAQAAUG9kY2FzdHMuYXBwDAAAAAEGAAAQAAAA
			IAAAADQAAAAIAAAABAMAABUAAAD///8PCAAAAAQDAAAX
			AAAA////DwgAAAAEAwAAp+8AAP///w8MAAAAAQYAAFwA
			AABsAAAAfAAAAAgAAAAABAAAQcNsYgiAAAAYAAAAAQIA
			AAIAAAAAAAAADwAAAAAAAAAAAAAAAAAAAAgAAAABCQAA
			ZmlsZTovLy8IAAAAAQEAAFVudGl0bGVkCAAAAAQDAAAA
			AIcROQAAACQAAAABAQAAQjQ5MEEwMDQtMzMxRi00OTI0
			LTlDQzktQjBFRTdFMjUxNDQyGAAAAAECAACBAAAAAQAA
			AO8TAAABAAAAAAAAAAAAAAABAAAAAQEAAC8AAAAAAAAA
			AQUAAKgAAAD+////AQAAAAAAAAANAAAABBAAAEgAAAAA
			AAAABRAAAIwAAAAAAAAAEBAAALAAAAAAAAAAQBAAAKAA
			AAAAAAAAAiAAAEwBAAAAAAAABSAAANAAAAAAAAAAECAA
			AOAAAAAAAAAAESAAAAABAAAAAAAAEiAAAPAAAAAAAAAA
			EyAAAKAAAAAAAAAAICAAACwBAAAAAAAAMCAAAFgBAAAA
			AAAAENAAAAQAAAAAAAAA
			</data>
			<key>bundle-identifier</key>
			<string>com.apple.podcasts</string>
			<key>dock-extra</key>
			<false/>
			<key>file-data</key>
			<dict>
				<key>_CFURLString</key>
				<string>file:///System/Applications/Podcasts.app/</string>
				<key>_CFURLStringType</key>
				<integer>15</integer>
			</dict>
			<key>file-label</key>
			<string>Podcasts</string>
			<key>file-mod-date</key>
			<integer>3712892177</integer>
			<key>file-type</key>
			<integer>41</integer>
			<key>is-beta</key>
			<false/>
			<key>parent-mod-date</key>
			<integer>3712892177</integer>
		</dict>
		<key>tile-type</key>
		<string>file-tile</string>
	</dict>
	<dict>
		<key>GUID</key>
		<integer>3315440949</integer>
		<key>tile-data</key>
		<dict>
			<key>book</key>
			<data>
			Ym9va0QCAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAA
			AAAAAAAAAAAAAAAAAAAAZAEAAAQAAAADAwAAAAAAIAYA
			AAABAQAAU3lzdGVtAAAMAAAAAQEAAEFwcGxpY2F0aW9u
			cw0AAAABAQAAQXBwIFN0b3JlLmFwcAAAAAwAAAABBgAA
			EAAAACAAAAA0AAAACAAAAAQDAAAVAAAA////DwgAAAAE
			AwAAFwAAAP///w8IAAAABAMAABkAAAD///8PDAAAAAEG
			AABgAAAAcAAAAIAAAAAIAAAAAAQAAEHDbGIIgAAAGAAA
			AAECAAACAAAAAAAAAA8AAAAAAAAAAAAAAAAAAAAIAAAA
			AQkAAGZpbGU6Ly8vCAAAAAEBAABVbnRpdGxlZAgAAAAE
			AwAAAACHETkAAAAkAAAAAQEAAEI0OTBBMDA0LTMzMUYt
			NDkyNC05Q0M5LUIwRUU3RTI1MTQ0MhgAAAABAgAAgQAA
			AAEAAADvEwAAAQAAAAAAAAAAAAAAAQAAAAEBAAAvAAAA
			AAAAAAEFAACoAAAA/v///wEAAAAAAAAADQAAAAQQAABM
			AAAAAAAAAAUQAACQAAAAAAAAABAQAAC0AAAAAAAAAEAQ
			AACkAAAAAAAAAAIgAABQAQAAAAAAAAUgAADUAAAAAAAA
			ABAgAADkAAAAAAAAABEgAAAEAQAAAAAAABIgAAD0AAAA
			AAAAABMgAACkAAAAAAAAACAgAAAwAQAAAAAAADAgAABc
			AQAAAAAAABDQAAAEAAAAAAAAAA==
			</data>
			<key>bundle-identifier</key>
			<string>com.apple.AppStore</string>
			<key>dock-extra</key>
			<true/>
			<key>file-data</key>
			<dict>
				<key>_CFURLString</key>
				<string>file:///System/Applications/App%20Store.app/</string>
				<key>_CFURLStringType</key>
				<integer>15</integer>
			</dict>
			<key>file-label</key>
			<string>App Store</string>
			<key>file-mod-date</key>
			<integer>3712892177</integer>
			<key>file-type</key>
			<integer>41</integer>
			<key>is-beta</key>
			<false/>
			<key>parent-mod-date</key>
			<integer>3712892177</integer>
		</dict>
		<key>tile-type</key>
		<string>file-tile</string>
	</dict>
	<dict>
		<key>GUID</key>
		<integer>3315440950</integer>
		<key>tile-data</key>
		<dict>
			<key>book</key>
			<data>
			Ym9va0wCAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAA
			AAAAAAAAAAAAAAAAAAAAbAEAAAQAAAADAwAAAAAAIAYA
			AAABAQAAU3lzdGVtAAAMAAAAAQEAAEFwcGxpY2F0aW9u
			cxYAAAABAQAAU3lzdGVtIFByZWZlcmVuY2VzLmFwcAAA
			DAAAAAEGAAAQAAAAIAAAADQAAAAIAAAABAMAABUAAAD/
			//8PCAAAAAQDAAAXAAAA////DwgAAAAEAwAAqSoBAP//
			/w8MAAAAAQYAAGgAAAB4AAAAiAAAAAgAAAAABAAAQcNs
			YgiAAAAYAAAAAQIAAAIAAAAAAAAADwAAAAAAAAAAAAAA
			AAAAAAgAAAABCQAAZmlsZTovLy8IAAAAAQEAAFVudGl0
			bGVkCAAAAAQDAAAAAIcROQAAACQAAAABAQAAQjQ5MEEw
			MDQtMzMxRi00OTI0LTlDQzktQjBFRTdFMjUxNDQyGAAA
			AAECAACBAAAAAQAAAO8TAAABAAAAAAAAAAAAAAABAAAA
			AQEAAC8AAAAAAAAAAQUAAKgAAAD+////AQAAAAAAAAAN
			AAAABBAAAFQAAAAAAAAABRAAAJgAAAAAAAAAEBAAALwA
			AAAAAAAAQBAAAKwAAAAAAAAAAiAAAFgBAAAAAAAABSAA
			ANwAAAAAAAAAECAAAOwAAAAAAAAAESAAAAwBAAAAAAAA
			EiAAAPwAAAAAAAAAEyAAAKwAAAAAAAAAICAAADgBAAAA
			AAAAMCAAAGQBAAAAAAAAENAAAAQAAAAAAAAA
			</data>
			<key>bundle-identifier</key>
			<string>com.apple.systempreferences</string>
			<key>dock-extra</key>
			<true/>
			<key>file-data</key>
			<dict>
				<key>_CFURLString</key>
				<string>file:///System/Applications/System%20Preferences.app/</string>
				<key>_CFURLStringType</key>
				<integer>15</integer>
			</dict>
			<key>file-label</key>
			<string>System Preferences</string>
			<key>file-mod-date</key>
			<integer>3712892177</integer>
			<key>file-type</key>
			<integer>41</integer>
			<key>is-beta</key>
			<false/>
			<key>parent-mod-date</key>
			<integer>3712892177</integer>
		</dict>
		<key>tile-type</key>
		<string>file-tile</string>
	</dict>
	<dict>
		<key>GUID</key>
		<integer>3315440951</integer>
		<key>tile-data</key>
		<dict>
			<key>book</key>
			<data>
			Ym9va6ACAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAA
			AAAAAAAAAAAAAAAAAAAAwAEAAAQAAAADAwAAAAAAIAYA
			AAABAQAAU3lzdGVtAAAHAAAAAQEAAExpYnJhcnkADAAA
			AAEBAABDb3JlU2VydmljZXMMAAAAAQEAAEFwcGxpY2F0
			aW9ucxYAAAABAQAARmVlZGJhY2sgQXNzaXN0YW50LmFw
			cAAAFAAAAAEGAAAQAAAAIAAAADAAAABEAAAAWAAAAAgA
			AAAEAwAAFQAAAP///w8IAAAABAMAAPHCAQD///8PCAAA
			AAQDAADqrwMA////DwgAAAAEAwAAkLwDAP///w8IAAAA
			BAMAAPnIAwD///8PFAAAAAEGAACUAAAApAAAALQAAADE
			AAAA1AAAAAgAAAAABAAAQcNsYgiAAAAYAAAAAQIAAAIA
			AAAAAAAADwAAAAAAAAAAAAAAAAAAAAgAAAABCQAAZmls
			ZTovLy8IAAAAAQEAAFVudGl0bGVkCAAAAAQDAAAAAIcR
			OQAAACQAAAABAQAAQjQ5MEEwMDQtMzMxRi00OTI0LTlD
			QzktQjBFRTdFMjUxNDQyGAAAAAECAACBAAAAAQAAAO8T
			AAABAAAAAAAAAAAAAAABAAAAAQEAAC8AAAAAAAAAAQUA
			AKgAAAD+////AQAAAAAAAAANAAAABBAAAHgAAAAAAAAA
			BRAAAOQAAAAAAAAAEBAAABABAAAAAAAAQBAAAAABAAAA
			AAAAAiAAAKwBAAAAAAAABSAAADABAAAAAAAAECAAAEAB
			AAAAAAAAESAAAGABAAAAAAAAEiAAAFABAAAAAAAAEyAA
			AAABAAAAAAAAICAAAIwBAAAAAAAAMCAAALgBAAAAAAAA
			ENAAAAQAAAAAAAAA
			</data>
			<key>bundle-identifier</key>
			<string>com.apple.appleseed.FeedbackAssistant</string>
			<key>dock-extra</key>
			<false/>
			<key>file-data</key>
			<dict>
				<key>_CFURLString</key>
				<string>file:///System/Library/CoreServices/Applications/Feedback%20Assistant.app/</string>
				<key>_CFURLStringType</key>
				<integer>15</integer>
			</dict>
			<key>file-label</key>
			<string>Feedback Assistant</string>
			<key>file-mod-date</key>
			<integer>3712892177</integer>
			<key>file-type</key>
			<integer>41</integer>
			<key>is-beta</key>
			<false/>
			<key>parent-mod-date</key>
			<integer>3712892177</integer>
		</dict>
		<key>tile-type</key>
		<string>file-tile</string>
	</dict>
</array>
'
defaults write com.apple.dock "persistent-others" '
<array>
	<dict>
		<key>GUID</key>
		<integer>3315440952</integer>
		<key>tile-data</key>
		<dict>
			<key>arrangement</key>
			<integer>2</integer>
			<key>book</key>
			<data>
			Ym9va3wCAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAA
			AAAAAAAAAAAAAAAAAAAAeAEAAAQAAAADAwAAAAAAIAUA
			AAABAQAAVXNlcnMAAAAGAAAAAQEAAG1heGltZQAACQAA
			AAEBAABEb3dubG9hZHMAAAAMAAAAAQYAABAAAAAgAAAA
			MAAAAAgAAAAEAwAAcGQAAAAAAAAIAAAABAMAACGLAAAA
			AAAACAAAAAQDAABUiwAAAAAAAAwAAAABBgAAWAAAAGgA
			AAB4AAAACAAAAAAEAABBw2xiCIAAABgAAAABAgAAAgAA
			AAAAAAAPAAAAAAAAAAAAAAAAAAAACAAAAAQDAAABAAAA
			AAAAAAQAAAADAwAA9QEAAAgAAAABCQAAZmlsZTovLy8I
			AAAAAQEAAFVudGl0bGVkCAAAAAQDAAAAAIcROQAAACQA
			AAABAQAAQjQ5MEEwMDQtMzMxRi00OTI0LTlDQzktQjBF
			RTdFMjUxNDQyGAAAAAECAACBAAAAAQAAAO8TAAABAAAA
			AAAAAAAAAAABAAAAAQEAAC8AAAAAAAAAAQUAAMwAAAD+
			////AQAAAAAAAAAQAAAABBAAAEQAAAAAAAAABRAAAIgA
			AAAAAAAAEBAAAKwAAAAAAAAAQBAAAJwAAAAAAAAAAiAA
			AGQBAAAAAAAABSAAAOgAAAAAAAAAECAAAPgAAAAAAAAA
			ESAAABgBAAAAAAAAEiAAAAgBAAAAAAAAEyAAAJwAAAAA
			AAAAICAAAEQBAAAAAAAAMCAAAHABAAAAAAAAAcAAAMwA
			AAAAAAAAEcAAACAAAAAAAAAAEsAAANwAAAAAAAAAENAA
			AAQAAAAAAAAA
			</data>
			<key>displayas</key>
			<integer>0</integer>
			<key>file-data</key>
			<dict>
				<key>_CFURLString</key>
				<string>file:///Users/maxime/Downloads/</string>
				<key>_CFURLStringType</key>
				<integer>15</integer>
			</dict>
			<key>file-label</key>
			<string>Downloads</string>
			<key>file-mod-date</key>
			<integer>32361999663785</integer>
			<key>file-type</key>
			<integer>2</integer>
			<key>is-beta</key>
			<false/>
			<key>parent-mod-date</key>
			<integer>122247075234482</integer>
			<key>preferreditemsize</key>
			<integer>-1</integer>
			<key>showas</key>
			<integer>1</integer>
		</dict>
		<key>tile-type</key>
		<string>directory-tile</string>
	</dict>
</array>
'
defaults write com.apple.dock "recent-apps" '
<array>
	<dict>
		<key>GUID</key>
		<integer>3315440953</integer>
		<key>tile-data</key>
		<dict>
			<key>book</key>
			<data>
			Ym9va2wCAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAA
			AAAAAAAAAAAAAAAAAAAAjAEAAAQAAAADAwAAAAAAIAYA
			AAABAQAAU3lzdGVtAAAMAAAAAQEAAEFwcGxpY2F0aW9u
			cwkAAAABAQAAVXRpbGl0aWVzAAAADAAAAAEBAABUZXJt
			aW5hbC5hcHAQAAAAAQYAABAAAAAgAAAANAAAAEgAAAAI
			AAAABAMAABUAAAD///8PCAAAAAQDAAAXAAAA////DwgA
			AAAEAwAApkABAP///w8IAAAABAMAAPWsAQD///8PEAAA
			AAEGAAB0AAAAhAAAAJQAAACkAAAACAAAAAAEAABBw2xi
			CIAAABgAAAABAgAAAgAAAAAAAAAPAAAAAAAAAAAAAAAA
			AAAACAAAAAEJAABmaWxlOi8vLwgAAAABAQAAVW50aXRs
			ZWQIAAAABAMAAAAAhxE5AAAAJAAAAAEBAABCNDkwQTAw
			NC0zMzFGLTQ5MjQtOUNDOS1CMEVFN0UyNTE0NDIYAAAA
			AQIAAIEAAAABAAAA7xMAAAEAAAAAAAAAAAAAAAEAAAAB
			AQAALwAAAAAAAAABBQAAqAAAAP7///8BAAAAAAAAAA0A
			AAAEEAAAXAAAAAAAAAAFEAAAtAAAAAAAAAAQEAAA3AAA
			AAAAAABAEAAAzAAAAAAAAAACIAAAeAEAAAAAAAAFIAAA
			/AAAAAAAAAAQIAAADAEAAAAAAAARIAAALAEAAAAAAAAS
			IAAAHAEAAAAAAAATIAAAzAAAAAAAAAAgIAAAWAEAAAAA
			AAAwIAAAhAEAAAAAAAAQ0AAABAAAAAAAAAA=
			</data>
			<key>bundle-identifier</key>
			<string>com.apple.Terminal</string>
			<key>dock-extra</key>
			<false/>
			<key>file-data</key>
			<dict>
				<key>_CFURLString</key>
				<string>file:///System/Applications/Utilities/Terminal.app/</string>
				<key>_CFURLStringType</key>
				<integer>15</integer>
			</dict>
			<key>file-label</key>
			<string>Terminal</string>
			<key>file-mod-date</key>
			<integer>3712892177</integer>
			<key>file-type</key>
			<integer>1</integer>
			<key>is-beta</key>
			<false/>
			<key>parent-mod-date</key>
			<integer>3712892177</integer>
		</dict>
		<key>tile-type</key>
		<string>file-tile</string>
	</dict>
	<dict>
		<key>GUID</key>
		<integer>3315440954</integer>
		<key>tile-data</key>
		<dict>
			<key>book</key>
			<data>
			Ym9va0ACAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAA
			AAAAAAAAAAAAAAAAAAAAYAEAAAQAAAADAwAAAAAAIAYA
			AAABAQAAU3lzdGVtAAAMAAAAAQEAAEFwcGxpY2F0aW9u
			cwwAAAABAQAAVGV4dEVkaXQuYXBwDAAAAAEGAAAQAAAA
			IAAAADQAAAAIAAAABAMAABUAAAD///8PCAAAAAQDAAAX
			AAAA////DwgAAAAEAwAA6zsBAP///w8MAAAAAQYAAFwA
			AABsAAAAfAAAAAgAAAAABAAAQcNsYgiAAAAYAAAAAQIA
			AAIAAAAAAAAADwAAAAAAAAAAAAAAAAAAAAgAAAABCQAA
			ZmlsZTovLy8IAAAAAQEAAFVudGl0bGVkCAAAAAQDAAAA
			AIcROQAAACQAAAABAQAAQjQ5MEEwMDQtMzMxRi00OTI0
			LTlDQzktQjBFRTdFMjUxNDQyGAAAAAECAACBAAAAAQAA
			AO8TAAABAAAAAAAAAAAAAAABAAAAAQEAAC8AAAAAAAAA
			AQUAAKgAAAD+////AQAAAAAAAAANAAAABBAAAEgAAAAA
			AAAABRAAAIwAAAAAAAAAEBAAALAAAAAAAAAAQBAAAKAA
			AAAAAAAAAiAAAEwBAAAAAAAABSAAANAAAAAAAAAAECAA
			AOAAAAAAAAAAESAAAAABAAAAAAAAEiAAAPAAAAAAAAAA
			EyAAAKAAAAAAAAAAICAAACwBAAAAAAAAMCAAAFgBAAAA
			AAAAENAAAAQAAAAAAAAA
			</data>
			<key>bundle-identifier</key>
			<string>com.apple.TextEdit</string>
			<key>dock-extra</key>
			<false/>
			<key>file-data</key>
			<dict>
				<key>_CFURLString</key>
				<string>file:///System/Applications/TextEdit.app/</string>
				<key>_CFURLStringType</key>
				<integer>15</integer>
			</dict>
			<key>file-label</key>
			<string>TextEdit</string>
			<key>file-mod-date</key>
			<integer>3712892177</integer>
			<key>file-type</key>
			<integer>1</integer>
			<key>is-beta</key>
			<false/>
			<key>parent-mod-date</key>
			<integer>3712892177</integer>
		</dict>
		<key>tile-type</key>
		<string>file-tile</string>
	</dict>
</array>
'
defaults write com.apple.dock "region" -string 'FR'
defaults write com.apple.dock "trash-full" -boolean true
defaults write com.apple.dock "version" -integer 1
defaults write com.apple.dock "wvous-br-corner" -integer 14
