#!/usr/bin/env bash

defaults write com.apple.ncprefs "apps" '
<array>
	<dict>
		<key>bundle-id</key>
		<string>com.apple.iCal</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>41951254</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Applications/Calendar.app</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAAEgAAAABAAAABgAAAAIAAAArY29t
				LmFwcGxlLkNhbGVuZGFyTm90aWZpY2F0aW9u
				LkNhbE5DU2VydmljZQAAAAAD
				</data>
				<key>uuid</key>
				<string>88B32D33-A1F1-4B45-B23F-99ABB45506ED</string>
			</dict>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADQAAAABAAAABgAAAAIAAAAXY29t
				LmFwcGxlLkNhbGVuZGFyQWdlbnQAAAAAAw==
				</data>
				<key>uuid</key>
				<string>11F00A99-04AC-4A9C-A8EE-2D81A2EC3095</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>bundle-id</key>
		<string>com.apple.FaceTime</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>41951246</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Applications/FaceTime.app</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADgAAAABAAAABgAAAAIAAAAcY29t
				LmFwcGxlLlRlbGVwaG9ueVV0aWxpdGllcwAA
				AAM=
				</data>
				<key>uuid</key>
				<string>573D9867-13BA-4744-BC24-0E5BEE4E1ED4</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>bundle-id</key>
		<string>com.apple.mail</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>41943054</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Applications/Mail.app</string>
	</dict>
	<dict>
		<key>auth</key>
		<integer>775</integer>
		<key>bundle-id</key>
		<string>com.apple.MobileSMS</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>864550926</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Applications/Messages.app</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADAAAAABAAAABgAAAAIAAAARY29t
				LmFwcGxlLmltYWdlbnQAAAAAAAAD
				</data>
				<key>uuid</key>
				<string>F83A4D3C-DC22-4112-8001-EFBD83797963</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>271</integer>
		<key>bundle-id</key>
		<string>com.apple.reminders</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>864550934</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Library/UserNotifications/Bundles/com.apple.reminders.bundle</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADAAAAABAAAABgAAAAIAAAARY29t
				LmFwcGxlLnJlbWluZGQAAAAAAAAD
				</data>
				<key>uuid</key>
				<string>4DEFE961-33B3-4126-BAF5-DD2787B22EAE</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>bundle-id</key>
		<string>com.apple.Safari</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>41951246</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/Applications/Safari.app</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>2</integer>
				<key>path</key>
				<string>/Applications/Safari.app</string>
				<key>req</key>
				<data>
				+t4MAAAAACwAAAABAAAABgAAAAIAAAAQY29t
				LmFwcGxlLlNhZmFyaQAAAAM=
				</data>
				<key>uuid</key>
				<string>54651278-B1CD-481B-A972-152C3023C0F0</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>6</integer>
		<key>bundle-id</key>
		<string>com.apple.notificationcenter.askpermissions</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>310383127</integer>
		<key>grouping</key>
		<integer>0</integer>
	</dict>
	<dict>
		<key>bundle-id</key>
		<string>_SYSTEM_CENTER_:com.apple.migrationhelper</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>41943575</integer>
		<key>grouping</key>
		<integer>0</integer>
	</dict>
	<dict>
		<key>auth</key>
		<integer>262</integer>
		<key>bundle-id</key>
		<string>com.apple.ScreenTimeNotifications</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>864550924</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Library/UserNotifications/Bundles/com.apple.ScreenTimeNotifications.bundle</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADgAAAABAAAABgAAAAIAAAAZY29t
				LmFwcGxlLlNjcmVlblRpbWVBZ2VudAAAAAAA
				AAM=
				</data>
				<key>uuid</key>
				<string>40A7072A-FF52-4923-8CF0-BCBB72F34597</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>bundle-id</key>
		<string>_SYSTEM_CENTER_:com.apple.accountsd</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>41943575</integer>
		<key>grouping</key>
		<integer>0</integer>
	</dict>
	<dict>
		<key>bundle-id</key>
		<string>_SYSTEM_CENTER_:com.apple.mdmclient</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>41943575</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADAAAAABAAAABgAAAAIAAAATY29t
				LmFwcGxlLm1kbWNsaWVudAAAAAAD
				</data>
				<key>uuid</key>
				<string>4B4CBE27-EFC5-4615-A65B-31655D1767CB</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>6</integer>
		<key>bundle-id</key>
		<string>com.apple.ScreenTimeEnabledNotifications</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>327680148</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Library/UserNotifications/Bundles/com.apple.ScreenTimeEnabledNotifications.bundle</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADgAAAABAAAABgAAAAIAAAAZY29t
				LmFwcGxlLlNjcmVlblRpbWVBZ2VudAAAAAAA
				AAM=
				</data>
				<key>uuid</key>
				<string>06880D36-6690-409F-8E07-F28A6B8B3351</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>bundle-id</key>
		<string>_SYSTEM_CENTER_:com.apple.storeassetd</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>41943575</integer>
		<key>grouping</key>
		<integer>0</integer>
	</dict>
	<dict>
		<key>bundle-id</key>
		<string>_SYSTEM_CENTER_:com.apple.TMHelperAgent</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>41943575</integer>
		<key>grouping</key>
		<integer>0</integer>
	</dict>
	<dict>
		<key>bundle-id</key>
		<string>_SYSTEM_CENTER_:com.apple.appstoreagent</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>41943703</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADAAAAABAAAABgAAAAIAAAATY29t
				LmFwcGxlLmFjY291bnRzZAAAAAAD
				</data>
				<key>uuid</key>
				<string>29D09884-0DF4-4B2D-9337-E4E92DA2EB0D</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>263</integer>
		<key>bundle-id</key>
		<string>com.apple.gamecenter</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>864559118</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Library/UserNotifications/Bundles/com.apple.gamecenter.bundle</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAACwAAAABAAAABgAAAAIAAAAPY29t
				LmFwcGxlLmdhbWVkAAAAAAM=
				</data>
				<key>uuid</key>
				<string>5573344C-5F41-4651-B6FE-0993F975F38D</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>bundle-id</key>
		<string>_SYSTEM_CENTER_:com.apple.askpermissiond</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>41943575</integer>
		<key>grouping</key>
		<integer>0</integer>
	</dict>
	<dict>
		<key>bundle-id</key>
		<string>_SYSTEM_CENTER_:com.apple.BluetoothUIServer</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>41943575</integer>
		<key>grouping</key>
		<integer>0</integer>
	</dict>
	<dict>
		<key>bundle-id</key>
		<string>_SYSTEM_CENTER_:com.apple.followup.alert</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>41943703</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADAAAAABAAAABgAAAAIAAAATY29t
				LmFwcGxlLmZvbGxvd3VwZAAAAAAD
				</data>
				<key>uuid</key>
				<string>EF4F33BD-2055-42C9-A778-5F6EE2247FED</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>4</integer>
		<key>bundle-id</key>
		<string>com.apple.TrySafari</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>327684246</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Library/UserNotifications/Bundles/com.apple.TrySafari.bundle</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADwAAAABAAAABgAAAAIAAAAeY29t
				LmFwcGxlLmNvcmVzZXJ2aWNlcy51aWFnZW50
				AAAAAAAD
				</data>
				<key>uuid</key>
				<string>EABB0551-D6BD-4BC6-8FBF-2B1AA929508D</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>bundle-id</key>
		<string>_SYSTEM_CENTER_:com.apple.CalendarNotification.CalNCService</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>41943575</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAAEgAAAABAAAABgAAAAIAAAArY29t
				LmFwcGxlLkNhbGVuZGFyTm90aWZpY2F0aW9u
				LkNhbE5DU2VydmljZQAAAAAD
				</data>
				<key>uuid</key>
				<string>E38D1092-B41A-418B-8175-3105215B6659</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>311</integer>
		<key>bundle-id</key>
		<string>com.apple.Home</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>864550926</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Library/UserNotifications/Bundles/com.apple.Home.bundle</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAACwAAAABAAAABgAAAAIAAAAPY29t
				LmFwcGxlLmhvbWVkAAAAAAM=
				</data>
				<key>uuid</key>
				<string>9C389AAF-5D88-4A1D-9F07-AA7BCAD59277</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>4</integer>
		<key>bundle-id</key>
		<string>_SYSTEM_CENTER_:com.apple.wifi.usernotifications.autohotspot</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>327680662</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADQAAAABAAAABgAAAAIAAAAYY29t
				LmFwcGxlLndpZmkuV2lGaUFnZW50AAAAAw==
				</data>
				<key>uuid</key>
				<string>B18767A1-9274-4914-9741-E0C3E0C40B5B</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>4</integer>
		<key>bundle-id</key>
		<string>_SYSTEM_CENTER_:com.apple.wifi.usernotifications.diagnostics</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>327680662</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADQAAAABAAAABgAAAAIAAAAYY29t
				LmFwcGxlLndpZmkuV2lGaUFnZW50AAAAAw==
				</data>
				<key>uuid</key>
				<string>95678FD1-0F2A-4163-8D0E-729BB80659F0</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>bundle-id</key>
		<string>_SYSTEM_CENTER_:com.apple.security.keychain-circle-notification</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>41943575</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAAEwAAAABAAAABgAAAAIAAAAvY29t
				LmFwcGxlLnNlY3VyaXR5LktleWNoYWluLUNp
				cmNsZS1Ob3RpZmljYXRpb24AAAAAAw==
				</data>
				<key>uuid</key>
				<string>F6540D75-6378-4EDF-B99D-CD4BE11A75D2</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>7</integer>
		<key>bundle-id</key>
		<string>_SYSTEM_CENTER_:com.apple.SoftwareUpdateNotification</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>327688855</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAAEgAAAABAAAABgAAAAIAAAArY29t
				LmFwcGxlLlNvZnR3YXJlVXBkYXRlTm90aWZp
				Y2F0aW9uTWFuYWdlcgAAAAAD
				</data>
				<key>uuid</key>
				<string>72E69CDC-85F8-4177-A375-D1185376DEC5</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>263</integer>
		<key>bundle-id</key>
		<string>com.apple.AppStore.notifications</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>864551062</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Library/UserNotifications/Bundles/com.apple.AppStore.notifications.bundle</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADQAAAABAAAABgAAAAIAAAAXY29t
				LmFwcGxlLmFwcHN0b3JlYWdlbnQAAAAAAw==
				</data>
				<key>uuid</key>
				<string>095AE02F-0133-4FB2-A532-1B90D50A821F</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>0</integer>
		<key>bundle-id</key>
		<string>com.apple.AppStore</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>268443662</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Applications/App Store.app</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADQAAAABAAAABgAAAAIAAAAXY29t
				LmFwcGxlLmFwcHN0b3JlYWdlbnQAAAAAAw==
				</data>
				<key>uuid</key>
				<string>02792EEE-6F13-42F3-9A64-ADB00DB5C241</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>bundle-id</key>
		<string>com.apple.iChat</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>41943054</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADgAAAABAAAABgAAAAIAAAAbY29t
				LmFwcGxlLmlkZW50aXR5c2VydmljZXNkAAAA
				AAM=
				</data>
				<key>uuid</key>
				<string>2476DD65-27BE-4689-9D7E-570E9629F635</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>bundle-id</key>
		<string>_SYSTEM_CENTER_:com.apple.sharingd</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>41943575</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADAAAAABAAAABgAAAAIAAAASY29t
				LmFwcGxlLnNoYXJpbmdkAAAAAAAD
				</data>
				<key>uuid</key>
				<string>2E8B5B9B-391C-48A5-8FF2-8069F77A83AA</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>bundle-id</key>
		<string>_SYSTEM_CENTER_:com.apple.sharingd.continuity</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>41943575</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADAAAAABAAAABgAAAAIAAAASY29t
				LmFwcGxlLnNoYXJpbmdkAAAAAAAD
				</data>
				<key>uuid</key>
				<string>078D44A7-3C75-48AB-8097-A6D20BCF20DC</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>bundle-id</key>
		<string>_SYSTEM_CENTER_:com.apple.FaceTime</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>41943575</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADgAAAABAAAABgAAAAIAAAAcY29t
				LmFwcGxlLlRlbGVwaG9ueVV0aWxpdGllcwAA
				AAM=
				</data>
				<key>uuid</key>
				<string>685E0B36-3049-460C-9ED5-65E0C3FCA081</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>7</integer>
		<key>bundle-id</key>
		<string>com.apple.Photos</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>310386702</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Applications/Photos.app</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADQAAAABAAAABgAAAAIAAAAXY29t
				LmFwcGxlLnBob3RvbGlicmFyeWQAAAAAAw==
				</data>
				<key>uuid</key>
				<string>92F3B6C1-5358-4D1C-813A-6AAF34BFC6BB</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>bundle-id</key>
		<string>_SYSTEM_CENTER_:com.apple.MobileAccessoryUpdater.fudHelperAgent</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>41943575</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADQAAAABAAAABgAAAAIAAAAYY29t
				LmFwcGxlLmZ1ZEhlbHBlckFnZW50AAAAAw==
				</data>
				<key>uuid</key>
				<string>9C8E3EC1-2F70-454F-A221-38AC51F2A1F0</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>bundle-id</key>
		<string>com.apple.TelephonyUtilities</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>41951246</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADAAAAABAAAABgAAAAIAAAARY29t
				LmFwcGxlLmltYWdlbnQAAAAAAAAD
				</data>
				<key>uuid</key>
				<string>9C9CB0A0-7917-4C1A-879E-C6A18412EB0A</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>6</integer>
		<key>bundle-id</key>
		<string>com.apple.BTUserNotifications</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>327688342</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Library/UserNotifications/Bundles/com.apple.BTUserNotifications.bundle</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADAAAAABAAAABgAAAAIAAAAUY29t
				LmFwcGxlLmNsb3VkcGFpcmQAAAAD
				</data>
				<key>uuid</key>
				<string>F53D62B7-39A8-4257-882B-4FC2199F103D</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>295</integer>
		<key>bundle-id</key>
		<string>com.apple.Passbook</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>864550926</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Library/UserNotifications/Bundles/com.apple.Passbook.bundle</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAACwAAAABAAAABgAAAAIAAAAPY29t
				LmFwcGxlLnBhc3NkAAAAAAM=
				</data>
				<key>uuid</key>
				<string>4E9DB511-8EBF-4C50-BCC6-7AFE2987F66A</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>0</integer>
		<key>bundle-id</key>
		<string>com.apple.TV</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>268443662</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Applications/TV.app</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADAAAAABAAAABgAAAAIAAAAUY29t
				LmFwcGxlLndhdGNobGlzdGQAAAAD
				</data>
				<key>uuid</key>
				<string>9F31114C-19D4-4F18-B91C-C96BA89849CC</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>7</integer>
		<key>bundle-id</key>
		<string>com.apple.controlcenter.notifications.low-battery</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>327688342</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Library/UserNotifications/Bundles/com.apple.controlcenter.notifications.low-battery.bundle</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADQAAAABAAAABgAAAAIAAAAXY29t
				LmFwcGxlLmNvbnRyb2xjZW50ZXIAAAAAAw==
				</data>
				<key>uuid</key>
				<string>26949073-FB81-4CFD-9EE5-D4AA5C551B1E</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>bundle-id</key>
		<string>com.apple.iBooksX</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>41951246</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Applications/Books.app</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>2</integer>
				<key>path</key>
				<string>/System/Library/PrivateFrameworks/CommerceKit.framework/Versions/A/Resources/commerce</string>
				<key>req</key>
				<data>
				+t4MAAAAADAAAAABAAAABgAAAAIAAAASY29t
				LmFwcGxlLmNvbW1lcmNlAAAAAAAD
				</data>
				<key>uuid</key>
				<string>B730F2DF-8641-4421-A655-F479F1C2FA09</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>263</integer>
		<key>bundle-id</key>
		<string>com.apple.askpermission.notifications</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>864551062</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Library/UserNotifications/Bundles/com.apple.askpermission.notifications.bundle</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADQAAAABAAAABgAAAAIAAAAYY29t
				LmFwcGxlLmFza3Blcm1pc3Npb25kAAAAAw==
				</data>
				<key>uuid</key>
				<string>789C1BA8-9E4A-4794-AA2C-742FE4C47595</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>7</integer>
		<key>bundle-id</key>
		<string>com.apple.universalcontrol.notifications.displays</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>327688342</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Library/UserNotifications/Bundles/com.apple.universalcontrol.notifications.displays.bundle</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADgAAAABAAAABgAAAAIAAAAaY29t
				LmFwcGxlLnVuaXZlcnNhbGNvbnRyb2wAAAAA
				AAM=
				</data>
				<key>uuid</key>
				<string>5E3B9B94-31CC-47C3-BA3B-3CCBC3ECB108</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>7</integer>
		<key>bundle-id</key>
		<string>com.apple.mdmclient.usernotifications.v2</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>327688342</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Library/UserNotifications/Bundles/com.apple.mdmclient.usernotifications.v2.bundle</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADAAAAABAAAABgAAAAIAAAATY29t
				LmFwcGxlLm1kbWNsaWVudAAAAAAD
				</data>
				<key>uuid</key>
				<string>0BCE1377-A274-4C1D-B834-37C3EC412468</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>7</integer>
		<key>bundle-id</key>
		<string>com.apple.appleaccount.notifications</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>327680142</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Library/UserNotifications/Bundles/com.apple.appleaccount.notifications.bundle</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADQAAAABAAAABgAAAAIAAAAXY29t
				LmFwcGxlLmFwcGxlYWNjb3VudGQAAAAAAw==
				</data>
				<key>uuid</key>
				<string>2CFFD605-477B-4B27-9504-57FFB29D89F2</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>4</integer>
		<key>bundle-id</key>
		<string>com.apple.tips</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>327680022</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Library/UserNotifications/Bundles/com.apple.tips.bundle</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAACwAAAABAAAABgAAAAIAAAAPY29t
				LmFwcGxlLnRpcHNkAAAAAAM=
				</data>
				<key>uuid</key>
				<string>CC06B6FC-F446-4215-BD3B-38F5E64F6054</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>bundle-id</key>
		<string>_SYSTEM_CENTER_:com.apple.USBAgent</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>41943575</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADAAAAABAAAABgAAAAIAAAASY29t
				LmFwcGxlLlVTQkFnZW50AAAAAAAD
				</data>
				<key>uuid</key>
				<string>D1D53008-DD2F-4A1B-86F2-F03972E95A46</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>6</integer>
		<key>bundle-id</key>
		<string>com.apple.studentd.notifications</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>327688342</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Library/UserNotifications/Bundles/com.apple.studentd.notifications.bundle</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADAAAAABAAAABgAAAAIAAAASY29t
				LmFwcGxlLnN0dWRlbnRkAAAAAAAD
				</data>
				<key>uuid</key>
				<string>2403FC0F-EE79-42CD-807C-546607D0A852</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>4</integer>
		<key>bundle-id</key>
		<string>com.apple.ReplayKitNotifications</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>327688334</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Library/UserNotifications/Bundles/com.apple.ReplayKitNotifications.bundle</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADAAAAABAAAABgAAAAIAAAARY29t
				LmFwcGxlLnJlcGxheWQAAAAAAAAD
				</data>
				<key>uuid</key>
				<string>38B16A08-CF52-40D7-9EBE-08A3D1779EA5</string>
			</dict>
		</array>
	</dict>
</array>
'
defaults write com.apple.ncprefs "content_visibility" -integer 2
defaults write com.apple.ncprefs "dnd_prefs" '
<data>
YnBsaXN0MDDVAQIDBAUGBggICFtkbmRNaXJyb3JlZF8QD2RuZERpc3BsYXlTbGVlcF8Q
HnJlcGVhdGVkRmFjZXRpbWVDYWxsc0JyZWFrc0RORF5kbmREaXNwbGF5TG9ja18QE2Zh
Y2V0aW1lQ2FuQnJlYWtETkQJCQgICAgTHzFSYXd4eXp7AAAAAAAAAQEAAAAAAAAACwAA
AAAAAAAAAAAAAAAAAHw=
</data>
'
defaults write com.apple.ncprefs "sort_order" -integer 0
defaults write com.apple.ncprefs "version" -integer 1
