#!/usr/bin/env bash

defaults write com.apple.spaces "SpacesDisplayConfiguration" '
<dict>
	<key>Management Data</key>
	<dict>
		<key>Age</key>
		<real>4903.5944406666677</real>
		<key>Management Mode</key>
		<integer>1</integer>
		<key>Monitors</key>
		<array>
			<dict>
				<key>Current Space</key>
				<dict>
					<key>ManagedSpaceID</key>
					<integer>1</integer>
					<key>id64</key>
					<integer>1</integer>
					<key>type</key>
					<integer>0</integer>
					<key>uuid</key>
					<string></string>
					<key>wsid</key>
					<integer>1</integer>
				</dict>
				<key>Display Identifier</key>
				<string>Main</string>
				<key>Spaces</key>
				<array>
					<dict>
						<key>ManagedSpaceID</key>
						<integer>1</integer>
						<key>id64</key>
						<integer>1</integer>
						<key>type</key>
						<integer>0</integer>
						<key>uuid</key>
						<string></string>
						<key>wsid</key>
						<integer>1</integer>
					</dict>
				</array>
			</dict>
			<dict>
				<key>Current Space</key>
				<dict>
					<key>ManagedSpaceID</key>
					<integer>12</integer>
					<key>id64</key>
					<integer>12</integer>
					<key>type</key>
					<integer>0</integer>
					<key>uuid</key>
					<string>C12285C3-6422-4A66-A5BE-BB526779AB11</string>
				</dict>
				<key>Display Identifier</key>
				<string>4B08E384-B118-3977-0857-D6964E3302DB</string>
				<key>Spaces</key>
				<array>
					<dict>
						<key>ManagedSpaceID</key>
						<integer>12</integer>
						<key>id64</key>
						<integer>12</integer>
						<key>type</key>
						<integer>0</integer>
						<key>uuid</key>
						<string>C12285C3-6422-4A66-A5BE-BB526779AB11</string>
					</dict>
				</array>
			</dict>
		</array>
		<key>Primary</key>
		<dict>
			<key>CreatedCount</key>
			<integer>0</integer>
			<key>DeletedCount</key>
			<integer>0</integer>
			<key>LifetimeEntryCount</key>
			<integer>0</integer>
			<key>LifetimeMax</key>
			<real>0.0</real>
			<key>LifetimeMin</key>
			<real>0.0</real>
			<key>LifetimeSum</key>
			<real>0.0</real>
			<key>PersistedCount</key>
			<integer>0</integer>
		</dict>
		<key>Secondary</key>
		<dict>
			<key>CreatedCount</key>
			<integer>0</integer>
			<key>DeletedCount</key>
			<integer>0</integer>
			<key>LifetimeEntryCount</key>
			<integer>0</integer>
			<key>LifetimeMax</key>
			<real>0.0</real>
			<key>LifetimeMin</key>
			<real>0.0</real>
			<key>LifetimeSum</key>
			<real>0.0</real>
			<key>PersistedCount</key>
			<integer>0</integer>
		</dict>
	</dict>
	<key>Space Properties</key>
	<array>
		<dict>
			<key>name</key>
			<string></string>
			<key>windows</key>
			<array>
				<integer>74</integer>
				<integer>261</integer>
				<integer>181</integer>
				<integer>178</integer>
				<integer>108</integer>
				<integer>84</integer>
				<integer>147</integer>
				<integer>60</integer>
				<integer>43</integer>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>C12285C3-6422-4A66-A5BE-BB526779AB11</string>
			<key>windows</key>
			<array>
				<integer>124</integer>
				<integer>120</integer>
				<integer>117</integer>
			</array>
		</dict>
	</array>
</dict>
'
