#!/usr/bin/env bash

defaults write com.apple.finder "CopyProgressWindowLocation" -string '{1080, 341}'
defaults write com.apple.finder "DesktopViewSettings" '
<dict>
	<key>IconViewSettings</key>
	<dict>
		<key>arrangeBy</key>
		<string>none</string>
		<key>backgroundColorBlue</key>
		<real>1</real>
		<key>backgroundColorGreen</key>
		<real>1</real>
		<key>backgroundColorRed</key>
		<real>1</real>
		<key>backgroundType</key>
		<integer>0</integer>
		<key>gridOffsetX</key>
		<real>0.0</real>
		<key>gridOffsetY</key>
		<real>0.0</real>
		<key>gridSpacing</key>
		<real>54</real>
		<key>iconSize</key>
		<real>64</real>
		<key>labelOnBottom</key>
		<true/>
		<key>showIconPreview</key>
		<true/>
		<key>showItemInfo</key>
		<false/>
		<key>textSize</key>
		<real>12</real>
		<key>viewOptionsVersion</key>
		<integer>1</integer>
	</dict>
</dict>
'
defaults write com.apple.finder "DownloadsFolderListViewSettingsVersion" -integer 1
defaults write com.apple.finder "FK_AppCentricShowSidebar" -boolean true
defaults write com.apple.finder "FK_SidebarWidth" -float 137
defaults write com.apple.finder "FK_StandardViewSettings" '
<dict>
	<key>ExtendedListViewSettingsV2</key>
	<dict>
		<key>calculateAllSizes</key>
		<false/>
		<key>columns</key>
		<array>
			<dict>
				<key>ascending</key>
				<true/>
				<key>identifier</key>
				<string>name</string>
				<key>visible</key>
				<true/>
				<key>width</key>
				<integer>300</integer>
			</dict>
			<dict>
				<key>ascending</key>
				<false/>
				<key>identifier</key>
				<string>dateModified</string>
				<key>visible</key>
				<true/>
				<key>width</key>
				<integer>181</integer>
			</dict>
			<dict>
				<key>ascending</key>
				<false/>
				<key>identifier</key>
				<string>dateCreated</string>
				<key>visible</key>
				<false/>
				<key>width</key>
				<integer>181</integer>
			</dict>
			<dict>
				<key>ascending</key>
				<false/>
				<key>identifier</key>
				<string>size</string>
				<key>visible</key>
				<true/>
				<key>width</key>
				<integer>97</integer>
			</dict>
			<dict>
				<key>ascending</key>
				<true/>
				<key>identifier</key>
				<string>kind</string>
				<key>visible</key>
				<true/>
				<key>width</key>
				<integer>115</integer>
			</dict>
			<dict>
				<key>ascending</key>
				<true/>
				<key>identifier</key>
				<string>label</string>
				<key>visible</key>
				<false/>
				<key>width</key>
				<integer>100</integer>
			</dict>
			<dict>
				<key>ascending</key>
				<true/>
				<key>identifier</key>
				<string>version</string>
				<key>visible</key>
				<false/>
				<key>width</key>
				<integer>75</integer>
			</dict>
			<dict>
				<key>ascending</key>
				<true/>
				<key>identifier</key>
				<string>comments</string>
				<key>visible</key>
				<false/>
				<key>width</key>
				<integer>300</integer>
			</dict>
			<dict>
				<key>ascending</key>
				<false/>
				<key>identifier</key>
				<string>dateLastOpened</string>
				<key>visible</key>
				<false/>
				<key>width</key>
				<integer>200</integer>
			</dict>
			<dict>
				<key>ascending</key>
				<false/>
				<key>identifier</key>
				<string>shareOwner</string>
				<key>visible</key>
				<false/>
				<key>width</key>
				<integer>200</integer>
			</dict>
			<dict>
				<key>ascending</key>
				<false/>
				<key>identifier</key>
				<string>shareLastEditor</string>
				<key>visible</key>
				<false/>
				<key>width</key>
				<integer>200</integer>
			</dict>
		</array>
		<key>iconSize</key>
		<integer>16</integer>
		<key>showIconPreview</key>
		<true/>
		<key>sortColumn</key>
		<string>name</string>
		<key>textSize</key>
		<integer>13</integer>
		<key>useRelativeDates</key>
		<true/>
		<key>viewOptionsVersion</key>
		<integer>1</integer>
	</dict>
	<key>IconViewSettings</key>
	<dict>
		<key>arrangeBy</key>
		<string>none</string>
		<key>backgroundColorBlue</key>
		<real>1</real>
		<key>backgroundColorGreen</key>
		<real>1</real>
		<key>backgroundColorRed</key>
		<real>1</real>
		<key>backgroundType</key>
		<integer>0</integer>
		<key>gridOffsetX</key>
		<real>0.0</real>
		<key>gridOffsetY</key>
		<real>0.0</real>
		<key>gridSpacing</key>
		<real>54</real>
		<key>iconSize</key>
		<real>64</real>
		<key>labelOnBottom</key>
		<true/>
		<key>showIconPreview</key>
		<true/>
		<key>showItemInfo</key>
		<false/>
		<key>textSize</key>
		<real>12</real>
		<key>viewOptionsVersion</key>
		<integer>1</integer>
	</dict>
	<key>ListViewSettings</key>
	<dict>
		<key>calculateAllSizes</key>
		<false/>
		<key>columns</key>
		<dict>
			<key>comments</key>
			<dict>
				<key>ascending</key>
				<true/>
				<key>index</key>
				<integer>7</integer>
				<key>visible</key>
				<false/>
				<key>width</key>
				<integer>300</integer>
			</dict>
			<key>dateCreated</key>
			<dict>
				<key>ascending</key>
				<false/>
				<key>index</key>
				<integer>2</integer>
				<key>visible</key>
				<false/>
				<key>width</key>
				<integer>181</integer>
			</dict>
			<key>dateLastOpened</key>
			<dict>
				<key>ascending</key>
				<false/>
				<key>index</key>
				<integer>8</integer>
				<key>visible</key>
				<false/>
				<key>width</key>
				<integer>200</integer>
			</dict>
			<key>dateModified</key>
			<dict>
				<key>ascending</key>
				<false/>
				<key>index</key>
				<integer>1</integer>
				<key>visible</key>
				<true/>
				<key>width</key>
				<integer>181</integer>
			</dict>
			<key>kind</key>
			<dict>
				<key>ascending</key>
				<true/>
				<key>index</key>
				<integer>4</integer>
				<key>visible</key>
				<true/>
				<key>width</key>
				<integer>115</integer>
			</dict>
			<key>label</key>
			<dict>
				<key>ascending</key>
				<true/>
				<key>index</key>
				<integer>5</integer>
				<key>visible</key>
				<false/>
				<key>width</key>
				<integer>100</integer>
			</dict>
			<key>name</key>
			<dict>
				<key>ascending</key>
				<true/>
				<key>index</key>
				<integer>0</integer>
				<key>visible</key>
				<true/>
				<key>width</key>
				<integer>300</integer>
			</dict>
			<key>size</key>
			<dict>
				<key>ascending</key>
				<false/>
				<key>index</key>
				<integer>3</integer>
				<key>visible</key>
				<true/>
				<key>width</key>
				<integer>97</integer>
			</dict>
			<key>version</key>
			<dict>
				<key>ascending</key>
				<true/>
				<key>index</key>
				<integer>6</integer>
				<key>visible</key>
				<false/>
				<key>width</key>
				<integer>75</integer>
			</dict>
		</dict>
		<key>iconSize</key>
		<integer>16</integer>
		<key>showIconPreview</key>
		<true/>
		<key>sortColumn</key>
		<string>name</string>
		<key>textSize</key>
		<integer>13</integer>
		<key>useRelativeDates</key>
		<true/>
		<key>viewOptionsVersion</key>
		<integer>1</integer>
	</dict>
	<key>SettingsType</key>
	<string>FK_StandardViewSettings</string>
</dict>
'
defaults write com.apple.finder "FXArrangeGroupViewBy" -string 'Name'
defaults write com.apple.finder "FXDesktopTouchBarUpgradedToTenTwelveOne" -integer 1
defaults write com.apple.finder "FXDesktopVolumePositions" '
<dict>
	<key>Install macOS Monterey beta_0x1.3847e258p+29</key>
	<dict>
		<key>AnchorRelativeTo</key>
		<integer>1</integer>
		<key>ScreenID</key>
		<integer>0</integer>
		<key>xRelative</key>
		<integer>-65</integer>
		<key>yRelative</key>
		<integer>65</integer>
	</dict>
	<key>Samsung-T7_-0x1.d27e44p+29</key>
	<dict>
		<key>AnchorRelativeTo</key>
		<integer>1</integer>
		<key>ScreenID</key>
		<integer>0</integer>
		<key>xRelative</key>
		<integer>-65</integer>
		<key>yRelative</key>
		<integer>65</integer>
	</dict>
</dict>
'
defaults write com.apple.finder "FXICloudDriveDeclinedUpgrade" -boolean false
defaults write com.apple.finder "FXICloudDriveDesktop" -boolean false
defaults write com.apple.finder "FXICloudDriveDocuments" -boolean false
defaults write com.apple.finder "FXICloudDriveEnabled" -boolean true
defaults write com.apple.finder "FXICloudDriveFirstSyncDownComplete" -boolean true
defaults write com.apple.finder "FXICloudLoggedIn" -boolean true
defaults write com.apple.finder "FXLastSearchScope" -string 'SCcf'
defaults write com.apple.finder "FXPreferredSearchViewStyleVersion" -string '%00%00%00%01'
defaults write com.apple.finder "FXQuickActionsConfigUpgradeLevel" -integer 2
defaults write com.apple.finder "FXRecentFolders" '
<array>
	<dict>
		<key>file-bookmark</key>
		<data>
		Ym9va9ACAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAAwAEAAAQAAAADAwAAAAIAIAUAAAABAQAAVXNlcnMA
		AAAGAAAAAQEAAG1heGltZQAACQAAAAEBAABEb3dubG9hZHMAAAAW
		AAAAAQEAAGRlZmF1bHRzLnNoLTIwMjEuMDQuMTAAABAAAAABBgAA
		EAAAACAAAAAwAAAARAAAAAgAAAAEAwAAcGQAAAAAAAAIAAAABAMA
		ACGLAAAAAAAACAAAAAQDAABUiwAAAAAAAAgAAAAEAwAAuwEFAAAA
		AAAQAAAAAQYAAHwAAACMAAAAnAAAAKwAAAAIAAAAAAQAAEHDEKy9
		AAAAGAAAAAECAAACAAAAAAAAAA8AAAAAAAAAAAAAAAAAAAAAAAAA
		AQUAAAgAAAAEAwAAAgAAAAAAAAAEAAAAAwMAAPUBAAAIAAAAAQkA
		AGZpbGU6Ly8vCAAAAAEBAABVbnRpdGxlZAgAAAAEAwAAAACHETkA
		AAAIAAAAAAQAAEHDbGIIgAAAJAAAAAEBAABCNDkwQTAwNC0zMzFG
		LTQ5MjQtOUNDOS1CMEVFN0UyNTE0NDIYAAAAAQIAAIEAAAABAAAA
		7xMAAAEAAAAAAAAAAAAAAAEAAAABAQAALwAAANgAAAD+////AQAA
		AAAAAAARAAAABBAAAGQAAAAAAAAABRAAALwAAAAAAAAAEBAAAOQA
		AAAAAAAAQBAAANQAAAAAAAAAAiAAALQBAAAAAAAABSAAACgBAAAA
		AAAAECAAADgBAAAAAAAAESAAAGgBAAAAAAAAEiAAAEgBAAAAAAAA
		EyAAAFgBAAAAAAAAICAAAJQBAAAAAAAAMCAAAAQBAAAAAAAAAcAA
		AAwBAAAAAAAAEcAAACAAAAAAAAAAEsAAABwBAAAAAAAAAdAAAAQB
		AAAAAAAAENAAAAQAAAAAAAAA
		</data>
		<key>name</key>
		<string>defaults.sh-2021.04.10</string>
	</dict>
	<dict>
		<key>file-bookmark</key>
		<data>
		Ym9va8ADAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAA1AIAAAQAAAADAwAAAAIAIAcAAAABAQAAVm9sdW1l
		cwAKAAAAAQEAAFNhbXN1bmctVDcAAA0AAAABAQAAUHJlZmVyZW5j
		ZXNfMQAAABMAAAABAQAAU3lzdGVtQ29uZmlndXJhdGlvbgAQAAAA
		AQYAABAAAAAgAAAANAAAAEwAAAAIAAAABAMAAAhuAAAAAAAAAAAA
		AAEKAAAQAAAAAQYAAIAAAACQAAAAkAAAAJAAAAAIAAAAAAQAAEHD
		ewMIgAAAGAAAAAECAAACAAAAAAAAAA8AAAAAAAAAAAAAAAAAAAAA
		AAAAAQUAABsAAAABCQAAZmlsZTovLy9Wb2x1bWVzL1NhbXN1bmct
		VDcvAAgAAAAEAwAAAABQ0ugAAAAIAAAAAAQAAMHNJ+RAAAAAJAAA
		AAEBAAAxRjg3QjFGNi1FQzI5LTMwREQtQUVBQi00MEVGNTc0NzE2
		QTkYAAAAAQIAAAEBAAAAAAAA7xMAAAEAAAAAAAAAAAAAABMAAAAB
		AQAAL1ZvbHVtZXMvU2Ftc3VuZy1UNwAIAAAAAQkAAGZpbGU6Ly8v
		CAAAAAEBAABVbnRpdGxlZAgAAAAEAwAAAACHETkAAAAIAAAAAAQA
		AEHDbGIIgAAAJAAAAAEBAABCNDkwQTAwNC0zMzFGLTQ5MjQtOUND
		OS1CMEVFN0UyNTE0NDIYAAAAAQIAAIEAAAABAAAA7xMAAAEAAAAA
		AAAAAAAAAAEAAAABAQAALwAAAGAAAAD+////APAAAAAAAAAHAAAA
		AiAAACACAAAAAAAABSAAAJQBAAAAAAAAECAAAKQBAAAAAAAAESAA
		ANQBAAAAAAAAEiAAALQBAAAAAAAAEyAAAMQBAAAAAAAAICAAAAAC
		AAAAAAAABAAAAAMDAAAA8AAABAAAAAMDAAAAAAAABAAAAAMDAAAB
		AAAAFAAAAAEGAACUAgAAoAIAAKwCAACgAgAAoAIAALQAAAD+////
		AQAAACwCAAAOAAAABBAAAGgAAAAAAAAABRAAAJgAAAAAAAAAEBAA
		AMAAAAAAAAAAQBAAALAAAAAAAAAAACAAALgCAAAAAAAAAiAAAHgB
		AAAAAAAABSAAAOgAAAAAAAAAECAAACAAAAAAAAAAESAAACwBAAAA
		AAAAEiAAAAwBAAAAAAAAEyAAABwBAAAAAAAAICAAAFgBAAAAAAAA
		AdAAAOAAAAAAAAAAENAAAAQAAAAAAAAA
		</data>
		<key>name</key>
		<string>SystemConfiguration</string>
	</dict>
	<dict>
		<key>file-bookmark</key>
		<data>
		Ym9va5gDAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAArAIAAAQAAAADAwAAAAIAIAcAAAABAQAAVm9sdW1l
		cwAKAAAAAQEAAFNhbXN1bmctVDcAAA0AAAABAQAAUHJlZmVyZW5j
		ZXNfMQAAAAwAAAABBgAAEAAAACAAAAA0AAAACAAAAAQDAAAIbgAA
		AAAAAAAAAAABCgAADAAAAAEGAABgAAAAcAAAAHAAAAAIAAAAAAQA
		AEHDewL5gAAAGAAAAAECAAACAAAAAAAAAA8AAAAAAAAAAAAAAAAA
		AAAAAAAAAQUAABsAAAABCQAAZmlsZTovLy9Wb2x1bWVzL1NhbXN1
		bmctVDcvAAgAAAAEAwAAAABQ0ugAAAAIAAAAAAQAAMHNJ+RAAAAA
		JAAAAAEBAAAxRjg3QjFGNi1FQzI5LTMwREQtQUVBQi00MEVGNTc0
		NzE2QTkYAAAAAQIAAAEBAAAAAAAA7xMAAAEAAAAAAAAAAAAAABMA
		AAABAQAAL1ZvbHVtZXMvU2Ftc3VuZy1UNwAIAAAAAQkAAGZpbGU6
		Ly8vCAAAAAEBAABVbnRpdGxlZAgAAAAEAwAAAACHETkAAAAIAAAA
		AAQAAEHDbGIIgAAAJAAAAAEBAABCNDkwQTAwNC0zMzFGLTQ5MjQt
		OUNDOS1CMEVFN0UyNTE0NDIYAAAAAQIAAIEAAAABAAAA7xMAAAEA
		AAAAAAAAAAAAAAEAAAABAQAALwAAAGAAAAD+////APAAAAAAAAAH
		AAAAAiAAAPwBAAAAAAAABSAAAHABAAAAAAAAECAAAIABAAAAAAAA
		ESAAALABAAAAAAAAEiAAAJABAAAAAAAAEyAAAKABAAAAAAAAICAA
		ANwBAAAAAAAABAAAAAMDAAAA8AAABAAAAAMDAAAAAAAABAAAAAMD
		AAABAAAAEAAAAAEGAABwAgAAfAIAAIgCAAB8AgAAtAAAAP7///8B
		AAAACAIAAA4AAAAEEAAATAAAAAAAAAAFEAAAeAAAAAAAAAAQEAAA
		nAAAAAAAAABAEAAAjAAAAAAAAAAAIAAAlAIAAAAAAAACIAAAVAEA
		AAAAAAAFIAAAxAAAAAAAAAAQIAAAIAAAAAAAAAARIAAACAEAAAAA
		AAASIAAA6AAAAAAAAAATIAAA+AAAAAAAAAAgIAAANAEAAAAAAAAB
		0AAAvAAAAAAAAAAQ0AAABAAAAAAAAAA=
		</data>
		<key>name</key>
		<string>Preferences_1</string>
	</dict>
	<dict>
		<key>file-bookmark</key>
		<data>
		Ym9va5ADAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAApAIAAAQAAAADAwAAAAIAIAcAAAABAQAAVm9sdW1l
		cwAKAAAAAQEAAFNhbXN1bmctVDcAAAYAAAABAQAATWF4aW1lAAAM
		AAAAAQYAABAAAAAgAAAANAAAAAgAAAAEAwAACG4AAAAAAAAAAAAA
		AQoAAAwAAAABBgAAWAAAAGgAAABoAAAACAAAAAAEAABBwXTRFIAA
		ABgAAAABAgAAAgAAAAAAAAAPAAAAAAAAAAAAAAAAAAAAAAAAAAEF
		AAAbAAAAAQkAAGZpbGU6Ly8vVm9sdW1lcy9TYW1zdW5nLVQ3LwAI
		AAAABAMAAAAAUNLoAAAACAAAAAAEAADBzSfkQAAAACQAAAABAQAA
		MUY4N0IxRjYtRUMyOS0zMERELUFFQUItNDBFRjU3NDcxNkE5GAAA
		AAECAAABAQAAAAAAAO8TAAABAAAAAAAAAAAAAAATAAAAAQEAAC9W
		b2x1bWVzL1NhbXN1bmctVDcACAAAAAEJAABmaWxlOi8vLwgAAAAB
		AQAAVW50aXRsZWQIAAAABAMAAAAAhxE5AAAACAAAAAAEAABBw2xi
		CIAAACQAAAABAQAAQjQ5MEEwMDQtMzMxRi00OTI0LTlDQzktQjBF
		RTdFMjUxNDQyGAAAAAECAACBAAAAAQAAAO8TAAABAAAAAAAAAAAA
		AAABAAAAAQEAAC8AAABgAAAA/v///wDwAAAAAAAABwAAAAIgAAD0
		AQAAAAAAAAUgAABoAQAAAAAAABAgAAB4AQAAAAAAABEgAACoAQAA
		AAAAABIgAACIAQAAAAAAABMgAACYAQAAAAAAACAgAADUAQAAAAAA
		AAQAAAADAwAAAPAAAAQAAAADAwAAAAAAAAQAAAADAwAAAQAAABAA
		AAABBgAAaAIAAHQCAACAAgAAdAIAALQAAAD+////AQAAAAACAAAO
		AAAABBAAAEQAAAAAAAAABRAAAHAAAAAAAAAAEBAAAJQAAAAAAAAA
		QBAAAIQAAAAAAAAAACAAAIwCAAAAAAAAAiAAAEwBAAAAAAAABSAA
		ALwAAAAAAAAAECAAACAAAAAAAAAAESAAAAABAAAAAAAAEiAAAOAA
		AAAAAAAAEyAAAPAAAAAAAAAAICAAACwBAAAAAAAAAdAAALQAAAAA
		AAAAENAAAAQAAAAAAAAA
		</data>
		<key>name</key>
		<string>Maxime</string>
	</dict>
	<dict>
		<key>file-bookmark</key>
		<data>
		Ym9va5QDAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAAqAIAAAQAAAADAwAAAAIAIAcAAAABAQAAVm9sdW1l
		cwAKAAAAAQEAAFNhbXN1bmctVDcAAAsAAAABAQAAUHJlZmVyZW5j
		ZXMADAAAAAEGAAAQAAAAIAAAADQAAAAIAAAABAMAAAhuAAAAAAAA
		AAAAAAEKAAAMAAAAAQYAAFwAAABsAAAAbAAAAAgAAAAABAAAQcNv
		aTIAAAAYAAAAAQIAAAIAAAAAAAAADwAAAAAAAAAAAAAAAAAAAAAA
		AAABBQAAGwAAAAEJAABmaWxlOi8vL1ZvbHVtZXMvU2Ftc3VuZy1U
		Ny8ACAAAAAQDAAAAAFDS6AAAAAgAAAAABAAAwc0n5EAAAAAkAAAA
		AQEAADFGODdCMUY2LUVDMjktMzBERC1BRUFCLTQwRUY1NzQ3MTZB
		ORgAAAABAgAAAQEAAAAAAADvEwAAAQAAAAAAAAAAAAAAEwAAAAEB
		AAAvVm9sdW1lcy9TYW1zdW5nLVQ3AAgAAAABCQAAZmlsZTovLy8I
		AAAAAQEAAFVudGl0bGVkCAAAAAQDAAAAAIcROQAAAAgAAAAABAAA
		QcNsYgiAAAAkAAAAAQEAAEI0OTBBMDA0LTMzMUYtNDkyNC05Q0M5
		LUIwRUU3RTI1MTQ0MhgAAAABAgAAgQAAAAEAAADvEwAAAQAAAAAA
		AAAAAAAAAQAAAAEBAAAvAAAAYAAAAP7///8A8AAAAAAAAAcAAAAC
		IAAA+AEAAAAAAAAFIAAAbAEAAAAAAAAQIAAAfAEAAAAAAAARIAAA
		rAEAAAAAAAASIAAAjAEAAAAAAAATIAAAnAEAAAAAAAAgIAAA2AEA
		AAAAAAAEAAAAAwMAAADwAAAEAAAAAwMAAAAAAAAEAAAAAwMAAAEA
		AAAQAAAAAQYAAGwCAAB4AgAAhAIAAHgCAAC0AAAA/v///wEAAAAE
		AgAADgAAAAQQAABIAAAAAAAAAAUQAAB0AAAAAAAAABAQAACYAAAA
		AAAAAEAQAACIAAAAAAAAAAAgAACQAgAAAAAAAAIgAABQAQAAAAAA
		AAUgAADAAAAAAAAAABAgAAAgAAAAAAAAABEgAAAEAQAAAAAAABIg
		AADkAAAAAAAAABMgAAD0AAAAAAAAACAgAAAwAQAAAAAAAAHQAAC4
		AAAAAAAAABDQAAAEAAAAAAAAAA==
		</data>
		<key>name</key>
		<string>Preferences</string>
	</dict>
	<dict>
		<key>file-bookmark</key>
		<data>
		Ym9va5gDAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAArAIAAAQAAAADAwAAAAIAIAcAAAABAQAAVm9sdW1l
		cwAKAAAAAQEAAFNhbXN1bmctVDcAAA0AAAABAQAAUHJlZmVyZW5j
		ZXNfMAAAAAwAAAABBgAAEAAAACAAAAA0AAAACAAAAAQDAAAIbgAA
		AAAAAAAAAAABCgAADAAAAAEGAABgAAAAcAAAAHAAAAAIAAAAAAQA
		AEHDhI9ygAAAGAAAAAECAAACAAAAAAAAAA8AAAAAAAAAAAAAAAAA
		AAAAAAAAAQUAABsAAAABCQAAZmlsZTovLy9Wb2x1bWVzL1NhbXN1
		bmctVDcvAAgAAAAEAwAAAABQ0ugAAAAIAAAAAAQAAMHNJ+RAAAAA
		JAAAAAEBAAAxRjg3QjFGNi1FQzI5LTMwREQtQUVBQi00MEVGNTc0
		NzE2QTkYAAAAAQIAAAEBAAAAAAAA7xMAAAEAAAAAAAAAAAAAABMA
		AAABAQAAL1ZvbHVtZXMvU2Ftc3VuZy1UNwAIAAAAAQkAAGZpbGU6
		Ly8vCAAAAAEBAABVbnRpdGxlZAgAAAAEAwAAAACHETkAAAAIAAAA
		AAQAAEHDbGIIgAAAJAAAAAEBAABCNDkwQTAwNC0zMzFGLTQ5MjQt
		OUNDOS1CMEVFN0UyNTE0NDIYAAAAAQIAAIEAAAABAAAA7xMAAAEA
		AAAAAAAAAAAAAAEAAAABAQAALwAAAGAAAAD+////APAAAAAAAAAH
		AAAAAiAAAPwBAAAAAAAABSAAAHABAAAAAAAAECAAAIABAAAAAAAA
		ESAAALABAAAAAAAAEiAAAJABAAAAAAAAEyAAAKABAAAAAAAAICAA
		ANwBAAAAAAAABAAAAAMDAAAA8AAABAAAAAMDAAAAAAAABAAAAAMD
		AAABAAAAEAAAAAEGAABwAgAAfAIAAIgCAAB8AgAAtAAAAP7///8B
		AAAACAIAAA4AAAAEEAAATAAAAAAAAAAFEAAAeAAAAAAAAAAQEAAA
		nAAAAAAAAABAEAAAjAAAAAAAAAAAIAAAlAIAAAAAAAACIAAAVAEA
		AAAAAAAFIAAAxAAAAAAAAAAQIAAAIAAAAAAAAAARIAAACAEAAAAA
		AAASIAAA6AAAAAAAAAATIAAA+AAAAAAAAAAgIAAANAEAAAAAAAAB
		0AAAvAAAAAAAAAAQ0AAABAAAAAAAAAA=
		</data>
		<key>name</key>
		<string>Preferences_0</string>
	</dict>
	<dict>
		<key>file-bookmark</key>
		<data>
		Ym9va2QDAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAAeAIAAAQAAAADAwAAAAIAIAcAAAABAQAAVm9sdW1l
		cwAKAAAAAQEAAFNhbXN1bmctVDcAAAgAAAABBgAAEAAAACAAAAAI
		AAAABAMAAAhuAAAAAAAAAAAAAAEKAAAIAAAAAQYAAEQAAABUAAAA
		CAAAAAAEAADBzSfkQAAAABgAAAABAgAACgAAAAAAAAAPAAAAAAAA
		AAAAAAAAAAAAAAAAAAEFAAAbAAAAAQkAAGZpbGU6Ly8vVm9sdW1l
		cy9TYW1zdW5nLVQ3LwAIAAAABAMAAAAAUNLoAAAAJAAAAAEBAAAx
		Rjg3QjFGNi1FQzI5LTMwREQtQUVBQi00MEVGNTc0NzE2QTkYAAAA
		AQIAAAEBAAAAAAAA7xMAAAEAAAAAAAAAAAAAABMAAAABAQAAL1Zv
		bHVtZXMvU2Ftc3VuZy1UNwAIAAAAAQkAAGZpbGU6Ly8vCAAAAAEB
		AABVbnRpdGxlZAgAAAAEAwAAAACHETkAAAAIAAAAAAQAAEHDbGII
		gAAAJAAAAAEBAABCNDkwQTAwNC0zMzFGLTQ5MjQtOUNDOS1CMEVF
		N0UyNTE0NDIYAAAAAQIAAIEAAAABAAAA7xMAAAEAAAAAAAAAAAAA
		AAEAAAABAQAALwAAAGAAAAD+////APAAAAAAAAAHAAAAAiAAAMwB
		AAAAAAAABSAAAEABAAAAAAAAECAAAFABAAAAAAAAESAAAIABAAAA
		AAAAEiAAAGABAAAAAAAAEyAAAHABAAAAAAAAICAAAKwBAAAAAAAA
		BAAAAAMDAAAA8AAABAAAAAMDAAAAAAAABAAAAAMDAAABAAAADAAA
		AAEGAABAAgAATAIAAFgCAAC0AAAA/v///wEAAADYAQAADgAAAAQQ
		AAA0AAAAAAAAAAUQAABcAAAAAAAAABAQAAB8AAAAAAAAAEAQAABs
		AAAAAAAAAAAgAABkAgAAAAAAAAIgAAAkAQAAAAAAAAUgAACkAAAA
		AAAAABAgAAAgAAAAAAAAABEgAADYAAAAAAAAABIgAADIAAAAAAAA
		ABMgAABsAAAAAAAAACAgAAAEAQAAAAAAAAHQAACcAAAAAAAAABDQ
		AAAEAAAAAAAAAA==
		</data>
		<key>name</key>
		<string>Samsung-T7</string>
	</dict>
	<dict>
		<key>file-bookmark</key>
		<data>
		Ym9va+gCAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAA2AEAAAQAAAADAwAAAAIAIAUAAAABAQAAVXNlcnMA
		AAAGAAAAAQEAAG1heGltZQAABwAAAAEBAABMaWJyYXJ5AAsAAAAB
		AQAAUHJlZmVyZW5jZXMABgAAAAEBAABCeUhvc3QAABQAAAABBgAA
		EAAAACAAAAAwAAAAQAAAAFQAAAAIAAAABAMAAHBkAAAAAAAACAAA
		AAQDAAAhiwAAAAAAAAgAAAAEAwAAKIsAAAAAAAAIAAAABAMAACuL
		AAAAAAAACAAAAAQDAAAjjgAAAAAAABQAAAABBgAAgAAAAJAAAACg
		AAAAsAAAAMAAAAAIAAAAAAQAAEHDhITX+oqqGAAAAAECAAACAAAA
		AAAAAA8AAAAAAAAAAAAAAAAAAAAAAAAAAQUAAAgAAAAEAwAAAwAA
		AAAAAAAEAAAAAwMAAPUBAAAIAAAAAQkAAGZpbGU6Ly8vCAAAAAEB
		AABVbnRpdGxlZAgAAAAEAwAAAACHETkAAAAIAAAAAAQAAEHDbGII
		gAAAJAAAAAEBAABCNDkwQTAwNC0zMzFGLTQ5MjQtOUNDOS1CMEVF
		N0UyNTE0NDIYAAAAAQIAAIEAAAABAAAA7xMAAAEAAAAAAAAAAAAA
		AAEAAAABAQAALwAAANgAAAD+////AQAAAAAAAAARAAAABBAAAGQA
		AAAAAAAABRAAANAAAAAAAAAAEBAAAPwAAAAAAAAAQBAAAOwAAAAA
		AAAAAiAAAMwBAAAAAAAABSAAAEABAAAAAAAAECAAAFABAAAAAAAA
		ESAAAIABAAAAAAAAEiAAAGABAAAAAAAAEyAAAHABAAAAAAAAICAA
		AKwBAAAAAAAAMCAAABwBAAAAAAAAAcAAACQBAAAAAAAAEcAAACAA
		AAAAAAAAEsAAADQBAAAAAAAAAdAAABwBAAAAAAAAENAAAAQAAAAA
		AAAA
		</data>
		<key>name</key>
		<string>ByHost</string>
	</dict>
	<dict>
		<key>file-bookmark</key>
		<data>
		Ym9va7ACAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAAoAEAAAQAAAADAwAAAAIAIAUAAAABAQAAVXNlcnMA
		AAAGAAAAAQEAAG1heGltZQAABwAAAAEBAABMaWJyYXJ5AAsAAAAB
		AQAAUHJlZmVyZW5jZXMAEAAAAAEGAAAQAAAAIAAAADAAAABAAAAA
		CAAAAAQDAABwZAAAAAAAAAgAAAAEAwAAIYsAAAAAAAAIAAAABAMA
		ACiLAAAAAAAACAAAAAQDAAAriwAAAAAAABAAAAABBgAAbAAAAHwA
		AACMAAAAnAAAAAgAAAAABAAAQcNsYgiAAAAYAAAAAQIAAAIAAAAA
		AAAADwAAAAAAAAAAAAAAAAAAAAAAAAABBQAACAAAAAQDAAACAAAA
		AAAAAAQAAAADAwAA9QEAAAgAAAABCQAAZmlsZTovLy8IAAAAAQEA
		AFVudGl0bGVkCAAAAAQDAAAAAIcROQAAACQAAAABAQAAQjQ5MEEw
		MDQtMzMxRi00OTI0LTlDQzktQjBFRTdFMjUxNDQyGAAAAAECAACB
		AAAAAQAAAO8TAAABAAAAAAAAAAAAAAABAAAAAQEAAC8AAADYAAAA
		/v///wEAAAAAAAAAEQAAAAQQAABUAAAAAAAAAAUQAACsAAAAAAAA
		ABAQAADUAAAAAAAAAEAQAADEAAAAAAAAAAIgAACUAQAAAAAAAAUg
		AAAYAQAAAAAAABAgAAAoAQAAAAAAABEgAABIAQAAAAAAABIgAAA4
		AQAAAAAAABMgAADEAAAAAAAAACAgAAB0AQAAAAAAADAgAAD0AAAA
		AAAAAAHAAAD8AAAAAAAAABHAAAAgAAAAAAAAABLAAAAMAQAAAAAA
		AAHQAAD0AAAAAAAAABDQAAAEAAAAAAAAAA==
		</data>
		<key>name</key>
		<string>Preferences</string>
	</dict>
	<dict>
		<key>file-bookmark</key>
		<data>
		Ym9va4QCAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
		AAAAAAAAAAAAdAEAAAQAAAADAwAAAAIAIAUAAAABAQAAVXNlcnMA
		AAAGAAAAAQEAAG1heGltZQAABwAAAAEBAABMaWJyYXJ5AAwAAAAB
		BgAAEAAAACAAAAAwAAAACAAAAAQDAABwZAAAAAAAAAgAAAAEAwAA
		IYsAAAAAAAAIAAAABAMAACiLAAAAAAAADAAAAAEGAABUAAAAZAAA
		AHQAAAAIAAAAAAQAAEHDbGIIgAAAGAAAAAECAAACAAAAAAAAAA8A
		AAAAAAAAAAAAAAAAAAAAAAAAAQUAAAgAAAAEAwAAAQAAAAAAAAAE
		AAAAAwMAAPUBAAAIAAAAAQkAAGZpbGU6Ly8vCAAAAAEBAABVbnRp
		dGxlZAgAAAAEAwAAAACHETkAAAAkAAAAAQEAAEI0OTBBMDA0LTMz
		MUYtNDkyNC05Q0M5LUIwRUU3RTI1MTQ0MhgAAAABAgAAgQAAAAEA
		AADvEwAAAQAAAAAAAAAAAAAAAQAAAAEBAAAvAAAA2AAAAP7///8B
		AAAAAAAAABEAAAAEEAAAQAAAAAAAAAAFEAAAhAAAAAAAAAAQEAAA
		qAAAAAAAAABAEAAAmAAAAAAAAAACIAAAaAEAAAAAAAAFIAAA7AAA
		AAAAAAAQIAAA/AAAAAAAAAARIAAAHAEAAAAAAAASIAAADAEAAAAA
		AAATIAAAmAAAAAAAAAAgIAAASAEAAAAAAAAwIAAAyAAAAAAAAAAB
		wAAA0AAAAAAAAAARwAAAIAAAAAAAAAASwAAA4AAAAAAAAAAB0AAA
		yAAAAAAAAAAQ0AAABAAAAAAAAAA=
		</data>
		<key>name</key>
		<string>Library</string>
	</dict>
</array>
'
defaults write com.apple.finder "FXSidebarUpgradedSharedSearchToTwelve" -boolean true
defaults write com.apple.finder "FXSidebarUpgradedToTenFourteen" -boolean true
defaults write com.apple.finder "FXSidebarUpgradedToTenTen" -boolean true
defaults write com.apple.finder "FXToolbarUpgradedToTenEight" -integer 1
defaults write com.apple.finder "FXToolbarUpgradedToTenNine" -integer 2
defaults write com.apple.finder "FXToolbarUpgradedToTenSeven" -integer 1
defaults write com.apple.finder "FavoriteTagNames" '
<array>
	<string></string>
	<string>Red</string>
	<string>Orange</string>
	<string>Yellow</string>
	<string>Green</string>
	<string>Blue</string>
	<string>Purple</string>
	<string>Grey</string>
</array>
'
defaults write com.apple.finder "LastTrashState" -boolean true
defaults write com.apple.finder "MeetingRoomViewSetting" '
<dict>
	<key>CustomViewStyleVersion</key>
	<integer>1</integer>
	<key>WindowState</key>
	<dict>
		<key>ContainerShowSidebar</key>
		<true/>
		<key>ShowSidebar</key>
		<true/>
		<key>ShowStatusBar</key>
		<false/>
		<key>ShowTabView</key>
		<false/>
		<key>ShowToolbar</key>
		<true/>
		<key>WindowBounds</key>
		<string>{{2805, 591}, {920, 436}}</string>
	</dict>
</dict>
'
defaults write com.apple.finder "NSNavLastRootDirectory" -string '~/Documents'
defaults write com.apple.finder "NSNavPanelExpandedSizeForOpenMode" -string '{800, 448}'
defaults write com.apple.finder "NSToolbar Configuration Browser" '
<dict>
	<key>TB Display Mode</key>
	<integer>2</integer>
	<key>TB Icon Size Mode</key>
	<integer>1</integer>
	<key>TB Is Shown</key>
	<integer>1</integer>
	<key>TB Size Mode</key>
	<integer>1</integer>
</dict>
'
defaults write com.apple.finder "NSWindow Frame NSNavPanelAutosaveName" -string '0 85 328 135 0 0 2560 1415 '
defaults write com.apple.finder "RecentMoveAndCopyDestinations" '
<array>
	<string>file:///Volumes/Samsung-T7/Preferences_0/</string>
</array>
'
defaults write com.apple.finder "RecentsArrangeGroupViewBy" -string 'Date Last Opened'
defaults write com.apple.finder "SearchRecentsSavedViewStyleVersion" -string '%00%00%00%01'
defaults write com.apple.finder "SearchRecentsViewSettings" '
<dict>
	<key>WindowState</key>
	<dict>
		<key>ContainerShowSidebar</key>
		<true/>
		<key>ShowSidebar</key>
		<true/>
		<key>ShowStatusBar</key>
		<false/>
		<key>ShowTabView</key>
		<false/>
		<key>ShowToolbar</key>
		<true/>
		<key>WindowBounds</key>
		<string>{{2805, 591}, {920, 436}}</string>
	</dict>
</dict>
'
defaults write com.apple.finder "SearchViewSettings" '
<dict>
	<key>WindowState</key>
	<dict>
		<key>ContainerShowSidebar</key>
		<true/>
		<key>ShowSidebar</key>
		<true/>
		<key>ShowStatusBar</key>
		<false/>
		<key>ShowTabView</key>
		<false/>
		<key>ShowToolbar</key>
		<true/>
		<key>WindowBounds</key>
		<string>{{2803, 282}, {1670, 912}}</string>
	</dict>
</dict>
'
defaults write com.apple.finder "ShowExternalHardDrivesOnDesktop" -boolean true
defaults write com.apple.finder "ShowHardDrivesOnDesktop" -boolean false
defaults write com.apple.finder "ShowRemovableMediaOnDesktop" -boolean true
defaults write com.apple.finder "ShowSidebar" -boolean true
defaults write com.apple.finder "SidebarDevicesSectionDisclosedState" -boolean true
defaults write com.apple.finder "SidebarPlacesSectionDisclosedState" -boolean true
defaults write com.apple.finder "SidebarShowingSignedIntoiCloud" -boolean true
defaults write com.apple.finder "SidebarShowingiCloudDesktop" -boolean false
defaults write com.apple.finder "SidebarWidth" -float 247
defaults write com.apple.finder "StandardViewSettings" '
<dict>
	<key>ExtendedListViewSettingsV2</key>
	<dict>
		<key>calculateAllSizes</key>
		<false/>
		<key>columns</key>
		<array>
			<dict>
				<key>ascending</key>
				<true/>
				<key>identifier</key>
				<string>name</string>
				<key>visible</key>
				<true/>
				<key>width</key>
				<integer>300</integer>
			</dict>
			<dict>
				<key>ascending</key>
				<false/>
				<key>identifier</key>
				<string>dateModified</string>
				<key>visible</key>
				<true/>
				<key>width</key>
				<integer>181</integer>
			</dict>
			<dict>
				<key>ascending</key>
				<false/>
				<key>identifier</key>
				<string>dateCreated</string>
				<key>visible</key>
				<false/>
				<key>width</key>
				<integer>181</integer>
			</dict>
			<dict>
				<key>ascending</key>
				<false/>
				<key>identifier</key>
				<string>size</string>
				<key>visible</key>
				<true/>
				<key>width</key>
				<integer>97</integer>
			</dict>
			<dict>
				<key>ascending</key>
				<true/>
				<key>identifier</key>
				<string>kind</string>
				<key>visible</key>
				<true/>
				<key>width</key>
				<integer>115</integer>
			</dict>
			<dict>
				<key>ascending</key>
				<true/>
				<key>identifier</key>
				<string>label</string>
				<key>visible</key>
				<false/>
				<key>width</key>
				<integer>100</integer>
			</dict>
			<dict>
				<key>ascending</key>
				<true/>
				<key>identifier</key>
				<string>version</string>
				<key>visible</key>
				<false/>
				<key>width</key>
				<integer>75</integer>
			</dict>
			<dict>
				<key>ascending</key>
				<true/>
				<key>identifier</key>
				<string>comments</string>
				<key>visible</key>
				<false/>
				<key>width</key>
				<integer>300</integer>
			</dict>
			<dict>
				<key>ascending</key>
				<false/>
				<key>identifier</key>
				<string>dateLastOpened</string>
				<key>visible</key>
				<false/>
				<key>width</key>
				<integer>200</integer>
			</dict>
			<dict>
				<key>ascending</key>
				<false/>
				<key>identifier</key>
				<string>shareOwner</string>
				<key>visible</key>
				<false/>
				<key>width</key>
				<integer>200</integer>
			</dict>
			<dict>
				<key>ascending</key>
				<false/>
				<key>identifier</key>
				<string>shareLastEditor</string>
				<key>visible</key>
				<false/>
				<key>width</key>
				<integer>200</integer>
			</dict>
		</array>
		<key>iconSize</key>
		<integer>16</integer>
		<key>showIconPreview</key>
		<true/>
		<key>sortColumn</key>
		<string>name</string>
		<key>textSize</key>
		<integer>13</integer>
		<key>useRelativeDates</key>
		<true/>
		<key>viewOptionsVersion</key>
		<integer>1</integer>
	</dict>
	<key>GalleryViewSettings</key>
	<dict>
		<key>arrangeBy</key>
		<string>name</string>
		<key>iconSize</key>
		<real>48</real>
		<key>showIconPreview</key>
		<true/>
		<key>viewOptionsVersion</key>
		<integer>1</integer>
	</dict>
	<key>IconViewSettings</key>
	<dict>
		<key>arrangeBy</key>
		<string>none</string>
		<key>backgroundColorBlue</key>
		<real>1</real>
		<key>backgroundColorGreen</key>
		<real>1</real>
		<key>backgroundColorRed</key>
		<real>1</real>
		<key>backgroundType</key>
		<integer>0</integer>
		<key>gridOffsetX</key>
		<real>0.0</real>
		<key>gridOffsetY</key>
		<real>0.0</real>
		<key>gridSpacing</key>
		<real>54</real>
		<key>iconSize</key>
		<real>64</real>
		<key>labelOnBottom</key>
		<true/>
		<key>showIconPreview</key>
		<true/>
		<key>showItemInfo</key>
		<false/>
		<key>textSize</key>
		<real>12</real>
		<key>viewOptionsVersion</key>
		<integer>1</integer>
	</dict>
	<key>ListViewSettings</key>
	<dict>
		<key>calculateAllSizes</key>
		<false/>
		<key>columns</key>
		<dict>
			<key>comments</key>
			<dict>
				<key>ascending</key>
				<true/>
				<key>index</key>
				<integer>7</integer>
				<key>visible</key>
				<false/>
				<key>width</key>
				<integer>300</integer>
			</dict>
			<key>dateCreated</key>
			<dict>
				<key>ascending</key>
				<false/>
				<key>index</key>
				<integer>2</integer>
				<key>visible</key>
				<false/>
				<key>width</key>
				<integer>181</integer>
			</dict>
			<key>dateLastOpened</key>
			<dict>
				<key>ascending</key>
				<false/>
				<key>index</key>
				<integer>8</integer>
				<key>visible</key>
				<false/>
				<key>width</key>
				<integer>200</integer>
			</dict>
			<key>dateModified</key>
			<dict>
				<key>ascending</key>
				<false/>
				<key>index</key>
				<integer>1</integer>
				<key>visible</key>
				<true/>
				<key>width</key>
				<integer>181</integer>
			</dict>
			<key>kind</key>
			<dict>
				<key>ascending</key>
				<true/>
				<key>index</key>
				<integer>4</integer>
				<key>visible</key>
				<true/>
				<key>width</key>
				<integer>115</integer>
			</dict>
			<key>label</key>
			<dict>
				<key>ascending</key>
				<true/>
				<key>index</key>
				<integer>5</integer>
				<key>visible</key>
				<false/>
				<key>width</key>
				<integer>100</integer>
			</dict>
			<key>name</key>
			<dict>
				<key>ascending</key>
				<true/>
				<key>index</key>
				<integer>0</integer>
				<key>visible</key>
				<true/>
				<key>width</key>
				<integer>300</integer>
			</dict>
			<key>size</key>
			<dict>
				<key>ascending</key>
				<false/>
				<key>index</key>
				<integer>3</integer>
				<key>visible</key>
				<true/>
				<key>width</key>
				<integer>97</integer>
			</dict>
			<key>version</key>
			<dict>
				<key>ascending</key>
				<true/>
				<key>index</key>
				<integer>6</integer>
				<key>visible</key>
				<false/>
				<key>width</key>
				<integer>75</integer>
			</dict>
		</dict>
		<key>iconSize</key>
		<integer>16</integer>
		<key>showIconPreview</key>
		<true/>
		<key>sortColumn</key>
		<string>name</string>
		<key>textSize</key>
		<integer>13</integer>
		<key>useRelativeDates</key>
		<true/>
		<key>viewOptionsVersion</key>
		<integer>1</integer>
	</dict>
	<key>SettingsType</key>
	<string>StandardViewSettings</string>
</dict>
'
defaults write com.apple.finder "TagsCloudSerialNumber" -integer 26
