#!/usr/bin/env bash

defaults write com.apple.suggestions "AppCanShowSiriSuggestionsBlacklist" '<array/>'
defaults write com.apple.suggestions "CloudKitPersistedState" '
<data>
YnBsaXN0MDDUAQIDBAUGBwpYJHZlcnNpb25ZJGFyY2hpdmVyVCR0b3BYJG9iamVjdHMS
AAGGoF8QD05TS2V5ZWRBcmNoaXZlctEICVRyb290gAGuCwwhIigpMTIzOTw9Pj9VJG51
bGzaDQ4PEBESExQVFhcXGRobHB0XHxtfEA9oYXNEZWZlcnJlZFN5bmNfEB5oYXNEZWZl
cnJlZFByb2Nlc3NTdGF0ZUNoYW5nZXNWJGNsYXNzXxAVc2FsdEF0b21pY1JlZmVyZW5j
ZUlkXxAPaGFzU3Vic2NyaXB0aW9uXxAdZXZlbnRzV2VyZVJlbW92ZWRGcm9tRXZlbnRL
aXRfEBxwcmltYXJ5SUNsb3VkQ2FsZW5kYXJBY2NvdW50WXN5bmNUb2tlblRzYWx0XxAP
c2FsdFVzZXNNYW5hdGVlgACAAIANgAOACoALgAyAAIACgApPECANy2iMMo2WXF8oOKIG
k0v4kHUGHKD5Pl0m2T8R8Rv1p9MPIyQlJidaUmVjb3JkTmFtZVZab25lSUSACYAEgAVf
EB1zYWx0X01OOCt2alZJOFBkRmJZVWl5eVBsRVE9PdQqKywPFy4vMF8QEWFub255bW91
c0NLVXNlcklEWW93bmVyTmFtZVhab25lTmFtZYAAgAeABoAIVmV2ZW50c18QEF9fZGVm
YXVsdE93bmVyX1/SNDU2N1okY2xhc3NuYW1lWCRjbGFzc2VzXkNLUmVjb3JkWm9uZUlE
ojY4WE5TT2JqZWN00jQ1OjtaQ0tSZWNvcmRJRKI6OAkIXxAkMDg5ODYwNDAtNTM5RC00
MjA2LUI4NTMtODUyQkYzNTRGODY20jQ1QEFfEB5fU0dEQ2xvdWRLaXRTeW5jUGVyc2lz
dGVkU3RhdGWiQjhfEB5fU0dEQ2xvdWRLaXRTeW5jUGVyc2lzdGVkU3RhdGUACAARABoA
JAApADIANwBJAEwAUQBTAGIAaAB9AI8AsAC3AM8A4QEBASABKgEvAUEBQwFFAUcBSQFL
AU0BTwFRAVMBVQF4AX8BigGRAZMBlQGXAbcBwAHUAd4B5wHpAesB7QHvAfYCCQIOAhkC
IgIxAjQCPQJCAk0CUAJRAlICeQJ+Ap8CogAAAAAAAAIBAAAAAAAAAEMAAAAAAAAAAAAA
AAAAAALD
</data>
'
defaults write com.apple.suggestions "SuggestionsAllowGeocode" -boolean false
defaults write com.apple.suggestions "UserAccountsPersistedState" '
<array>
	<string>08986040-539D-4206-B853-852BF354F866</string>
	<string>maximebories@icloud.com</string>
</array>
'
defaults write com.apple.suggestions "findToShowMigrationPerformed" -boolean true
defaults write com.apple.suggestions "spToLearnMigrationPerformed" -boolean true
