#!/usr/bin/env bash

defaults write com.apple.amp.mediasharingd "home-sharing-computer-id" -string ''
defaults write com.apple.amp.mediasharingd "home-sharing-enabled" -integer 0
defaults write com.apple.amp.mediasharingd "home-sharing-group-id" -string ''
defaults write com.apple.amp.mediasharingd "home-sharing-sequence-id" -integer 100
defaults write com.apple.amp.mediasharingd "home-sharing-settings" '
<dict>
	<key>home-sharing-update-play-counts</key>
	<false/>
	<key>home-sharing-user-id</key>
	<integer>0</integer>
	<key>home-sharing-user-name</key>
	<string></string>
</dict>
'
defaults write com.apple.amp.mediasharingd "photo-sharing-enabled" -integer 0
defaults write com.apple.amp.mediasharingd "photo-sharing-settings" '
<dict>
	<key>apertureAlbums</key>
	<array/>
	<key>apertureCopyOriginalPhotos</key>
	<false/>
	<key>apertureCustomAlbumOrder</key>
	<integer>0</integer>
	<key>apertureSyncAllAlbums</key>
	<false/>
	<key>apertureSyncAllFaces</key>
	<false/>
	<key>apertureSyncMode</key>
	<integer>0</integer>
	<key>apertureSyncPhotoVideos</key>
	<false/>
	<key>iPhotoAlbums</key>
	<array/>
	<key>iPhotoCopyOriginalPhotos</key>
	<false/>
	<key>iPhotoCustomAlbumOrder</key>
	<integer>0</integer>
	<key>iPhotoPrefsMajorVersion</key>
	<integer>0</integer>
	<key>iPhotoPrefsMinorVersion</key>
	<integer>0</integer>
	<key>iPhotoSyncAllAlbums</key>
	<false/>
	<key>iPhotoSyncAllFaces</key>
	<false/>
	<key>iPhotoSyncMode</key>
	<integer>0</integer>
	<key>iPhotoSyncPhotoVideos</key>
	<false/>
	<key>iPhotoUpgradedDistinguishedAlbums</key>
	<false/>
	<key>photo-sharing-source-id</key>
	<integer>0</integer>
	<key>photosAppAlbums</key>
	<array/>
	<key>photosAppAutoIncludeEnabled</key>
	<false/>
	<key>photosAppCopyOriginalPhotos</key>
	<false/>
	<key>photosAppCustomAlbumOrder</key>
	<integer>0</integer>
	<key>photosAppEventCount</key>
	<integer>255</integer>
	<key>photosAppOnlyFavorites</key>
	<false/>
	<key>photosAppSyncAllAlbums</key>
	<false/>
	<key>photosAppSyncAllFaces</key>
	<false/>
	<key>photosAppSyncMode</key>
	<integer>0</integer>
	<key>photosAppSyncPhotoVideos</key>
	<false/>
	<key>photosFolderAlbums</key>
	<array/>
	<key>photosFolderCopyOriginalPhotos</key>
	<false/>
	<key>photosFolderCustomAlbumOrder</key>
	<integer>0</integer>
	<key>photosFolderInfo</key>
	<dict>
		<key>syncFolderIsFromMac</key>
		<false/>
		<key>syncFolderIsValid</key>
		<false/>
	</dict>
	<key>photosFolderSyncMode</key>
	<integer>0</integer>
	<key>photosFolderSyncPhotoVideos</key>
	<false/>
	<key>psAlbumAlbums</key>
	<array/>
	<key>psAlbumCopyOriginalPhotos</key>
	<false/>
	<key>psAlbumCustomAlbumOrder</key>
	<integer>0</integer>
	<key>psAlbumSyncMode</key>
	<integer>0</integer>
	<key>psAlbumSyncPhotoVideos</key>
	<false/>
	<key>psElementsAlbums</key>
	<array/>
	<key>psElementsCopyOriginalPhotos</key>
	<false/>
	<key>psElementsCustomAlbumOrder</key>
	<integer>0</integer>
	<key>psElementsSyncMode</key>
	<integer>0</integer>
	<key>psElementsSyncPhotoVideos</key>
	<false/>
</dict>
'
defaults write com.apple.amp.mediasharingd "public-sharing-enabled" -integer 0
defaults write com.apple.amp.mediasharingd "public-sharing-is-protected" -integer 0
defaults write com.apple.amp.mediasharingd "public-sharing-settings" '
<dict>
	<key>public-sharing-playlists</key>
	<array>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>65216489464619224</integer>
			<key>public-sharing-playlist-name</key>
			<string>La playlist officielle - Le Printemps de Bourges Crédit Mutuel 2021</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>103639518028035931</integer>
			<key>public-sharing-playlist-name</key>
			<string>Lulu</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>287142123258198689</integer>
			<key>public-sharing-playlist-name</key>
			<string>Lyrics</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>348581513505560257</integer>
			<key>public-sharing-playlist-name</key>
			<string>Ambient Relaxation</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>348788361454618312</integer>
			<key>public-sharing-playlist-name</key>
			<string>Spotify’s Top 20 Most-Streamed Tracks for Sleep, Globally</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>366302004202526152</integer>
			<key>public-sharing-playlist-name</key>
			<string>Dope Beats</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>525223029382560189</integer>
			<key>public-sharing-playlist-name</key>
			<string>Discover Weekly Archive</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>549968732179636657</integer>
			<key>public-sharing-playlist-name</key>
			<string>Vieux Rap</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>637559032479171686</integer>
			<key>public-sharing-playlist-name</key>
			<string>Archive Controlling Crowds (Parts I-III)</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>673698855008512191</integer>
			<key>public-sharing-playlist-name</key>
			<string>2012</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>735585620979043634</integer>
			<key>public-sharing-playlist-name</key>
			<string>Offline</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>839936923745895738</integer>
			<key>public-sharing-playlist-name</key>
			<string>Heartbreak</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>906894229013801485</integer>
			<key>public-sharing-playlist-name</key>
			<string>Ramin Djawadi Westworld: Season 1 (Selections from the HBO® Series)</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>1002765802271177331</integer>
			<key>public-sharing-playlist-name</key>
			<string>00s</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>1034295895482674127</integer>
			<key>public-sharing-playlist-name</key>
			<string>Nelly Furtado Loose</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>1059802118252706453</integer>
			<key>public-sharing-playlist-name</key>
			<string>James Horner Titanic: Music from the Motion Picture Soundtrack</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>1070108761634101671</integer>
			<key>public-sharing-playlist-name</key>
			<string>Music</string>
			<key>public-sharing-playlist-shared</key>
			<true/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>1250226839682904926</integer>
			<key>public-sharing-playlist-name</key>
			<string>Feelin'"'"' Good</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>1316380086315702366</integer>
			<key>public-sharing-playlist-name</key>
			<string>Orchestre d'"'"'harmonie</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>1445874194018446271</integer>
			<key>public-sharing-playlist-name</key>
			<string>Douceur Pop</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>1520681360674491573</integer>
			<key>public-sharing-playlist-name</key>
			<string>EA Games Soundtrack The Sims 2</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>1591071750100906781</integer>
			<key>public-sharing-playlist-name</key>
			<string>I Want You Back The Jackson 5</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>1604251026769116179</integer>
			<key>public-sharing-playlist-name</key>
			<string>05s</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>2</integer>
			<key>public-sharing-playlist-id</key>
			<integer>1613306626461419335</integer>
			<key>public-sharing-playlist-name</key>
			<string>TV Shows</string>
			<key>public-sharing-playlist-shared</key>
			<true/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>1690790015045840277</integer>
			<key>public-sharing-playlist-name</key>
			<string>Anthony</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>1741407389639972536</integer>
			<key>public-sharing-playlist-name</key>
			<string>Dormir  Calme et relaxation, Dormir profondément, Insomnie, Playlist pour s'"'"'endormir</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>1837855108725602958</integer>
			<key>public-sharing-playlist-name</key>
			<string>La Détente Générale #118</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>1941632018392278571</integer>
			<key>public-sharing-playlist-name</key>
			<string>Ennio Morricone Note di pace Venezia 10 settembre 2007</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>2120686572261420576</integer>
			<key>public-sharing-playlist-name</key>
			<string>Mes favoris Fip</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>2495533385581691377</integer>
			<key>public-sharing-playlist-name</key>
			<string>Some Minds</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>2641621334484988350</integer>
			<key>public-sharing-playlist-name</key>
			<string>Various Artists Moonrise Kingdom (Original Score)</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>2651054331153801193</integer>
			<key>public-sharing-playlist-name</key>
			<string>LLarge Spectrum Testing</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>2723217924747058979</integer>
			<key>public-sharing-playlist-name</key>
			<string>1993</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>2820136779295344858</integer>
			<key>public-sharing-playlist-name</key>
			<string>Thomas Laduguie Cellosphères</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>2821587198514204271</integer>
			<key>public-sharing-playlist-name</key>
			<string>Jazz</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>2907322761457877648</integer>
			<key>public-sharing-playlist-name</key>
			<string>Tryo Mamagubida</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>2915890324058328376</integer>
			<key>public-sharing-playlist-name</key>
			<string>Shazam</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>3012362631191148912</integer>
			<key>public-sharing-playlist-name</key>
			<string>Sweet Soul Sunday</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>3038022095057066260</integer>
			<key>public-sharing-playlist-name</key>
			<string>Electronic Concentration</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>3047189537703341549</integer>
			<key>public-sharing-playlist-name</key>
			<string>Les Petits Mouchoirs</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>3071272825452432446</integer>
			<key>public-sharing-playlist-name</key>
			<string>Majestic Casual | Chapter 2</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>3202826346606495455</integer>
			<key>public-sharing-playlist-name</key>
			<string>J'"'"'en ai fait une autre pour toi</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>3208262883033145664</integer>
			<key>public-sharing-playlist-name</key>
			<string>Ennio Morricone The Mission: Music From The Motion Picture</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>3221873343188323392</integer>
			<key>public-sharing-playlist-name</key>
			<string>2013</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>3454730137634490700</integer>
			<key>public-sharing-playlist-name</key>
			<string>90s</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>3490966215089021710</integer>
			<key>public-sharing-playlist-name</key>
			<string>Paul Simon Stranger To Stranger</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>3535912774378365039</integer>
			<key>public-sharing-playlist-name</key>
			<string>One for the scientists</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>3816717612659866508</integer>
			<key>public-sharing-playlist-name</key>
			<string>2014</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>4077320200599081732</integer>
			<key>public-sharing-playlist-name</key>
			<string>Adele</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>4090066955882730438</integer>
			<key>public-sharing-playlist-name</key>
			<string>alt-J Top Tracks</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>4280007695801713610</integer>
			<key>public-sharing-playlist-name</key>
			<string>Classique</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>4417324896151249704</integer>
			<key>public-sharing-playlist-name</key>
			<string>Petit Biscuit Presence</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>4466676928036779552</integer>
			<key>public-sharing-playlist-name</key>
			<string>OST</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>4467862449821010970</integer>
			<key>public-sharing-playlist-name</key>
			<string>alt-J</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>4591645442511804334</integer>
			<key>public-sharing-playlist-name</key>
			<string>Jabberwocky Lunar Lane</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>4671154350736199512</integer>
			<key>public-sharing-playlist-name</key>
			<string>21 Songs To Let Someone Know You Fancy Them</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>4809853875254134984</integer>
			<key>public-sharing-playlist-name</key>
			<string>Lofi Fruits Music  lofi hip hop music to chill, relax, study, sleep</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>4964916431765914589</integer>
			<key>public-sharing-playlist-name</key>
			<string>American Horror Story Freak Show Soundtrack</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>4968299647932300904</integer>
			<key>public-sharing-playlist-name</key>
			<string>New Playlist</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>4986247580359622517</integer>
			<key>public-sharing-playlist-name</key>
			<string>Guts</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>5119211534672213555</integer>
			<key>public-sharing-playlist-name</key>
			<string>Need for Speed: Underground</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>5172307723306057853</integer>
			<key>public-sharing-playlist-name</key>
			<string>Dustin O'"'"'Halloran Piano Solos Vol. 2</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>5272554174569818530</integer>
			<key>public-sharing-playlist-name</key>
			<string>Feist - The Reminder</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>2</integer>
			<key>public-sharing-playlist-id</key>
			<integer>5336233010279024135</integer>
			<key>public-sharing-playlist-name</key>
			<string>Movies</string>
			<key>public-sharing-playlist-shared</key>
			<true/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>5521519297355282899</integer>
			<key>public-sharing-playlist-name</key>
			<string>2012 Campaign Playlist</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>5552967115915665265</integer>
			<key>public-sharing-playlist-name</key>
			<string>Dead</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>5581747841538826164</integer>
			<key>public-sharing-playlist-name</key>
			<string>Fleetwood Mac</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>5588332009398770160</integer>
			<key>public-sharing-playlist-name</key>
			<string>Mes enfants</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>5633599590645669693</integer>
			<key>public-sharing-playlist-name</key>
			<string>-M- Lamomali</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>5645462767285313417</integer>
			<key>public-sharing-playlist-name</key>
			<string>Guts Hip Hop After All</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>5652292278604535895</integer>
			<key>public-sharing-playlist-name</key>
			<string>Bauke Top - We need to eat kale - Single</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>5754677184372396673</integer>
			<key>public-sharing-playlist-name</key>
			<string>Saxo Chill</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>5809394573003670961</integer>
			<key>public-sharing-playlist-name</key>
			<string>Jacques Brel</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>6000809315680817432</integer>
			<key>public-sharing-playlist-name</key>
			<string>Faves</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>6014995322493313274</integer>
			<key>public-sharing-playlist-name</key>
			<string>Intouchables</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>6029265776748919240</integer>
			<key>public-sharing-playlist-name</key>
			<string>Quite Special Death</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>6149142858434948716</integer>
			<key>public-sharing-playlist-name</key>
			<string>Electro Chill</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>6187772690593448009</integer>
			<key>public-sharing-playlist-name</key>
			<string>Musiques de pubs TV 2o13</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>6298058371585256802</integer>
			<key>public-sharing-playlist-name</key>
			<string>Nora En Pure Come With Me</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>6302013741970165419</integer>
			<key>public-sharing-playlist-name</key>
			<string>Disclosure Caracal (Deluxe)</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>6328053075851096926</integer>
			<key>public-sharing-playlist-name</key>
			<string>BON ENTENDEUR</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>6361029298127699721</integer>
			<key>public-sharing-playlist-name</key>
			<string>Liked from Radio</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>6653917365269230082</integer>
			<key>public-sharing-playlist-name</key>
			<string>All New All Now</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>6803890897397488282</integer>
			<key>public-sharing-playlist-name</key>
			<string>Eminem</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>6927062721320975060</integer>
			<key>public-sharing-playlist-name</key>
			<string>Trent Reznor and Atticus Ross The Social Network</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>6954170935833922935</integer>
			<key>public-sharing-playlist-name</key>
			<string>Titles</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>6992276177246702163</integer>
			<key>public-sharing-playlist-name</key>
			<string>Alan Silvestri Cosmos: A SpaceTime Odyssey</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>7064023863293614880</integer>
			<key>public-sharing-playlist-name</key>
			<string>lofi hip hop music - beats to sleep/chill to</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>7073671129656483593</integer>
			<key>public-sharing-playlist-name</key>
			<string>Chill Hits</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>7253523048620898002</integer>
			<key>public-sharing-playlist-name</key>
			<string>Xylo</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>7369343087985310451</integer>
			<key>public-sharing-playlist-name</key>
			<string>Musiques de parfums</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>7376208663448320951</integer>
			<key>public-sharing-playlist-name</key>
			<string>ERA Era I 2002</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>7760465986385803934</integer>
			<key>public-sharing-playlist-name</key>
			<string>70s</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>7774821901003989977</integer>
			<key>public-sharing-playlist-name</key>
			<string>azerty</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>7906824917034097607</integer>
			<key>public-sharing-playlist-name</key>
			<string>Feel Good Friday</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>7920674831216624146</integer>
			<key>public-sharing-playlist-name</key>
			<string>Disco flat</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>7996547113574158126</integer>
			<key>public-sharing-playlist-name</key>
			<string>Chanson</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>8020655853751807317</integer>
			<key>public-sharing-playlist-name</key>
			<string>Chill / Underground Hip-Hop</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>8104634518646362098</integer>
			<key>public-sharing-playlist-name</key>
			<string>Ennio Morricone The Mission: Music From The Motion Picture 2</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>8134501947166408581</integer>
			<key>public-sharing-playlist-name</key>
			<string>Top hip hop chill tracks</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>8148245374271063946</integer>
			<key>public-sharing-playlist-name</key>
			<string>Chill Out Music</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>8156320750894823189</integer>
			<key>public-sharing-playlist-name</key>
			<string>Spotify Singles: Covers</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>8186918775971017862</integer>
			<key>public-sharing-playlist-name</key>
			<string>My Shazam Tracks</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>8446935662971419924</integer>
			<key>public-sharing-playlist-name</key>
			<string>Boney M.</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>8532574338325961921</integer>
			<key>public-sharing-playlist-name</key>
			<string>Fourrez-moi tout ça ici</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>8634127683880917319</integer>
			<key>public-sharing-playlist-name</key>
			<string>Majestic Casual ✨</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>8811690109661793461</integer>
			<key>public-sharing-playlist-name</key>
			<string>Mozart</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>8857803099342517638</integer>
			<key>public-sharing-playlist-name</key>
			<string>Psyche</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>8938650358566806042</integer>
			<key>public-sharing-playlist-name</key>
			<string>Classical Relax</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>8982136379496724111</integer>
			<key>public-sharing-playlist-name</key>
			<string>Minimal Techno</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>9107955321670240423</integer>
			<key>public-sharing-playlist-name</key>
			<string>Space</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>9114056604087901213</integer>
			<key>public-sharing-playlist-name</key>
			<string>Apple Keynote: WWDC 2013</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>9123588920065936426</integer>
			<key>public-sharing-playlist-name</key>
			<string>Karaoke</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>2</integer>
			<key>public-sharing-playlist-id</key>
			<integer>9124674239921717140</integer>
			<key>public-sharing-playlist-name</key>
			<string>Rentals</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>9134998724364159376</integer>
			<key>public-sharing-playlist-name</key>
			<string>Discover Weekly Archive</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-9166823881836714329</integer>
			<key>public-sharing-playlist-name</key>
			<string>Good Morning England</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-9008752909766801036</integer>
			<key>public-sharing-playlist-name</key>
			<string>Années 2000</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-8882128699777598407</integer>
			<key>public-sharing-playlist-name</key>
			<string>2011</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-8715768099838519976</integer>
			<key>public-sharing-playlist-name</key>
			<string>Trop perchées</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-8650497429327359851</integer>
			<key>public-sharing-playlist-name</key>
			<string>Fair</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-8575413556085909479</integer>
			<key>public-sharing-playlist-name</key>
			<string>Need for Speed: Underground 2</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-8556252040814174569</integer>
			<key>public-sharing-playlist-name</key>
			<string>Soirée</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-8391666803229009994</integer>
			<key>public-sharing-playlist-name</key>
			<string>Iron</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-8208496532383817048</integer>
			<key>public-sharing-playlist-name</key>
			<string>Chill &amp; Relax  Summer Electro Chill Music | Mix été 2021 | Lounge songs 2021 | Chillout apéro posé</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-8195394383306476146</integer>
			<key>public-sharing-playlist-name</key>
			<string>Spotify.Me</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-8160239058529006597</integer>
			<key>public-sharing-playlist-name</key>
			<string>Love</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-8145884871719755428</integer>
			<key>public-sharing-playlist-name</key>
			<string>Bob</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-8143150646991993044</integer>
			<key>public-sharing-playlist-name</key>
			<string>Sensual</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-8130768929394314289</integer>
			<key>public-sharing-playlist-name</key>
			<string>Grand art</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-7858632410169411584</integer>
			<key>public-sharing-playlist-name</key>
			<string>Douls</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-7855134846247986626</integer>
			<key>public-sharing-playlist-name</key>
			<string>Oldies</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-7808930489607068089</integer>
			<key>public-sharing-playlist-name</key>
			<string>Skrillex Bangarang</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-7761419177961135291</integer>
			<key>public-sharing-playlist-name</key>
			<string>Mop Mop Lunar Love</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-7692569180277033168</integer>
			<key>public-sharing-playlist-name</key>
			<string>John Williams Star Wars: The Force Awakens (Original Motion Picture Soundtrack)</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-7676521055270240770</integer>
			<key>public-sharing-playlist-name</key>
			<string>Hip Hop Chill</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-7606981357714442979</integer>
			<key>public-sharing-playlist-name</key>
			<string>Hot Hits UK</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-7506877210588507561</integer>
			<key>public-sharing-playlist-name</key>
			<string>Téléphone</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-7369070669196265257</integer>
			<key>public-sharing-playlist-name</key>
			<string>Five Bottles of Mambo Yma Sumac</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-7332696006758473894</integer>
			<key>public-sharing-playlist-name</key>
			<string>Mop Mop Ritual of the Savage</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-7310582231491099951</integer>
			<key>public-sharing-playlist-name</key>
			<string>Guts Paradise for All (Deluxe Edition)</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-7136846477468752059</integer>
			<key>public-sharing-playlist-name</key>
			<string>Manau</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-7110082665008716268</integer>
			<key>public-sharing-playlist-name</key>
			<string>Soultronic</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-7028937710239357976</integer>
			<key>public-sharing-playlist-name</key>
			<string>The Most Beautiful Songs in the World</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-6844091271823602415</integer>
			<key>public-sharing-playlist-name</key>
			<string>Yann Tiersen - Le fabuleux destin d'"'"'Amélie Poulain</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-6686611507227047237</integer>
			<key>public-sharing-playlist-name</key>
			<string>One for the engineers</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-6664006355677852266</integer>
			<key>public-sharing-playlist-name</key>
			<string>American Horror Story</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-6625154847462342106</integer>
			<key>public-sharing-playlist-name</key>
			<string>Iam Rêvolution (Deluxe)</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-6515780886080856418</integer>
			<key>public-sharing-playlist-name</key>
			<string>J'"'"'accuse</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-6512281080084094543</integer>
			<key>public-sharing-playlist-name</key>
			<string>Next</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-6457547161389378194</integer>
			<key>public-sharing-playlist-name</key>
			<string>La Playlist de France Inter (officiel)</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-6298202622397431643</integer>
			<key>public-sharing-playlist-name</key>
			<string>Hans Zimmer Interstellar: Original Motion Picture Soundtrack (Deluxe Digital Version)</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-6286630254788875594</integer>
			<key>public-sharing-playlist-name</key>
			<string>Monday Motivation</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-6245154236323509919</integer>
			<key>public-sharing-playlist-name</key>
			<string>Crap</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-6220110153131436899</integer>
			<key>public-sharing-playlist-name</key>
			<string>Summer</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-6206827673582160568</integer>
			<key>public-sharing-playlist-name</key>
			<string>Discover Weekly Archive</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-6136936371339484123</integer>
			<key>public-sharing-playlist-name</key>
			<string>Moby</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-5985395783208917840</integer>
			<key>public-sharing-playlist-name</key>
			<string>Iridium-7 Launch Soundtrack</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-5973279529314482068</integer>
			<key>public-sharing-playlist-name</key>
			<string>Saint-Germain-des-Prés Café Vol. 16 by KlangKuenstler</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-5959206680720662911</integer>
			<key>public-sharing-playlist-name</key>
			<string>Leonard</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-5912476201775634976</integer>
			<key>public-sharing-playlist-name</key>
			<string>Divers</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-5780074771205286694</integer>
			<key>public-sharing-playlist-name</key>
			<string>Quentin Tarantino’s Django Unchained Original Motion Picture Soundtrack</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-5761492497171252757</integer>
			<key>public-sharing-playlist-name</key>
			<string>Chill Tracks</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-5745064865872471854</integer>
			<key>public-sharing-playlist-name</key>
			<string>80s</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-5650294839775888140</integer>
			<key>public-sharing-playlist-name</key>
			<string>Brain Food</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-5604272478838184252</integer>
			<key>public-sharing-playlist-name</key>
			<string>Les Musiques des Publicités utilisées par Apple - via ApplePub.fr</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-5591951402071624030</integer>
			<key>public-sharing-playlist-name</key>
			<string>Rock</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-5549049319058455300</integer>
			<key>public-sharing-playlist-name</key>
			<string>Back to school</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-5542782561656330567</integer>
			<key>public-sharing-playlist-name</key>
			<string>Gospel/Vocal</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-5336163285001754768</integer>
			<key>public-sharing-playlist-name</key>
			<string>Pop</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-5285499188448639462</integer>
			<key>public-sharing-playlist-name</key>
			<string>Majestic Casual | Chapter 3</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-5271460335348897738</integer>
			<key>public-sharing-playlist-name</key>
			<string>Cinematic Chillout</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-5203757166476834869</integer>
			<key>public-sharing-playlist-name</key>
			<string>Pozey</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-5042253705158159914</integer>
			<key>public-sharing-playlist-name</key>
			<string>Piano</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-4977346890382813375</integer>
			<key>public-sharing-playlist-name</key>
			<string>Throwback Party</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-4893248282272673788</integer>
			<key>public-sharing-playlist-name</key>
			<string>The Tree of Life</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-4847834905275507001</integer>
			<key>public-sharing-playlist-name</key>
			<string>Wayra (Dance Of The Winds) Yma Sumac</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-4798741859253761077</integer>
			<key>public-sharing-playlist-name</key>
			<string>Chopin Last Sonata</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>8</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-4583535256750891904</integer>
			<key>public-sharing-playlist-name</key>
			<string>Audiobooks</string>
			<key>public-sharing-playlist-shared</key>
			<true/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-4475661344741077296</integer>
			<key>public-sharing-playlist-name</key>
			<string>La playlist estivale de France Inter</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-4461918976693002768</integer>
			<key>public-sharing-playlist-name</key>
			<string>New Playlist</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-4374714400846237191</integer>
			<key>public-sharing-playlist-name</key>
			<string>Quentin Tarantino'"'"'s Inglourious Basterds Motion Picture Soundtrack Quentin Tarantino'"'"'s Inglourious Basterds Motion Picture Soundtrack</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-4279857850574752544</integer>
			<key>public-sharing-playlist-name</key>
			<string>My Shazam Tracks</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-4268513972942992842</integer>
			<key>public-sharing-playlist-name</key>
			<string>Starred</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-4138825019419507576</integer>
			<key>public-sharing-playlist-name</key>
			<string>Nostalgie</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-4116641063431670063</integer>
			<key>public-sharing-playlist-name</key>
			<string>Electro posé/CHILL</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-4033489908709716905</integer>
			<key>public-sharing-playlist-name</key>
			<string>Club</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-4026417681533806346</integer>
			<key>public-sharing-playlist-name</key>
			<string>ALL</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-3941747482458008776</integer>
			<key>public-sharing-playlist-name</key>
			<string>Various Artists Mixtape, Vol. 1 (Rond la lune)</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-3795744327818025669</integer>
			<key>public-sharing-playlist-name</key>
			<string>ELECTRO/TECHNO</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-3691186285132058881</integer>
			<key>public-sharing-playlist-name</key>
			<string>lofi hip hop beats - music to study/relax to | Focus Music | Chillhop Music 2021</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-3622031582587194818</integer>
			<key>public-sharing-playlist-name</key>
			<string>Hans Zimmer</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-3613732524864151319</integer>
			<key>public-sharing-playlist-name</key>
			<string>Ray</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-3591238884905990314</integer>
			<key>public-sharing-playlist-name</key>
			<string>Spotify &amp; Chill</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-3553643002829737984</integer>
			<key>public-sharing-playlist-name</key>
			<string>Mardi</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-3493470662919157644</integer>
			<key>public-sharing-playlist-name</key>
			<string>Calme</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-3438799798995982210</integer>
			<key>public-sharing-playlist-name</key>
			<string>Dance</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-3411671323587901334</integer>
			<key>public-sharing-playlist-name</key>
			<string>Late Night Vibes - Chillhop / Ambient / Lofi Hip Hop | Sleep Music | Chillhop Music 2020</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-3382946069476733962</integer>
			<key>public-sharing-playlist-name</key>
			<string>Various Artists Yoga Music</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-3310790202109753351</integer>
			<key>public-sharing-playlist-name</key>
			<string>Guts Le Bienheureux</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-3270533524107069690</integer>
			<key>public-sharing-playlist-name</key>
			<string>50s</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-3069394731726358288</integer>
			<key>public-sharing-playlist-name</key>
			<string>Video</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-3054445136925165923</integer>
			<key>public-sharing-playlist-name</key>
			<string>Lana</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-3028357606289623389</integer>
			<key>public-sharing-playlist-name</key>
			<string>net7</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-2952715996888012511</integer>
			<key>public-sharing-playlist-name</key>
			<string>TBEP</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-2919173932838884564</integer>
			<key>public-sharing-playlist-name</key>
			<string>60s</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-2907231674108551257</integer>
			<key>public-sharing-playlist-name</key>
			<string>Hip Hop Fr</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-2895029057488203946</integer>
			<key>public-sharing-playlist-name</key>
			<string>Electro Hits  Dance Hits, Electro Dance Hits Electro, EDM, Soiree Electro, Soiree EDM, Soiree Club</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-2886774694260321106</integer>
			<key>public-sharing-playlist-name</key>
			<string>Classical Favourites for Relaxing and Dreaming</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-2848586464518460378</integer>
			<key>public-sharing-playlist-name</key>
			<string>Coming-Next Grand Journal 2004/2015</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-2658333414441364103</integer>
			<key>public-sharing-playlist-name</key>
			<string>Showoff</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-2636914861497413864</integer>
			<key>public-sharing-playlist-name</key>
			<string>Majestic Casual - Chapter 3</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-2568214474367734325</integer>
			<key>public-sharing-playlist-name</key>
			<string>Game Of Thrones - Relaxing</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-2559222201948596525</integer>
			<key>public-sharing-playlist-name</key>
			<string>MJ</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-2534621325990759520</integer>
			<key>public-sharing-playlist-name</key>
			<string>Find them Next</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-2482502518615537617</integer>
			<key>public-sharing-playlist-name</key>
			<string>Wake Up Happy</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-2457183018012991181</integer>
			<key>public-sharing-playlist-name</key>
			<string>Battlestar Galactica</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-2312756244785208561</integer>
			<key>public-sharing-playlist-name</key>
			<string>The Beatles</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-2287173297078501310</integer>
			<key>public-sharing-playlist-name</key>
			<string>Lowkey Tech</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-2181449879819890561</integer>
			<key>public-sharing-playlist-name</key>
			<string>MIKA Life In Cartoon Motion</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-2152622376296096783</integer>
			<key>public-sharing-playlist-name</key>
			<string>The Crown Seasons 1 and 2</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-2087504895080595073</integer>
			<key>public-sharing-playlist-name</key>
			<string>The F Word</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-2085017283286624645</integer>
			<key>public-sharing-playlist-name</key>
			<string>Electronica</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>2</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-2049014209140165662</integer>
			<key>public-sharing-playlist-name</key>
			<string>Home Videos</string>
			<key>public-sharing-playlist-shared</key>
			<true/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-2019710793682010379</integer>
			<key>public-sharing-playlist-name</key>
			<string>Avocuddle, vensterbank &amp; Fets - Ain'"'"'t No Sunshine - Single</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-2011878877113872523</integer>
			<key>public-sharing-playlist-name</key>
			<string>Electro Chill</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-2002579988917109102</integer>
			<key>public-sharing-playlist-name</key>
			<string>Musiques de pubs TV 2o12</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-1988455389787255726</integer>
			<key>public-sharing-playlist-name</key>
			<string>Discover Weekly</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-1819528597667245524</integer>
			<key>public-sharing-playlist-name</key>
			<string>ERA Life Is Movie</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-1737229079275705482</integer>
			<key>public-sharing-playlist-name</key>
			<string>Select</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-1649223093993335346</integer>
			<key>public-sharing-playlist-name</key>
			<string>SoundHound History</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-1596947894400570956</integer>
			<key>public-sharing-playlist-name</key>
			<string>Kyle Dixon &amp; Michael Stein Stranger Things</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-1562162369542083714</integer>
			<key>public-sharing-playlist-name</key>
			<string>Électro</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-1523477314635195383</integer>
			<key>public-sharing-playlist-name</key>
			<string>Dodo</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-1395319954078128930</integer>
			<key>public-sharing-playlist-name</key>
			<string>Play it Forward</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-1393675602667783756</integer>
			<key>public-sharing-playlist-name</key>
			<string>France Gall</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-1387735151987144290</integer>
			<key>public-sharing-playlist-name</key>
			<string>Spring</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-1317064094885711287</integer>
			<key>public-sharing-playlist-name</key>
			<string>Classique Chillout</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-1292717136980860368</integer>
			<key>public-sharing-playlist-name</key>
			<string>Ludovico Einaudi La Scala: Concert 03 03 03</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-1193293398960856203</integer>
			<key>public-sharing-playlist-name</key>
			<string>Mariss Jansons/Oslo Philharmonic Orchestra Dvorák: Symphonies</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-1104817634322427232</integer>
			<key>public-sharing-playlist-name</key>
			<string>Mourning</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-1101386974558573180</integer>
			<key>public-sharing-playlist-name</key>
			<string>Club 2</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-1055819532795546167</integer>
			<key>public-sharing-playlist-name</key>
			<string>Happy</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-965790467395147595</integer>
			<key>public-sharing-playlist-name</key>
			<string>Agnes Obel Philharmonics</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-874001106812606154</integer>
			<key>public-sharing-playlist-name</key>
			<string>SoundHound</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-741036318240150559</integer>
			<key>public-sharing-playlist-name</key>
			<string>Oriental</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-666601402798194890</integer>
			<key>public-sharing-playlist-name</key>
			<string>France Inter</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-659256392706741459</integer>
			<key>public-sharing-playlist-name</key>
			<string>James Newton Howard The Village</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-636014087900538914</integer>
			<key>public-sharing-playlist-name</key>
			<string>Hans Zimmer Planet Earth II (Original Television Soundtrack)</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-451145225863798084</integer>
			<key>public-sharing-playlist-name</key>
			<string>Blizard</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-417519961564471872</integer>
			<key>public-sharing-playlist-name</key>
			<string>Relax</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-403021977701410600</integer>
			<key>public-sharing-playlist-name</key>
			<string>Your Top Songs 2019</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-338252098461617995</integer>
			<key>public-sharing-playlist-name</key>
			<string>Morceaux piano</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-302068165227405532</integer>
			<key>public-sharing-playlist-name</key>
			<string>Cat Relaxation Music</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-268575282227905386</integer>
			<key>public-sharing-playlist-name</key>
			<string>Années 80</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-251825756092334239</integer>
			<key>public-sharing-playlist-name</key>
			<string>Latino</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-99255172647278595</integer>
			<key>public-sharing-playlist-name</key>
			<string>Various Artists 3xA Mixed Series</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-60923274756452765</integer>
			<key>public-sharing-playlist-name</key>
			<string>Summer</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
		<dict>
			<key>public-sharing-playlist-domain</key>
			<integer>1</integer>
			<key>public-sharing-playlist-id</key>
			<integer>-19083216193459720</integer>
			<key>public-sharing-playlist-name</key>
			<string>Howard Shore Lord Of The Rings-The Fellowship Of The Ring</string>
			<key>public-sharing-playlist-shared</key>
			<false/>
		</dict>
	</array>
	<key>public-sharing-share-all-playlists</key>
	<false/>
</dict>
'
defaults write com.apple.amp.mediasharingd "shared-library-id" -integer -1213722282796290816
defaults write com.apple.amp.mediasharingd "shared-library-machine-id" -integer -1545403488374349714
defaults write com.apple.amp.mediasharingd "shared-library-name" -string 'Maxime Bories’s Library'
