#!/usr/bin/env bash

defaults write com.apple.Music "NSApplicationCrashOnExceptions" -boolean false
defaults write com.apple.Music "PPr4:LIB:48d4a9aa1d14832e:5" '
<dict>
	<key>browseHeight</key>
	<integer>140</integer>
	<key>browseVisible</key>
	<false/>
	<key>columnSets</key>
	<array>
		<dict>
			<key>artwork</key>
			<false/>
			<key>columns</key>
			<array>
				<dict>
					<key>field</key>
					<integer>1</integer>
					<key>moveable</key>
					<false/>
					<key>resizeable</key>
					<false/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<false/>
					<key>width</key>
					<integer>45</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>125</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<false/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>15</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>2</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<true/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>200</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>130</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<false/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>27</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>13</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<true/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>59</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>4</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<true/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>125</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>3</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<true/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>125</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>8</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<true/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>80</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>154</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<false/>
					<key>reversed</key>
					<true/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>27</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>22</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<true/>
					<key>reversed</key>
					<true/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>65</integer>
				</dict>
			</array>
			<key>order</key>
			<integer>7</integer>
			<key>reversed</key>
			<false/>
			<key>sortColumn</key>
			<integer>5</integer>
			<key>viewGrouping</key>
			<integer>0</integer>
			<key>viewMode</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>artwork</key>
			<false/>
			<key>columns</key>
			<array>
				<dict>
					<key>field</key>
					<integer>126</integer>
					<key>moveable</key>
					<false/>
					<key>resizeable</key>
					<true/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>230</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>1</integer>
					<key>moveable</key>
					<false/>
					<key>resizeable</key>
					<false/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<false/>
					<key>width</key>
					<integer>45</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>125</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<false/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>15</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>2</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<true/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>200</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>130</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<false/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>27</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>13</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<true/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>59</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>4</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<true/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>125</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>3</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<true/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>125</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>8</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<true/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>80</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>154</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<false/>
					<key>reversed</key>
					<true/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>27</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>22</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<true/>
					<key>reversed</key>
					<true/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>65</integer>
				</dict>
			</array>
			<key>order</key>
			<integer>5</integer>
			<key>reversed</key>
			<false/>
			<key>sortColumn</key>
			<integer>0</integer>
			<key>viewGrouping</key>
			<integer>0</integer>
			<key>viewMode</key>
			<integer>5</integer>
		</dict>
	</array>
	<key>composersSplitWidth</key>
	<integer>0</integer>
	<key>maximized</key>
	<false/>
	<key>modifiedDate</key>
	<date>2021-10-03T18:16:37Z</date>
	<key>textArtworkVisible</key>
	<false/>
	<key>thumbArtworkVisible</key>
	<true/>
	<key>unwatchedSplitWidth</key>
	<integer>0</integer>
	<key>viewMode</key>
	<integer>0</integer>
	<key>windowHPos</key>
	<integer>670</integer>
	<key>windowHeight</key>
	<integer>720</integer>
	<key>windowVPos</key>
	<integer>229</integer>
	<key>windowWidth</key>
	<integer>1220</integer>
	<key>zoomed</key>
	<false/>
</dict>
'
defaults write com.apple.Music "PPr4:LIB:48d4a9aa1d14832e:67eedb9ec923e83e" '
<dict>
	<key>browseHeight</key>
	<integer>140</integer>
	<key>browseVisible</key>
	<false/>
	<key>columnSets</key>
	<array>
		<dict>
			<key>artwork</key>
			<false/>
			<key>columns</key>
			<array>
				<dict>
					<key>field</key>
					<integer>1</integer>
					<key>moveable</key>
					<false/>
					<key>resizeable</key>
					<false/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>45</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>125</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<false/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>15</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>2</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<true/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>200</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>130</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<false/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>27</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>13</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<true/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>59</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>4</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<true/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>125</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>3</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<true/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>125</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>8</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<true/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>80</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>154</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<false/>
					<key>reversed</key>
					<true/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>27</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>22</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<true/>
					<key>reversed</key>
					<true/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>65</integer>
				</dict>
			</array>
			<key>order</key>
			<integer>1</integer>
			<key>reversed</key>
			<false/>
			<key>sortColumn</key>
			<integer>0</integer>
			<key>viewGrouping</key>
			<integer>0</integer>
			<key>viewMode</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>artwork</key>
			<false/>
			<key>columns</key>
			<array>
				<dict>
					<key>field</key>
					<integer>126</integer>
					<key>moveable</key>
					<false/>
					<key>resizeable</key>
					<true/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>230</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>1</integer>
					<key>moveable</key>
					<false/>
					<key>resizeable</key>
					<false/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>45</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>125</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<false/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>15</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>2</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<true/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>200</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>130</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<false/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>27</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>13</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<true/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>59</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>4</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<true/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>125</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>3</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<true/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>125</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>8</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<true/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>80</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>154</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<false/>
					<key>reversed</key>
					<true/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>27</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>22</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<true/>
					<key>reversed</key>
					<true/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>65</integer>
				</dict>
			</array>
			<key>order</key>
			<integer>1</integer>
			<key>reversed</key>
			<false/>
			<key>sortColumn</key>
			<integer>1</integer>
			<key>viewGrouping</key>
			<integer>0</integer>
			<key>viewMode</key>
			<integer>5</integer>
		</dict>
	</array>
	<key>composersSplitWidth</key>
	<integer>0</integer>
	<key>maximized</key>
	<false/>
	<key>modifiedDate</key>
	<date>2021-10-03T12:18:22Z</date>
	<key>textArtworkVisible</key>
	<false/>
	<key>thumbArtworkVisible</key>
	<true/>
	<key>unwatchedSplitWidth</key>
	<integer>0</integer>
	<key>viewMode</key>
	<integer>0</integer>
	<key>windowHPos</key>
	<integer>0</integer>
	<key>windowVPos</key>
	<integer>0</integer>
	<key>zoomed</key>
	<false/>
</dict>
'
defaults write com.apple.Music "PPr4:LIB:48d4a9aa1d14832e:ed9ca3fc03bd9a7" '
<dict>
	<key>browseHeight</key>
	<integer>140</integer>
	<key>browseVisible</key>
	<false/>
	<key>columnSets</key>
	<array>
		<dict>
			<key>artwork</key>
			<false/>
			<key>columns</key>
			<array>
				<dict>
					<key>field</key>
					<integer>1</integer>
					<key>moveable</key>
					<false/>
					<key>resizeable</key>
					<false/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<false/>
					<key>width</key>
					<integer>45</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>125</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<false/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>15</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>2</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<true/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>200</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>130</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<false/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>27</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>13</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<true/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>59</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>4</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<true/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>125</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>3</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<true/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>125</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>8</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<true/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>80</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>154</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<false/>
					<key>reversed</key>
					<true/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>27</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>22</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<true/>
					<key>reversed</key>
					<true/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>65</integer>
				</dict>
			</array>
			<key>order</key>
			<integer>7</integer>
			<key>reversed</key>
			<false/>
			<key>sortColumn</key>
			<integer>5</integer>
			<key>viewGrouping</key>
			<integer>0</integer>
			<key>viewMode</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>artwork</key>
			<false/>
			<key>columns</key>
			<array>
				<dict>
					<key>field</key>
					<integer>126</integer>
					<key>moveable</key>
					<false/>
					<key>resizeable</key>
					<true/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>230</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>1</integer>
					<key>moveable</key>
					<false/>
					<key>resizeable</key>
					<false/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<false/>
					<key>width</key>
					<integer>45</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>125</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<false/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>15</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>2</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<true/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>200</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>130</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<false/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>27</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>13</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<true/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>59</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>4</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<true/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>125</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>3</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<true/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>125</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>8</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<true/>
					<key>reversed</key>
					<false/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>80</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>154</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<false/>
					<key>reversed</key>
					<true/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>27</integer>
				</dict>
				<dict>
					<key>field</key>
					<integer>22</integer>
					<key>moveable</key>
					<true/>
					<key>resizeable</key>
					<true/>
					<key>reversed</key>
					<true/>
					<key>sortable</key>
					<true/>
					<key>width</key>
					<integer>65</integer>
				</dict>
			</array>
			<key>order</key>
			<integer>7</integer>
			<key>reversed</key>
			<false/>
			<key>sortColumn</key>
			<integer>6</integer>
			<key>viewGrouping</key>
			<integer>0</integer>
			<key>viewMode</key>
			<integer>5</integer>
		</dict>
	</array>
	<key>composersSplitWidth</key>
	<integer>0</integer>
	<key>maximized</key>
	<false/>
	<key>modifiedDate</key>
	<date>2021-10-03T18:16:37Z</date>
	<key>textArtworkVisible</key>
	<false/>
	<key>thumbArtworkVisible</key>
	<true/>
	<key>unwatchedSplitWidth</key>
	<integer>0</integer>
	<key>viewMode</key>
	<integer>0</integer>
	<key>windowHPos</key>
	<integer>0</integer>
	<key>windowVPos</key>
	<integer>0</integer>
	<key>zoomed</key>
	<false/>
</dict>
'
defaults write com.apple.Music "RDoc:132:Documents" '
<data>
AAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAQlJPVwAAADQBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEA
AAAO2co/wDvZpwAAANwAAAEGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
</data>
'
defaults write com.apple.Music "StoreUserInfo" '
<dict>
	<key>166608742</key>
	<dict>
		<key>UserHandle</key>
		<string></string>
		<key>UserName</key>
		<string>Maxime Bories</string>
	</dict>
</dict>
'
defaults write com.apple.Music "bwui" '
<dict>
	<key>sidebar-hidden</key>
	<array>
		<dict>
			<key>distinguishedPlaylistKind</key>
			<integer>4</integer>
			<key>mediaViewMode</key>
			<integer>5</integer>
			<key>setbyuserinteraction</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>distinguishedPlaylistKind</key>
			<integer>4</integer>
			<key>mediaViewMode</key>
			<integer>10</integer>
			<key>setbyuserinteraction</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>distinguishedPlaylistKind</key>
			<integer>64</integer>
			<key>mediaViewMode</key>
			<integer>38</integer>
			<key>setbyuserinteraction</key>
			<integer>0</integer>
		</dict>
	</array>
	<key>sidebar-shown</key>
	<array>
		<dict>
			<key>distinguishedPlaylistKind</key>
			<integer>4</integer>
			<key>mediaViewMode</key>
			<integer>4</integer>
			<key>setbyuserinteraction</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>distinguishedPlaylistKind</key>
			<integer>4</integer>
			<key>mediaViewMode</key>
			<integer>6</integer>
			<key>setbyuserinteraction</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>distinguishedPlaylistKind</key>
			<integer>4</integer>
			<key>mediaViewMode</key>
			<integer>8</integer>
			<key>setbyuserinteraction</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>distinguishedPlaylistKind</key>
			<integer>4</integer>
			<key>mediaViewMode</key>
			<integer>9</integer>
			<key>setbyuserinteraction</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>distinguishedPlaylistKind</key>
			<integer>4</integer>
			<key>mediaViewMode</key>
			<integer>41</integer>
			<key>setbyuserinteraction</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>distinguishedPlaylistKind</key>
			<integer>47</integer>
			<key>mediaViewMode</key>
			<integer>38</integer>
			<key>setbyuserinteraction</key>
			<integer>1</integer>
		</dict>
	</array>
</dict>
'
defaults write com.apple.Music "checkedHLSKeysTime" -integer 3716122018
defaults write com.apple.Music "com.apple.Music.WebKit2AsynchronousSpellCheckingEnabled" -boolean true
defaults write com.apple.Music "com.apple.Music.WebKit2EnableInheritURIQueryComponent" -boolean true
defaults write com.apple.Music "com.apple.Music.WebKit2ShouldPrintBackgrounds" -boolean true
defaults write com.apple.Music "com.apple.Music.WebKit2ShowsToolTipOverTruncatedText" -boolean true
defaults write com.apple.Music "com.apple.Music.WebKit2SuppressesIncrementalRendering" -boolean true
defaults write com.apple.Music "com.apple.Music.WebKit2UserInterfaceDirectionPolicy" -integer 1
defaults write com.apple.Music "controllableInterfaceGUID" -integer 484875494610058857
defaults write com.apple.Music "debugAssertCategoriesEnabled" -integer 0
defaults write com.apple.Music "debugAssertCategoriesVersion" -integer 3
defaults write com.apple.Music "devp:2:Device Information" '
<data>
PiyP38MYTEYSUUcdUd3Xg2qpmubb/dyY2YX8gMulu/+Vdf+U0W3snKazSbe1F2imgyTR
QwzakoJ8Gh7aiizg2n6dRjovWSUmdhqhODazYdVU
</data>
'
defaults write com.apple.Music "doesStoreSupportCloudMusicLibrary" -integer 1
defaults write com.apple.Music "encoderName" -string 'AAC Encoder'
defaults write com.apple.Music "eqPrefsVersion" -integer 1
defaults write com.apple.Music "firstLaunchShowWelcomeScreenState" -integer 2
defaults write com.apple.Music "gnot:1:Gracenote Match Registered User ID" '
<data>
V0VjeEE0eVdmb1RRMVVJUzZrVW1VaXNKN1RLQXRkK0hCSksyK3l5THNWSUlSN1grQkwr
cjM2LzNqNU1KcXNleEU1MXgrLzkvQmkyQ2FiTVdUY05aRFM1VDFUZVRGa3ZtcTVPbFpE
cGV5bGpWeTFldTNZWVFqY3kxNmlEcmIyeWRpeStOcThvTytKTHBiRUhPUUNkNkgzVjQv
U1duY1hZWXdrSE43RVNnekpyYUxPR3M1TlU9AA==
</data>
'
defaults write com.apple.Music "gnot:2:Gracenote CDDB Lookup Registered User ID" '
<data>
V0VjeEE0TnpKOHhrTzRZWlUwUDV5S1RzU3hhR1BpSjY4ZUhlR1V4YnVIN0xlbFJQZ2JU
TUF2dHRMYm1nenE3UDVKTlc5ZlRxUVB2RW4ybVJaTXk4NDFoQXJoOTkyZTRualJBOGZU
cFZGT1VUT1NWRkRvZCszME1JbVdkOWEyeWRabXpmbnUxZks4Y1MwMlFCWlFGTW5oMENB
TlZnY1o4dGlVcGx3NVJBdEZzeUdHeVc3ZVU9AA==
</data>
'
defaults write com.apple.Music "haveRadioState" -integer 1
defaults write com.apple.Music "imported-eq-presets" -integer 1
defaults write com.apple.Music "library-bookmark" '
<data>
Ym9va8QDAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAIA
AAUAAAABAQAAVXNlcnMAAAAGAAAAAQEAAG1heGltZQAABQAAAAEBAABNdXNpYwAAABoA
AAABAQAATXVzaWMgTGlicmFyeS5tdXNpY2xpYnJhcnkAABQAAAABBgAABAAAABQAAAAk
AAAAJAAAADQAAAAIAAAABAMAAHlkAAAAAAAACAAAAAQDAAA4jQAAAAAAAAgAAAAEAwAA
OY0AAAAAAAAIAAAABAMAAI+NCQAAAAAACAAAAAQDAAAFjgkAAAAAABQAAAABBgAAdAAA
AIQAAACUAAAApAAAALQAAAAIAAAAAAQAAEHDhNEZgAAAGAAAAAECAAACAAAAAAAAAA8A
AAAAAAAAAAAAAAAAAAAIAAAABAMAAAMAAAAAAAAABAAAAAMDAAD1AQAACAAAAAEJAABm
aWxlOi8vLwoAAAABAQAAbWFjT1MgLSBIRAAACAAAAAQDAAAAAIcROQAAAAgAAAAABAAA
QcN+9mSAAAAkAAAAAQEAADc3N0IxMjUzLTE1QzAtNEZDMS05NTU1LTBBOTI2RTFDREQ3
NRgAAAABAgAAgQAAAAEAAADvEwAAAQAAAAAAAAAAAAAAAQAAAAEBAAAvAAAAAAAAAAEF
AADmAAAAAQIAAGQ2OGI5Yzc5ODJiZTViZjFjMDU2OTVhZmU4MDA3YjU1ODhlMzM2YzU1
NWU4Njc3ZDFjNTBhOWM4NDAwZjFjZjE7MDA7MDAwMDAwMDA7MDAwMDAwMDA7MDAwMDAw
MDA7MDAwMDAwMDAwMDAwMDAyMDtjb20uYXBwbGUuYXBwLXNhbmRib3gucmVhZC13cml0
ZTswMTswMTAwMDAwZDswMDAwMDAwMDAwMDk4ZTA1OzAxOy91c2Vycy9tYXhpbWUvbXVz
aWMvbXVzaWMvbXVzaWMgbGlicmFyeS5tdXNpY2xpYnJhcnkAAADMAAAA/v///wEAAAAA
AAAAEAAAAAQQAABYAAAAAAAAAAUQAADEAAAAAAAAABAQAADwAAAAAAAAAEAQAADgAAAA
AAAAAAIgAAC8AQAAAAAAAAUgAAAsAQAAAAAAABAgAAA8AQAAAAAAABEgAABwAQAAAAAA
ABIgAABQAQAAAAAAABMgAABgAQAAAAAAACAgAACcAQAAAAAAADAgAADIAQAAAAAAAAHA
AAAQAQAAAAAAABHAAAAUAAAAAAAAABLAAAAgAQAAAAAAAIDwAADQAQAAAAAAAA==
</data>
'
defaults write com.apple.Music "media-folder-bookmark" '
<data>
Ym9va6wDAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAqAIA
AAUAAAABAQAAVXNlcnMAAAAGAAAAAQEAAG1heGltZQAABQAAAAEBAABNdXNpYwAAAA8A
AAABAQAATWVkaWEubG9jYWxpemVkABQAAAABBgAABAAAABQAAAAkAAAAJAAAADQAAAAI
AAAABAMAAHlkAAAAAAAACAAAAAQDAAA4jQAAAAAAAAgAAAAEAwAAOY0AAAAAAAAIAAAA
BAMAAI+NCQAAAAAACAAAAAQDAACQjQkAAAAAABQAAAABBgAAaAAAAHgAAACIAAAAmAAA
AKgAAAAIAAAAAAQAAEHDhNEZV6wyGAAAAAECAAACAAAAAAAAAA8AAAAAAAAAAAAAAAAA
AAAIAAAABAMAAAMAAAAAAAAABAAAAAMDAAD1AQAACAAAAAEJAABmaWxlOi8vLwoAAAAB
AQAAbWFjT1MgLSBIRAAACAAAAAQDAAAAAIcROQAAAAgAAAAABAAAQcN+9mSAAAAkAAAA
AQEAADc3N0IxMjUzLTE1QzAtNEZDMS05NTU1LTBBOTI2RTFDREQ3NRgAAAABAgAAgQAA
AAEAAADvEwAAAQAAAAAAAAAAAAAAAQAAAAEBAAAvAAAAAAAAAAEFAADbAAAAAQIAADI4
MDJhZGNlNGJiZTE5ZjcxYzEyYmY0OTIyNjExOTVmMzA0YTVmMjk2ZTBjOTI4NjAxZmRh
OGI1ZDFjZTczZDM7MDA7MDAwMDAwMDA7MDAwMDAwMDA7MDAwMDAwMDA7MDAwMDAwMDAw
MDAwMDAyMDtjb20uYXBwbGUuYXBwLXNhbmRib3gucmVhZC13cml0ZTswMTswMTAwMDAw
ZDswMDAwMDAwMDAwMDk4ZDkwOzAxOy91c2Vycy9tYXhpbWUvbXVzaWMvbXVzaWMvbWVk
aWEubG9jYWxpemVkAADMAAAA/v///wEAAAAAAAAAEAAAAAQQAABMAAAAAAAAAAUQAAC4
AAAAAAAAABAQAADkAAAAAAAAAEAQAADUAAAAAAAAAAIgAACwAQAAAAAAAAUgAAAgAQAA
AAAAABAgAAAwAQAAAAAAABEgAABkAQAAAAAAABIgAABEAQAAAAAAABMgAABUAQAAAAAA
ACAgAACQAQAAAAAAADAgAAC8AQAAAAAAAAHAAAAEAQAAAAAAABHAAAAUAAAAAAAAABLA
AAAUAQAAAAAAAIDwAADEAQAAAAAAAA==
</data>
'
defaults write com.apple.Music "preloadFilesIntoMemory" -boolean false
defaults write com.apple.Music "refreshedHLSKeysTime" -integer 3716101873
defaults write com.apple.Music "rprf:0000000000000000" '
<data>
cnNwZj+AAAA/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
</data>
'
defaults write com.apple.Music "rspl:1:AirTunes Speaker List" '
<data>
PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPCFET0NUWVBFIHBs
aXN0IFBVQkxJQyAiLS8vQXBwbGUvL0RURCBQTElTVCAxLjAvL0VOIiAiaHR0cDovL3d3
dy5hcHBsZS5jb20vRFREcy9Qcm9wZXJ0eUxpc3QtMS4wLmR0ZCI+CjxwbGlzdCB2ZXJz
aW9uPSIxLjAiPgo8YXJyYXk+Cgk8ZGljdD4KCQk8a2V5PkFWRGV2aWNlVHlwZTwva2V5
PgoJCTxzdHJpbmc+VGhpcyBDb21wdXRlcjwvc3RyaW5nPgoJCTxrZXk+Q2x1c3RlckRl
dmljZVR5cGU8L2tleT4KCQk8aW50ZWdlcj4wPC9pbnRlZ2VyPgoJCTxrZXk+RGV2aWNl
SUQ8L2tleT4KCQk8aW50ZWdlcj4wPC9pbnRlZ2VyPgoJCTxrZXk+RGV2aWNlTW9kZWw8
L2tleT4KCQk8c3RyaW5nPjwvc3RyaW5nPgoJCTxrZXk+RGV2aWNlTmFtZTwva2V5PgoJ
CTxzdHJpbmc+TWF4aW1l4oCZcyBNYWMgbWluaTwvc3RyaW5nPgoJCTxrZXk+RGV2aWNl
VHlwZTwva2V5PgoJCTxpbnRlZ2VyPjE8L2ludGVnZXI+CgkJPGtleT5Mb2dpY2FsRGV2
aWNlSUQ8L2tleT4KCQk8c3RyaW5nPjwvc3RyaW5nPgoJCTxrZXk+U3VwcG9ydGVkVHlw
ZXM8L2tleT4KCQk8aW50ZWdlcj42PC9pbnRlZ2VyPgoJPC9kaWN0Pgo8L2FycmF5Pgo8
L3BsaXN0Pgo=
</data>
'
defaults write com.apple.Music "showWelcomeScreenState" -integer 2
defaults write com.apple.Music "sidebarItemInfo" '
<dict>
	<key>selected</key>
	<dict>
		<key>group</key>
		<integer>1</integer>
		<key>id</key>
		<integer>301</integer>
	</dict>
</dict>
'
defaults write com.apple.Music "storeBrowseColumns" '
<dict>
	<key>Columns.columnInfo</key>
	<array>
		<dict>
			<key>ColumnInfo.moveable</key>
			<true/>
			<key>ColumnInfo.resizable</key>
			<true/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<true/>
			<key>ColumnInfo.trackField</key>
			<integer>26</integer>
			<key>ColumnInfo.width</key>
			<integer>115</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
	</array>
	<key>Columns.numColumns</key>
	<integer>1</integer>
	<key>Columns.sortColumnIndex</key>
	<integer>0</integer>
</dict>
'
defaults write com.apple.Music "storeMediaTypeFlags" -integer 3422
defaults write com.apple.Music "storePublishedPlaylistColumns" '
<dict>
	<key>Columns.columnInfo</key>
	<array>
		<dict>
			<key>ColumnInfo.moveable</key>
			<true/>
			<key>ColumnInfo.resizable</key>
			<true/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<true/>
			<key>ColumnInfo.trackField</key>
			<integer>26</integer>
			<key>ColumnInfo.width</key>
			<integer>115</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
		<dict>
			<key>ColumnInfo.moveable</key>
			<false/>
			<key>ColumnInfo.resizable</key>
			<false/>
			<key>ColumnInfo.reverseSort</key>
			<false/>
			<key>ColumnInfo.sortable</key>
			<false/>
			<key>ColumnInfo.trackField</key>
			<integer>0</integer>
		</dict>
	</array>
	<key>Columns.numColumns</key>
	<integer>1</integer>
	<key>Columns.sortColumnIndex</key>
	<integer>0</integer>
</dict>
'
defaults write com.apple.Music "storeSupportsCloudPurchases" -integer 1
defaults write com.apple.Music "storeSupportsPasswordSettings" -boolean true
defaults write com.apple.Music "storeSupportsPreviousPurchases" -boolean true
defaults write com.apple.Music "storeSupportsUPP" -boolean true
defaults write com.apple.Music "userMaxConcurrentDownloads" -integer 3
