#!/usr/bin/env bash

defaults write com.apple.print.custompresets.forprinter.Canon_Pixma_TS8300 "com.apple.print.lastPresetPref" -string 'Default Settings'
defaults write com.apple.print.custompresets.forprinter.Canon_Pixma_TS8300 "com.apple.print.lastPresetPrefType" -integer 1
defaults write com.apple.print.custompresets.forprinter.Canon_Pixma_TS8300 "com.apple.print.lastUsedSettingsPref" '
<dict>
	<key>com.apple.print.preset.id</key>
	<string>com.apple.print.lastUsedSettingsPref</string>
	<key>com.apple.print.preset.settings</key>
	<dict>
		<key>BookletBinding</key>
		<false/>
		<key>BookletType</key>
		<integer>0</integer>
		<key>ColorModel</key>
		<string>Gray</string>
		<key>InputSlot</key>
		<string>rear</string>
		<key>MediaType</key>
		<string>stationery</string>
		<key>PaperInfoIsSuggested</key>
		<true/>
		<key>com.apple.print.DialogDismissedBy</key>
		<string>Print</string>
		<key>com.apple.print.PDEsUsed</key>
		<string> com.apple.print.pde.MediaQualityPDEKind, com.apple.print.pde.NSPrintAccessoryViewPDE,</string>
		<key>com.apple.print.PMPresetUsed</key>
		<string>Default Settings</string>
		<key>com.apple.print.PageToPaperMappingMediaName</key>
		<string>A4.Fullbleed</string>
		<key>com.apple.print.PageToPaperMappingType</key>
		<integer>1</integer>
		<key>com.apple.print.PrintSettings.PMCopies</key>
		<integer>1</integer>
		<key>com.apple.print.PrintSettings.PMCopyCollate</key>
		<true/>
		<key>com.apple.print.PrintSettings.PMDestinationType</key>
		<integer>1</integer>
		<key>com.apple.print.PrintSettings.PMDuplexing</key>
		<integer>1</integer>
		<key>com.apple.print.PrintSettings.PMFirstPage</key>
		<integer>1</integer>
		<key>com.apple.print.PrintSettings.PMLastPage</key>
		<integer>2147483647</integer>
		<key>com.apple.print.PrintSettings.PMPageRange</key>
		<array>
			<integer>1</integer>
			<integer>2147483647</integer>
		</array>
		<key>com.apple.print.preset.Orientation</key>
		<integer>1</integer>
		<key>com.apple.print.preset.PaperInfo</key>
		<dict>
			<key>paperInfo</key>
			<dict>
				<key>PMPPDPaperCodeName</key>
				<string>A4.Fullbleed</string>
				<key>PMPPDTranslationStringPaperName</key>
				<string>A4.Fullbleed</string>
				<key>PMTiogaPaperName</key>
				<string>iso-a4-fullbleed</string>
				<key>com.apple.print.PageFormat.PMAdjustedPageRect</key>
				<array>
					<integer>0</integer>
					<integer>0</integer>
					<real>841.782887656561</real>
					<real>595.20000000000005</real>
				</array>
				<key>com.apple.print.PageFormat.PMAdjustedPaperRect</key>
				<array>
					<integer>0</integer>
					<integer>0</integer>
					<real>841.782887656561</real>
					<real>595.20000000000005</real>
				</array>
				<key>com.apple.print.PaperInfo.PMCustomPaper</key>
				<false/>
				<key>com.apple.print.PaperInfo.PMPaperName</key>
				<string>iso-a4-fullbleed</string>
				<key>com.apple.print.PaperInfo.PMUnadjustedPageRect</key>
				<array>
					<integer>0</integer>
					<integer>0</integer>
					<real>841.8897705078125</real>
					<real>595.27557373046875</real>
				</array>
				<key>com.apple.print.PaperInfo.PMUnadjustedPaperRect</key>
				<array>
					<integer>0</integer>
					<integer>0</integer>
					<real>841.8897705078125</real>
					<real>595.27557373046875</real>
				</array>
				<key>com.apple.print.PaperInfo.ppd.PMPaperName</key>
				<string>A4.Fullbleed</string>
				<key>com.apple.print.ticket.type</key>
				<string>com.apple.print.PaperInfoTicket</string>
			</dict>
		</dict>
		<key>com.apple.print.preset.ReverseOrient</key>
		<false/>
		<key>com.apple.print.subTicket.paper_info_ticket</key>
		<dict>
			<key>PMPPDPaperCodeName</key>
			<string>A4.Fullbleed</string>
			<key>PMPPDTranslationStringPaperName</key>
			<string>A4.Fullbleed</string>
			<key>PMTiogaPaperName</key>
			<string>iso-a4-fullbleed</string>
			<key>com.apple.print.PaperInfo.PMDisplayName</key>
			<string>iso-a4-fullbleed</string>
			<key>com.apple.print.PaperInfo.PMPPDPaperDimension</key>
			<array>
				<integer>0</integer>
				<integer>0</integer>
				<real>595.27557373046875</real>
				<real>841.8897705078125</real>
			</array>
			<key>com.apple.print.PaperInfo.PMPaperName</key>
			<string>iso-a4-fullbleed</string>
			<key>com.apple.print.PaperInfo.PMUnadjustedPageRect</key>
			<array>
				<integer>0</integer>
				<integer>0</integer>
				<real>841.8897705078125</real>
				<real>595.27557373046875</real>
			</array>
			<key>com.apple.print.PaperInfo.PMUnadjustedPaperRect</key>
			<array>
				<integer>0</integer>
				<integer>0</integer>
				<real>841.8897705078125</real>
				<real>595.27557373046875</real>
			</array>
			<key>com.apple.print.PaperInfo.ppd.PMPaperName</key>
			<string>A4.Fullbleed</string>
			<key>com.apple.print.ticket.type</key>
			<string>com.apple.print.PaperInfoTicket</string>
		</dict>
		<key>com.apple.print.ticket.type</key>
		<string>com.apple.print.PrintSettingsTicket</string>
		<key>com.apple.print.totalPages</key>
		<integer>1</integer>
		<key>cupsPrintQuality</key>
		<string>Draft</string>
	</dict>
</dict>
'
