#!/usr/bin/env bash

defaults -currentHost write com.apple.windowserver.displays "DisplaySets" '
<dict>
	<key>Configs</key>
	<array>
		<array>
			<dict>
				<key>CurrentInfo</key>
				<dict>
					<key>Depth</key>
					<integer>8</integer>
					<key>High</key>
					<real>1440</real>
					<key>Hz</key>
					<real>60</real>
					<key>IsLink</key>
					<false/>
					<key>OriginX</key>
					<real>0.0</real>
					<key>OriginY</key>
					<real>0.0</real>
					<key>Rotation</key>
					<integer>0</integer>
					<key>Scale</key>
					<real>1</real>
					<key>Wide</key>
					<real>2560</real>
				</dict>
				<key>Rotation</key>
				<real>0.0</real>
				<key>UUID</key>
				<string>794CE067-6D91-920E-3D19-FC1626C9B248</string>
				<key>UnmirrorInfo</key>
				<dict>
					<key>Depth</key>
					<integer>8</integer>
					<key>High</key>
					<real>1440</real>
					<key>Hz</key>
					<real>60</real>
					<key>IsLink</key>
					<false/>
					<key>OriginX</key>
					<real>0.0</real>
					<key>OriginY</key>
					<real>0.0</real>
					<key>Rotation</key>
					<integer>0</integer>
					<key>Scale</key>
					<real>1</real>
					<key>Wide</key>
					<real>2560</real>
				</dict>
			</dict>
			<dict>
				<key>CurrentInfo</key>
				<dict>
					<key>Depth</key>
					<integer>8</integer>
					<key>High</key>
					<real>1440</real>
					<key>Hz</key>
					<real>60</real>
					<key>IsLink</key>
					<false/>
					<key>OriginX</key>
					<real>2560</real>
					<key>OriginY</key>
					<real>0.0</real>
					<key>Rotation</key>
					<integer>0</integer>
					<key>Scale</key>
					<real>1</real>
					<key>Wide</key>
					<real>2560</real>
				</dict>
				<key>Rotation</key>
				<real>0.0</real>
				<key>UUID</key>
				<string>4B08E384-B118-3977-0857-D6964E3302DB</string>
				<key>UnmirrorInfo</key>
				<dict>
					<key>Depth</key>
					<integer>4</integer>
					<key>High</key>
					<real>1</real>
					<key>Hz</key>
					<real>60</real>
					<key>IsLink</key>
					<false/>
					<key>OriginX</key>
					<real>0.0</real>
					<key>OriginY</key>
					<real>0.0</real>
					<key>Rotation</key>
					<integer>0</integer>
					<key>Scale</key>
					<real>1</real>
					<key>Wide</key>
					<real>1</real>
				</dict>
			</dict>
		</array>
		<array>
			<dict>
				<key>CurrentInfo</key>
				<dict>
					<key>Depth</key>
					<integer>8</integer>
					<key>High</key>
					<real>1080</real>
					<key>Hz</key>
					<real>60</real>
					<key>IsLink</key>
					<false/>
					<key>OriginX</key>
					<real>2560</real>
					<key>OriginY</key>
					<real>250</real>
					<key>Rotation</key>
					<integer>0</integer>
					<key>Scale</key>
					<real>1</real>
					<key>Wide</key>
					<real>1920</real>
				</dict>
				<key>Rotation</key>
				<real>0.0</real>
				<key>UUID</key>
				<string>2D50045A-FE30-37D7-3D19-FC1626C9B248</string>
				<key>UnmirrorInfo</key>
				<dict>
					<key>Depth</key>
					<integer>8</integer>
					<key>High</key>
					<real>1080</real>
					<key>Hz</key>
					<real>60</real>
					<key>IsLink</key>
					<false/>
					<key>OriginX</key>
					<real>0.0</real>
					<key>OriginY</key>
					<real>0.0</real>
					<key>Rotation</key>
					<integer>0</integer>
					<key>Scale</key>
					<real>1</real>
					<key>Wide</key>
					<real>1920</real>
				</dict>
			</dict>
			<dict>
				<key>CurrentInfo</key>
				<dict>
					<key>Depth</key>
					<integer>8</integer>
					<key>High</key>
					<real>1440</real>
					<key>Hz</key>
					<real>60</real>
					<key>IsLink</key>
					<false/>
					<key>OriginX</key>
					<real>0.0</real>
					<key>OriginY</key>
					<real>0.0</real>
					<key>Rotation</key>
					<integer>0</integer>
					<key>Scale</key>
					<real>1</real>
					<key>Wide</key>
					<real>2560</real>
				</dict>
				<key>Rotation</key>
				<real>0.0</real>
				<key>UUID</key>
				<string>4B08E384-B118-3977-0857-D6964E3302DB</string>
				<key>UnmirrorInfo</key>
				<dict>
					<key>Depth</key>
					<integer>4</integer>
					<key>High</key>
					<real>1</real>
					<key>Hz</key>
					<real>60</real>
					<key>IsLink</key>
					<false/>
					<key>OriginX</key>
					<real>0.0</real>
					<key>OriginY</key>
					<real>0.0</real>
					<key>Rotation</key>
					<integer>0</integer>
					<key>Scale</key>
					<real>1</real>
					<key>Wide</key>
					<real>1</real>
				</dict>
			</dict>
		</array>
		<array>
			<dict>
				<key>CurrentInfo</key>
				<dict>
					<key>Depth</key>
					<integer>8</integer>
					<key>High</key>
					<real>1440</real>
					<key>Hz</key>
					<real>60</real>
					<key>IsLink</key>
					<false/>
					<key>OriginX</key>
					<real>0.0</real>
					<key>OriginY</key>
					<real>0.0</real>
					<key>Rotation</key>
					<integer>0</integer>
					<key>Scale</key>
					<real>1</real>
					<key>Wide</key>
					<real>2560</real>
				</dict>
				<key>Rotation</key>
				<real>0.0</real>
				<key>UUID</key>
				<string>794CE067-6D91-920E-3D19-FC1626C9B248</string>
				<key>UnmirrorInfo</key>
				<dict>
					<key>Depth</key>
					<integer>8</integer>
					<key>High</key>
					<real>1440</real>
					<key>Hz</key>
					<real>60</real>
					<key>IsLink</key>
					<false/>
					<key>OriginX</key>
					<real>0.0</real>
					<key>OriginY</key>
					<real>0.0</real>
					<key>Rotation</key>
					<integer>0</integer>
					<key>Scale</key>
					<real>1</real>
					<key>Wide</key>
					<real>2560</real>
				</dict>
			</dict>
		</array>
	</array>
	<key>Orientations</key>
	<dict>
		<key>2D50045A-FE30-37D7-3D19-FC1626C9B248</key>
		<integer>0</integer>
		<key>4B08E384-B118-3977-0857-D6964E3302DB</key>
		<integer>0</integer>
		<key>794CE067-6D91-920E-3D19-FC1626C9B248</key>
		<integer>0</integer>
	</dict>
	<key>Underscan</key>
	<dict>
		<key>2D50045A-FE30-37D7-3D19-FC1626C9B248</key>
		<real>1</real>
		<key>4B08E384-B118-3977-0857-D6964E3302DB</key>
		<real>1</real>
		<key>794CE067-6D91-920E-3D19-FC1626C9B248</key>
		<real>1</real>
	</dict>
	<key>Version</key>
	<integer>1</integer>
</dict>
'
defaults -currentHost write com.apple.windowserver.displays "account" -integer 644
defaults -currentHost write com.apple.windowserver.displays "last_mode" -string 'per-display'
