#!/usr/bin/env bash

defaults write com.apple.spaces "SpacesDisplayConfiguration" '
<dict>
	<key>Management Data</key>
	<dict>
		<key>Age</key>
		<real>48103.26604304168</real>
		<key>Management Mode</key>
		<integer>1</integer>
		<key>Monitors</key>
		<array>
			<dict>
				<key>Current Space</key>
				<dict>
					<key>ManagedSpaceID</key>
					<integer>1</integer>
					<key>id64</key>
					<integer>1</integer>
					<key>type</key>
					<integer>0</integer>
					<key>uuid</key>
					<string></string>
					<key>wsid</key>
					<integer>1</integer>
				</dict>
				<key>Display Identifier</key>
				<string>Main</string>
				<key>Spaces</key>
				<array>
					<dict>
						<key>ManagedSpaceID</key>
						<integer>1</integer>
						<key>id64</key>
						<integer>1</integer>
						<key>type</key>
						<integer>0</integer>
						<key>uuid</key>
						<string></string>
						<key>wsid</key>
						<integer>1</integer>
					</dict>
				</array>
			</dict>
			<dict>
				<key>Current Space</key>
				<dict>
					<key>ManagedSpaceID</key>
					<integer>32</integer>
					<key>id64</key>
					<integer>32</integer>
					<key>type</key>
					<integer>0</integer>
					<key>uuid</key>
					<string>91544590-7409-45C1-86A8-3488D2E31637</string>
				</dict>
				<key>Display Identifier</key>
				<string>4B08E384-B118-3977-0857-D6964E3302DB</string>
				<key>Spaces</key>
				<array>
					<dict>
						<key>ManagedSpaceID</key>
						<integer>32</integer>
						<key>id64</key>
						<integer>32</integer>
						<key>type</key>
						<integer>0</integer>
						<key>uuid</key>
						<string>91544590-7409-45C1-86A8-3488D2E31637</string>
					</dict>
				</array>
			</dict>
		</array>
		<key>Primary</key>
		<dict>
			<key>CreatedCount</key>
			<integer>9</integer>
			<key>DeletedCount</key>
			<integer>6</integer>
			<key>LifetimeEntryCount</key>
			<integer>6</integer>
			<key>LifetimeMax</key>
			<real>1346.6061325000003</real>
			<key>LifetimeMin</key>
			<real>6.4860275416667719</real>
			<key>LifetimeSum</key>
			<real>3385.0872601250016</real>
			<key>PersistedCount</key>
			<integer>0</integer>
		</dict>
		<key>Secondary</key>
		<dict>
			<key>CreatedCount</key>
			<integer>2</integer>
			<key>DeletedCount</key>
			<integer>2</integer>
			<key>LifetimeEntryCount</key>
			<integer>2</integer>
			<key>LifetimeMax</key>
			<real>1.4232596666666666</real>
			<key>LifetimeMin</key>
			<real>0.56073258333344711</real>
			<key>LifetimeSum</key>
			<real>1.9839922500001137</real>
			<key>PersistedCount</key>
			<integer>0</integer>
		</dict>
	</dict>
	<key>Space Properties</key>
	<array>
		<dict>
			<key>name</key>
			<string></string>
			<key>windows</key>
			<array>
				<integer>402</integer>
				<integer>393</integer>
				<integer>35</integer>
				<integer>15</integer>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>91544590-7409-45C1-86A8-3488D2E31637</string>
			<key>windows</key>
			<array>
				<integer>335</integer>
				<integer>334</integer>
			</array>
		</dict>
	</array>
</dict>
'
