#!/usr/bin/env bash

defaults write com.apple.ncprefs "apps" '
<array>
	<dict>
		<key>bundle-id</key>
		<string>com.apple.iCal</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>41951254</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Applications/Calendar.app</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADQAAAABAAAABgAAAAIAAAAXY29t
				LmFwcGxlLkNhbGVuZGFyQWdlbnQAAAAAAw==
				</data>
				<key>uuid</key>
				<string>4B69E1CA-81F9-42CA-9BAE-03ACB55CA958</string>
			</dict>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAAEgAAAABAAAABgAAAAIAAAArY29t
				LmFwcGxlLkNhbGVuZGFyTm90aWZpY2F0aW9u
				LkNhbE5DU2VydmljZQAAAAAD
				</data>
				<key>uuid</key>
				<string>7023FBAB-DD59-4CAB-B70D-D142A2ED29D3</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>bundle-id</key>
		<string>com.apple.FaceTime</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>41951246</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Applications/FaceTime.app</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADgAAAABAAAABgAAAAIAAAAcY29t
				LmFwcGxlLlRlbGVwaG9ueVV0aWxpdGllcwAA
				AAM=
				</data>
				<key>uuid</key>
				<string>915363FA-6C8B-45BD-8163-4D2823F3A522</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>bundle-id</key>
		<string>com.apple.mail</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>41943054</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Applications/Mail.app</string>
	</dict>
	<dict>
		<key>auth</key>
		<integer>775</integer>
		<key>bundle-id</key>
		<string>com.apple.MobileSMS</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>864550926</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Applications/Messages.app</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADAAAAABAAAABgAAAAIAAAARY29t
				LmFwcGxlLmltYWdlbnQAAAAAAAAD
				</data>
				<key>uuid</key>
				<string>AC86D7C9-553E-4692-B3B2-681F198D6038</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>271</integer>
		<key>bundle-id</key>
		<string>com.apple.reminders</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>864550934</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Library/UserNotifications/Bundles/com.apple.reminders.bundle</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADAAAAABAAAABgAAAAIAAAARY29t
				LmFwcGxlLnJlbWluZGQAAAAAAAAD
				</data>
				<key>uuid</key>
				<string>D0986F11-B152-468B-A69A-4FF57E68CD0E</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>bundle-id</key>
		<string>com.apple.Safari</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>41951246</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/Applications/Safari.app</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>2</integer>
				<key>path</key>
				<string>/Applications/Safari.app</string>
				<key>req</key>
				<data>
				+t4MAAAAACwAAAABAAAABgAAAAIAAAAQY29t
				LmFwcGxlLlNhZmFyaQAAAAM=
				</data>
				<key>uuid</key>
				<string>367DE047-744C-4A2C-8952-ADC2DB52908C</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>bundle-id</key>
		<string>_SYSTEM_CENTER_:com.apple.migrationhelper</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>41943575</integer>
		<key>grouping</key>
		<integer>0</integer>
	</dict>
	<dict>
		<key>bundle-id</key>
		<string>_SYSTEM_CENTER_:com.apple.accountsd</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>41943575</integer>
		<key>grouping</key>
		<integer>0</integer>
	</dict>
	<dict>
		<key>bundle-id</key>
		<string>_SYSTEM_CENTER_:com.apple.mdmclient</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>41943575</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADAAAAABAAAABgAAAAIAAAATY29t
				LmFwcGxlLm1kbWNsaWVudAAAAAAD
				</data>
				<key>uuid</key>
				<string>B3275716-1ED3-4D35-823A-805E52F14B67</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>bundle-id</key>
		<string>_SYSTEM_CENTER_:com.apple.storeassetd</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>41943575</integer>
		<key>grouping</key>
		<integer>0</integer>
	</dict>
	<dict>
		<key>bundle-id</key>
		<string>_SYSTEM_CENTER_:com.apple.TMHelperAgent</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>41943575</integer>
		<key>grouping</key>
		<integer>0</integer>
	</dict>
	<dict>
		<key>auth</key>
		<integer>262</integer>
		<key>bundle-id</key>
		<string>com.apple.ScreenTimeNotifications</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>864550924</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Library/UserNotifications/Bundles/com.apple.ScreenTimeNotifications.bundle</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADgAAAABAAAABgAAAAIAAAAZY29t
				LmFwcGxlLlNjcmVlblRpbWVBZ2VudAAAAAAA
				AAM=
				</data>
				<key>uuid</key>
				<string>DF3D717E-08A1-4EE1-8FA0-23D4F587B7BF</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>bundle-id</key>
		<string>_SYSTEM_CENTER_:com.apple.appstoreagent</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>41943703</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADAAAAABAAAABgAAAAIAAAATY29t
				LmFwcGxlLmFjY291bnRzZAAAAAAD
				</data>
				<key>uuid</key>
				<string>DD992B70-76C8-4177-8A79-6C03D2B4294E</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>263</integer>
		<key>bundle-id</key>
		<string>com.apple.gamecenter</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>864559118</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Library/UserNotifications/Bundles/com.apple.gamecenter.bundle</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAACwAAAABAAAABgAAAAIAAAAPY29t
				LmFwcGxlLmdhbWVkAAAAAAM=
				</data>
				<key>uuid</key>
				<string>5B2EAAAF-B85A-4ECD-92F0-60D017FE2634</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>6</integer>
		<key>bundle-id</key>
		<string>com.apple.ScreenTimeEnabledNotifications</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>327680148</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Library/UserNotifications/Bundles/com.apple.ScreenTimeEnabledNotifications.bundle</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADgAAAABAAAABgAAAAIAAAAZY29t
				LmFwcGxlLlNjcmVlblRpbWVBZ2VudAAAAAAA
				AAM=
				</data>
				<key>uuid</key>
				<string>811B9007-E1A9-4B20-B726-8F00803A3C5A</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>bundle-id</key>
		<string>_SYSTEM_CENTER_:com.apple.askpermissiond</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>41943575</integer>
		<key>grouping</key>
		<integer>0</integer>
	</dict>
	<dict>
		<key>bundle-id</key>
		<string>_SYSTEM_CENTER_:com.apple.BluetoothUIServer</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>41943575</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADgAAAABAAAABgAAAAIAAAAbY29t
				LmFwcGxlLkJsdWV0b290aFVJU2VydmVyAAAA
				AAM=
				</data>
				<key>uuid</key>
				<string>B77674A8-2054-4D5E-B7BF-971D13097CA0</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>bundle-id</key>
		<string>_SYSTEM_CENTER_:com.apple.followup.alert</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>41943703</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADAAAAABAAAABgAAAAIAAAATY29t
				LmFwcGxlLmZvbGxvd3VwZAAAAAAD
				</data>
				<key>uuid</key>
				<string>903200D5-6AF1-4355-A208-2BCA758BC4EB</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>bundle-id</key>
		<string>_SYSTEM_CENTER_:com.apple.CalendarNotification.CalNCService</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>41943575</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAAEgAAAABAAAABgAAAAIAAAArY29t
				LmFwcGxlLkNhbGVuZGFyTm90aWZpY2F0aW9u
				LkNhbE5DU2VydmljZQAAAAAD
				</data>
				<key>uuid</key>
				<string>E54E88CE-34D2-4BFB-879D-393145F37E71</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>311</integer>
		<key>bundle-id</key>
		<string>com.apple.Home</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>864550926</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Library/UserNotifications/Bundles/com.apple.Home.bundle</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAACwAAAABAAAABgAAAAIAAAAPY29t
				LmFwcGxlLmhvbWVkAAAAAAM=
				</data>
				<key>uuid</key>
				<string>9294373B-F379-44C9-9231-76AD13443387</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>bundle-id</key>
		<string>_SYSTEM_CENTER_:com.apple.security.keychain-circle-notification</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>41943575</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAAEwAAAABAAAABgAAAAIAAAAvY29t
				LmFwcGxlLnNlY3VyaXR5LktleWNoYWluLUNp
				cmNsZS1Ob3RpZmljYXRpb24AAAAAAw==
				</data>
				<key>uuid</key>
				<string>876D070B-DCD1-4D55-92CC-601642FD5B6B</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>4</integer>
		<key>bundle-id</key>
		<string>_SYSTEM_CENTER_:com.apple.wifi.usernotifications.autohotspot</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>327680662</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADQAAAABAAAABgAAAAIAAAAYY29t
				LmFwcGxlLndpZmkuV2lGaUFnZW50AAAAAw==
				</data>
				<key>uuid</key>
				<string>0AA6CDEA-D171-42CF-BBB5-F325195BF023</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>4</integer>
		<key>bundle-id</key>
		<string>_SYSTEM_CENTER_:com.apple.wifi.usernotifications.diagnostics</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>327680662</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADQAAAABAAAABgAAAAIAAAAYY29t
				LmFwcGxlLndpZmkuV2lGaUFnZW50AAAAAw==
				</data>
				<key>uuid</key>
				<string>78549FB2-0529-4044-BB9E-9DD671D56935</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>7</integer>
		<key>bundle-id</key>
		<string>_SYSTEM_CENTER_:com.apple.SoftwareUpdateNotification</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>327688855</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAAEgAAAABAAAABgAAAAIAAAArY29t
				LmFwcGxlLlNvZnR3YXJlVXBkYXRlTm90aWZp
				Y2F0aW9uTWFuYWdlcgAAAAAD
				</data>
				<key>uuid</key>
				<string>E23917C5-E406-4BCB-87BE-22F2CBCBE99F</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>263</integer>
		<key>bundle-id</key>
		<string>com.apple.AppStore.notifications</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>864551062</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Library/UserNotifications/Bundles/com.apple.AppStore.notifications.bundle</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADQAAAABAAAABgAAAAIAAAAXY29t
				LmFwcGxlLmFwcHN0b3JlYWdlbnQAAAAAAw==
				</data>
				<key>uuid</key>
				<string>46A3DD58-FE99-48D5-84C8-B265F5A60E93</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>0</integer>
		<key>bundle-id</key>
		<string>com.apple.AppStore</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>276832270</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Applications/App Store.app</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADQAAAABAAAABgAAAAIAAAAXY29t
				LmFwcGxlLmFwcHN0b3JlYWdlbnQAAAAAAw==
				</data>
				<key>uuid</key>
				<string>EF780697-B95C-4786-B820-5BE85C0D711E</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>4</integer>
		<key>bundle-id</key>
		<string>com.apple.TrySafari</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>327684246</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Library/UserNotifications/Bundles/com.apple.TrySafari.bundle</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADwAAAABAAAABgAAAAIAAAAeY29t
				LmFwcGxlLmNvcmVzZXJ2aWNlcy51aWFnZW50
				AAAAAAAD
				</data>
				<key>uuid</key>
				<string>67F85CA8-263C-4B14-A3F3-AE95C23E46B4</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>bundle-id</key>
		<string>_SYSTEM_CENTER_:com.apple.sharingd</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>41943575</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADAAAAABAAAABgAAAAIAAAASY29t
				LmFwcGxlLnNoYXJpbmdkAAAAAAAD
				</data>
				<key>uuid</key>
				<string>6F50A8BF-2C65-40ED-82DE-EB91C4B6B145</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>bundle-id</key>
		<string>_SYSTEM_CENTER_:com.apple.FaceTime</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>41943575</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADgAAAABAAAABgAAAAIAAAAcY29t
				LmFwcGxlLlRlbGVwaG9ueVV0aWxpdGllcwAA
				AAM=
				</data>
				<key>uuid</key>
				<string>23324FC9-576B-4587-A1FE-6052B0EACABA</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>bundle-id</key>
		<string>_SYSTEM_CENTER_:com.apple.sharingd.continuity</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>41943575</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADAAAAABAAAABgAAAAIAAAASY29t
				LmFwcGxlLnNoYXJpbmdkAAAAAAAD
				</data>
				<key>uuid</key>
				<string>541542E7-905C-4834-8FF6-C73B16991E64</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>7</integer>
		<key>bundle-id</key>
		<string>com.apple.Photos</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>310386702</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Applications/Photos.app</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADQAAAABAAAABgAAAAIAAAAXY29t
				LmFwcGxlLnBob3RvbGlicmFyeWQAAAAAAw==
				</data>
				<key>uuid</key>
				<string>9674C688-F2A8-4A93-8DBF-618B23EF2B0B</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>295</integer>
		<key>bundle-id</key>
		<string>com.apple.Passbook</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>864550926</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Library/UserNotifications/Bundles/com.apple.Passbook.bundle</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAACwAAAABAAAABgAAAAIAAAAPY29t
				LmFwcGxlLnBhc3NkAAAAAAM=
				</data>
				<key>uuid</key>
				<string>3F5F2E66-F725-4C0E-804A-2A055AA9EE9D</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>6</integer>
		<key>bundle-id</key>
		<string>com.apple.BTUserNotifications</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>327688342</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Library/UserNotifications/Bundles/com.apple.BTUserNotifications.bundle</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADAAAAABAAAABgAAAAIAAAAUY29t
				LmFwcGxlLmNsb3VkcGFpcmQAAAAD
				</data>
				<key>uuid</key>
				<string>60A62506-11B7-4936-923C-1FBEC5DE9AC3</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>bundle-id</key>
		<string>_SYSTEM_CENTER_:com.apple.MobileAccessoryUpdater.fudHelperAgent</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>41943575</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADQAAAABAAAABgAAAAIAAAAYY29t
				LmFwcGxlLmZ1ZEhlbHBlckFnZW50AAAAAw==
				</data>
				<key>uuid</key>
				<string>3DAD9227-6BD3-48E0-A8D6-DBBBBDC0E9B5</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>0</integer>
		<key>bundle-id</key>
		<string>com.apple.TV</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>268443662</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Applications/TV.app</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADAAAAABAAAABgAAAAIAAAAUY29t
				LmFwcGxlLndhdGNobGlzdGQAAAAD
				</data>
				<key>uuid</key>
				<string>B197467B-9BE0-4F70-978A-07F7670D698E</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>7</integer>
		<key>bundle-id</key>
		<string>com.apple.controlcenter.notifications.low-battery</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>327688342</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Library/UserNotifications/Bundles/com.apple.controlcenter.notifications.low-battery.bundle</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADQAAAABAAAABgAAAAIAAAAXY29t
				LmFwcGxlLmNvbnRyb2xjZW50ZXIAAAAAAw==
				</data>
				<key>uuid</key>
				<string>2D3F784D-D443-4217-8C62-1038C43F0583</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>bundle-id</key>
		<string>com.apple.iBooksX</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>41951246</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Applications/Books.app</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>2</integer>
				<key>path</key>
				<string>/System/Library/PrivateFrameworks/CommerceKit.framework/Versions/A/Resources/commerce</string>
				<key>req</key>
				<data>
				+t4MAAAAADAAAAABAAAABgAAAAIAAAASY29t
				LmFwcGxlLmNvbW1lcmNlAAAAAAAD
				</data>
				<key>uuid</key>
				<string>7A2D3780-70FC-4E52-8B89-AF91F6C1B27D</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>263</integer>
		<key>bundle-id</key>
		<string>com.apple.askpermission.notifications</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>864551062</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Library/UserNotifications/Bundles/com.apple.askpermission.notifications.bundle</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADQAAAABAAAABgAAAAIAAAAYY29t
				LmFwcGxlLmFza3Blcm1pc3Npb25kAAAAAw==
				</data>
				<key>uuid</key>
				<string>E5ECBD6D-0D2D-4389-B119-EA5158B55536</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>7</integer>
		<key>bundle-id</key>
		<string>com.apple.universalcontrol.notifications.displays</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>327688342</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Library/UserNotifications/Bundles/com.apple.universalcontrol.notifications.displays.bundle</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADgAAAABAAAABgAAAAIAAAAaY29t
				LmFwcGxlLnVuaXZlcnNhbGNvbnRyb2wAAAAA
				AAM=
				</data>
				<key>uuid</key>
				<string>0D5BEDB0-CBA6-4D98-81E6-9741A99EB6D2</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>7</integer>
		<key>bundle-id</key>
		<string>com.apple.mdmclient.usernotifications.v2</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>327688342</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Library/UserNotifications/Bundles/com.apple.mdmclient.usernotifications.v2.bundle</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADAAAAABAAAABgAAAAIAAAATY29t
				LmFwcGxlLm1kbWNsaWVudAAAAAAD
				</data>
				<key>uuid</key>
				<string>2B15CCFA-3F78-4825-8D72-75895891FB7F</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>7</integer>
		<key>bundle-id</key>
		<string>com.apple.appleaccount.notifications</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>327680142</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Library/UserNotifications/Bundles/com.apple.appleaccount.notifications.bundle</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADQAAAABAAAABgAAAAIAAAAXY29t
				LmFwcGxlLmFwcGxlYWNjb3VudGQAAAAAAw==
				</data>
				<key>uuid</key>
				<string>C6DF0516-3815-4440-8E13-00CEAE294717</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>4</integer>
		<key>bundle-id</key>
		<string>com.apple.tips</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>327680022</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Library/UserNotifications/Bundles/com.apple.tips.bundle</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAACwAAAABAAAABgAAAAIAAAAPY29t
				LmFwcGxlLnRpcHNkAAAAAAM=
				</data>
				<key>uuid</key>
				<string>6DB41A99-F060-49A2-AC81-3AEA88BEDA35</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>bundle-id</key>
		<string>_SYSTEM_CENTER_:com.apple.USBAgent</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>41943575</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADAAAAABAAAABgAAAAIAAAASY29t
				LmFwcGxlLlVTQkFnZW50AAAAAAAD
				</data>
				<key>uuid</key>
				<string>3A075913-6118-47B7-B2AB-8981B586BBAF</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>4</integer>
		<key>bundle-id</key>
		<string>com.apple.ReplayKitNotifications</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>327688334</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Library/UserNotifications/Bundles/com.apple.ReplayKitNotifications.bundle</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADAAAAABAAAABgAAAAIAAAARY29t
				LmFwcGxlLnJlcGxheWQAAAAAAAAD
				</data>
				<key>uuid</key>
				<string>5EFA6AB8-9815-4FA6-B709-4262B2469ABD</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>bundle-id</key>
		<string>_SYSTEM_CENTER_:com.apple.DiskArbitration.DiskArbitrationAgent</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>41943575</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADwAAAABAAAABgAAAAIAAAAeY29t
				LmFwcGxlLkRpc2tBcmJpdHJhdGlvbkFnZW50
				AAAAAAAD
				</data>
				<key>uuid</key>
				<string>F532556F-3242-4FDF-A8B7-C11587841C61</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>6</integer>
		<key>bundle-id</key>
		<string>com.apple.studentd.notifications</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>327688342</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Library/UserNotifications/Bundles/com.apple.studentd.notifications.bundle</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADAAAAABAAAABgAAAAIAAAASY29t
				LmFwcGxlLnN0dWRlbnRkAAAAAAAD
				</data>
				<key>uuid</key>
				<string>B6E7BCA6-6C48-4341-9B40-FF5369C0396F</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>7</integer>
		<key>bundle-id</key>
		<string>com.apple.Notes</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>310386702</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Applications/Notes.app</string>
		<key>push</key>
		<dict>
			<key>env</key>
			<string>production</string>
			<key>token</key>
			<data>
			</data>
			<key>topic</key>
			<string>com.apple.Notes</string>
			<key>types</key>
			<integer>9223372036854775808</integer>
		</dict>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>2</integer>
				<key>path</key>
				<string>/System/Applications/Notes.app</string>
				<key>req</key>
				<data>
				+t4MAAAAACwAAAABAAAABgAAAAIAAAAPY29t
				LmFwcGxlLk5vdGVzAAAAAAM=
				</data>
				<key>uuid</key>
				<string>B02C9AAB-DE2D-4118-B335-EFF099D3B0BD</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>4</integer>
		<key>bundle-id</key>
		<string>com.apple.Maps</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>327680014</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Applications/Maps.app</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADgAAAABAAAABgAAAAIAAAAZY29t
				LmFwcGxlLk1hcHMucHVzaGRhZW1vbgAAAAAA
				AAM=
				</data>
				<key>uuid</key>
				<string>0D90D286-0355-4AE1-80DC-23A980D5FAAD</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>6</integer>
		<key>bundle-id</key>
		<string>com.apple.shortcuts</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>327680142</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Applications/Shortcuts.app</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADQAAAABAAAABgAAAAIAAAAWY29t
				LmFwcGxlLnNpcmlhY3Rpb25zZAAAAAAAAw==
				</data>
				<key>uuid</key>
				<string>2FCD96A0-9763-4671-97F8-47435D4283B5</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>7</integer>
		<key>bundle-id</key>
		<string>com.apple.AppSSOKerberos.notifications</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>327163926</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Library/UserNotifications/Bundles/com.apple.AppSSOKerberos.notifications.bundle</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADQAAAABAAAABgAAAAIAAAAVY29t
				LmFwcGxlLkFwcFNTT0FnZW50AAAAAAAAAw==
				</data>
				<key>uuid</key>
				<string>7DD35DA7-5ABA-4378-8810-C5CFF32D1F48</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>5</integer>
		<key>bundle-id</key>
		<string>com.apple.Music</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>276832270</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Applications/Music.app</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>2</integer>
				<key>path</key>
				<string>/System/Applications/Music.app</string>
				<key>req</key>
				<data>
				+t4MAAAAACwAAAABAAAABgAAAAIAAAAPY29t
				LmFwcGxlLk11c2ljAAAAAAM=
				</data>
				<key>uuid</key>
				<string>B8271C63-87C7-4BCA-8883-5FBB21954B36</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>0</integer>
		<key>bundle-id</key>
		<string>com.apple.iWork.Pages</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>310386702</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/Applications/Pages.app</string>
		<key>push</key>
		<dict>
			<key>env</key>
			<string>production</string>
			<key>token</key>
			<data>
			</data>
			<key>topic</key>
			<string>com.apple.iWork.Pages</string>
			<key>types</key>
			<integer>9223372036854775808</integer>
		</dict>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>0</integer>
				<key>path</key>
				<string>/Applications/Pages.app</string>
				<key>req</key>
				<data>
				+t4MAAAAAMwAAAABAAAABgAAAAcAAAAGAAAA
				DwAAAA4AAAAAAAAACiqGSIb3Y2QGAQkAAAAA
				AAAAAAAGAAAABgAAAAYAAAAPAAAADgAAAAEA
				AAAKKoZIhvdjZAYCBgAAAAAAAAAAAA4AAAAA
				AAAACiqGSIb3Y2QGAQ0AAAAAAAAAAAALAAAA
				AAAAAApzdWJqZWN0Lk9VAAAAAAABAAAACksz
				NkJLRjdUM0QAAAAAAAIAAAAVY29tLmFwcGxl
				LmlXb3JrLlBhZ2VzAAAA
				</data>
				<key>uuid</key>
				<string>FE414DF8-593E-488A-87C5-C034AF4C7545</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>bundle-id</key>
		<string>com.apple.ScreenSharing</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>41951254</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>path</key>
		<string>/System/Library/CoreServices/Applications/Screen Sharing.app</string>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADgAAAABAAAABgAAAAIAAAAbY29t
				LmFwcGxlLnNzaW52aXRhdGlvbmFnZW50AAAA
				AAM=
				</data>
				<key>uuid</key>
				<string>380D142B-B99C-4A2A-9A5F-7B4D30638054</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>bundle-id</key>
		<string>_SYSTEM_CENTER_:com.apple.ScreenSharing</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>41943575</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADgAAAABAAAABgAAAAIAAAAbY29t
				LmFwcGxlLnNzaW52aXRhdGlvbmFnZW50AAAA
				AAM=
				</data>
				<key>uuid</key>
				<string>A48EAD7B-FF0E-436E-86C3-FA0E548B5541</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>bundle-id</key>
		<string>_SYSTEM_CENTER_:com.apple.EscrowSecurityAlert</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>41943575</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADwAAAABAAAABgAAAAIAAAAdY29t
				LmFwcGxlLkVzY3Jvd1NlY3VyaXR5QWxlcnQA
				AAAAAAAD
				</data>
				<key>uuid</key>
				<string>707A2F56-6788-47E7-825D-BE69303A004A</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>auth</key>
		<integer>6</integer>
		<key>bundle-id</key>
		<string>com.apple.notificationcenter.askpermissions</string>
		<key>content_visibility</key>
		<integer>3</integer>
		<key>flags</key>
		<integer>310383127</integer>
		<key>grouping</key>
		<integer>0</integer>
	</dict>
	<dict>
		<key>bundle-id</key>
		<string>com.apple.iChat</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>41943054</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADgAAAABAAAABgAAAAIAAAAbY29t
				LmFwcGxlLmlkZW50aXR5c2VydmljZXNkAAAA
				AAM=
				</data>
				<key>uuid</key>
				<string>ED9AEA75-B837-46CD-A068-28364B1BD109</string>
			</dict>
		</array>
	</dict>
	<dict>
		<key>bundle-id</key>
		<string>com.apple.TelephonyUtilities</string>
		<key>content_visibility</key>
		<integer>0</integer>
		<key>flags</key>
		<integer>41951246</integer>
		<key>grouping</key>
		<integer>0</integer>
		<key>src</key>
		<array>
			<dict>
				<key>flags</key>
				<integer>6</integer>
				<key>req</key>
				<data>
				+t4MAAAAADAAAAABAAAABgAAAAIAAAARY29t
				LmFwcGxlLmltYWdlbnQAAAAAAAAD
				</data>
				<key>uuid</key>
				<string>23EABC7C-FC58-42CE-94D9-5FB27E571596</string>
			</dict>
		</array>
	</dict>
</array>
'
defaults write com.apple.ncprefs "content_visibility" -integer 2
defaults write com.apple.ncprefs "dnd_prefs" '
<data>
YnBsaXN0MDDVAQIDBAUGBggICFtkbmRNaXJyb3JlZF8QD2RuZERpc3BsYXlTbGVlcF8Q
HnJlcGVhdGVkRmFjZXRpbWVDYWxsc0JyZWFrc0RORF5kbmREaXNwbGF5TG9ja18QE2Zh
Y2V0aW1lQ2FuQnJlYWtETkQJCQgICAgTHzFSYXd4eXp7AAAAAAAAAQEAAAAAAAAACwAA
AAAAAAAAAAAAAAAAAHw=
</data>
'
defaults write com.apple.ncprefs "sort_order" -integer 0
defaults write com.apple.ncprefs "version" -integer 1
