#!/usr/bin/env bash

defaults write com.apple.dock "autohide" -boolean false
defaults write com.apple.dock "largesize" -float 128
defaults write com.apple.dock "last-analytics-stamp" '
<array>
	<real>654977849.75198996</real>
</array>
'
defaults write com.apple.dock "lastShowIndicatorTime" -float 654954458.70254302
defaults write com.apple.dock "loc" -string 'en_GB:FR'
defaults write com.apple.dock "mod-count" -integer 19
defaults write com.apple.dock "persistent-apps" '
<array>
	<dict>
		<key>GUID</key>
		<integer>2100041404</integer>
		<key>tile-data</key>
		<dict>
			<key>book</key>
			<data>
			Ym9vaxwCAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAA
			AAAAAAAAAAAAAAAAAAAAPAEAAAQAAAADAwAAAAAAIAwA
			AAABAQAAQXBwbGljYXRpb25zCgAAAAEBAABTYWZhcmku
			YXBwAAAIAAAAAQYAABAAAAAkAAAACAAAAAQDAAAwLgkA
			AAAAAAgAAAAEAwAAMi4JAAAAAAAIAAAAAQYAAEgAAABY
			AAAACAAAAAAEAABBw372ZIAAABgAAAABAgAAAgAAAAAA
			AAAPAAAAAAAAAAAAAAAAAAAACAAAAAEJAABmaWxlOi8v
			LwoAAAABAQAAbWFjT1MgLSBIRAAACAAAAAQDAAAAAIcR
			OQAAACQAAAABAQAANzc3QjEyNTMtMTVDMC00RkMxLTk1
			NTUtMEE5MjZFMUNERDc1GAAAAAECAACBAAAAAQAAAO8T
			AAABAAAAAAAAAAAAAAABAAAAAQEAAC8AAAAAAAAAAQUA
			AKgAAAD+////AQAAAAAAAAANAAAABBAAADgAAAAAAAAA
			BRAAAGgAAAAAAAAAEBAAAIgAAAAAAAAAQBAAAHgAAAAA
			AAAAAiAAACgBAAAAAAAABSAAAKgAAAAAAAAAECAAALgA
			AAAAAAAAESAAANwAAAAAAAAAEiAAAMwAAAAAAAAAEyAA
			AHgAAAAAAAAAICAAAAgBAAAAAAAAMCAAADQBAAAAAAAA
			ENAAAAQAAAAAAAAA
			</data>
			<key>bundle-identifier</key>
			<string>com.apple.Safari</string>
			<key>dock-extra</key>
			<false/>
			<key>file-data</key>
			<dict>
				<key>_CFURLString</key>
				<string>file:///Applications/Safari.app/</string>
				<key>_CFURLStringType</key>
				<integer>15</integer>
			</dict>
			<key>file-label</key>
			<string>Safari</string>
			<key>file-mod-date</key>
			<integer>3715327433</integer>
			<key>file-type</key>
			<integer>41</integer>
			<key>is-beta</key>
			<false/>
			<key>parent-mod-date</key>
			<integer>32847331042751</integer>
		</dict>
		<key>tile-type</key>
		<string>file-tile</string>
	</dict>
	<dict>
		<key>GUID</key>
		<integer>2100041405</integer>
		<key>tile-data</key>
		<dict>
			<key>book</key>
			<data>
			Ym9va0QCAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAA
			AAAAAAAAAAAAAAAAAAAAZAEAAAQAAAADAwAAAAAAIAYA
			AAABAQAAU3lzdGVtAAAMAAAAAQEAAEFwcGxpY2F0aW9u
			cwwAAAABAQAATWVzc2FnZXMuYXBwDAAAAAEGAAAQAAAA
			IAAAADQAAAAIAAAABAMAABUAAAD///8PCAAAAAQDAAAX
			AAAA////DwgAAAAEAwAASIoAAP///w8MAAAAAQYAAFwA
			AABsAAAAfAAAAAgAAAAABAAAQcNsYgiAAAAYAAAAAQIA
			AAIAAAAAAAAADwAAAAAAAAAAAAAAAAAAAAgAAAABCQAA
			ZmlsZTovLy8KAAAAAQEAAG1hY09TIC0gSEQAAAgAAAAE
			AwAAAACHETkAAAAkAAAAAQEAADc3N0IxMjUzLTE1QzAt
			NEZDMS05NTU1LTBBOTI2RTFDREQ3NRgAAAABAgAAgQAA
			AAEAAADvEwAAAQAAAAAAAAAAAAAAAQAAAAEBAAAvAAAA
			AAAAAAEFAACoAAAA/v///wEAAAAAAAAADQAAAAQQAABI
			AAAAAAAAAAUQAACMAAAAAAAAABAQAACwAAAAAAAAAEAQ
			AACgAAAAAAAAAAIgAABQAQAAAAAAAAUgAADQAAAAAAAA
			ABAgAADgAAAAAAAAABEgAAAEAQAAAAAAABIgAAD0AAAA
			AAAAABMgAACgAAAAAAAAACAgAAAwAQAAAAAAADAgAABc
			AQAAAAAAABDQAAAEAAAAAAAAAA==
			</data>
			<key>bundle-identifier</key>
			<string>com.apple.MobileSMS</string>
			<key>dock-extra</key>
			<false/>
			<key>file-data</key>
			<dict>
				<key>_CFURLString</key>
				<string>file:///System/Applications/Messages.app/</string>
				<key>_CFURLStringType</key>
				<integer>15</integer>
			</dict>
			<key>file-label</key>
			<string>Messages</string>
			<key>file-mod-date</key>
			<integer>3712892177</integer>
			<key>file-type</key>
			<integer>41</integer>
			<key>is-beta</key>
			<false/>
			<key>parent-mod-date</key>
			<integer>3712892177</integer>
		</dict>
		<key>tile-type</key>
		<string>file-tile</string>
	</dict>
	<dict>
		<key>GUID</key>
		<integer>2100041410</integer>
		<key>tile-data</key>
		<dict>
			<key>book</key>
			<data>
			Ym9va0QCAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAA
			AAAAAAAAAAAAAAAAAAAAZAEAAAQAAAADAwAAAAAAIAYA
			AAABAQAAU3lzdGVtAAAMAAAAAQEAAEFwcGxpY2F0aW9u
			cwwAAAABAQAAQ2FsZW5kYXIuYXBwDAAAAAEGAAAQAAAA
			IAAAADQAAAAIAAAABAMAABUAAAD///8PCAAAAAQDAAAX
			AAAA////DwgAAAAEAwAAAR0AAP///w8MAAAAAQYAAFwA
			AABsAAAAfAAAAAgAAAAABAAAQcNsYgiAAAAYAAAAAQIA
			AAIAAAAAAAAADwAAAAAAAAAAAAAAAAAAAAgAAAABCQAA
			ZmlsZTovLy8KAAAAAQEAAG1hY09TIC0gSEQAAAgAAAAE
			AwAAAACHETkAAAAkAAAAAQEAADc3N0IxMjUzLTE1QzAt
			NEZDMS05NTU1LTBBOTI2RTFDREQ3NRgAAAABAgAAgQAA
			AAEAAADvEwAAAQAAAAAAAAAAAAAAAQAAAAEBAAAvAAAA
			AAAAAAEFAACoAAAA/v///wEAAAAAAAAADQAAAAQQAABI
			AAAAAAAAAAUQAACMAAAAAAAAABAQAACwAAAAAAAAAEAQ
			AACgAAAAAAAAAAIgAABQAQAAAAAAAAUgAADQAAAAAAAA
			ABAgAADgAAAAAAAAABEgAAAEAQAAAAAAABIgAAD0AAAA
			AAAAABMgAACgAAAAAAAAACAgAAAwAQAAAAAAADAgAABc
			AQAAAAAAABDQAAAEAAAAAAAAAA==
			</data>
			<key>bundle-identifier</key>
			<string>com.apple.iCal</string>
			<key>dock-extra</key>
			<true/>
			<key>file-data</key>
			<dict>
				<key>_CFURLString</key>
				<string>file:///System/Applications/Calendar.app/</string>
				<key>_CFURLStringType</key>
				<integer>15</integer>
			</dict>
			<key>file-label</key>
			<string>Calendar</string>
			<key>file-mod-date</key>
			<integer>3712892177</integer>
			<key>file-type</key>
			<integer>41</integer>
			<key>is-beta</key>
			<false/>
			<key>parent-mod-date</key>
			<integer>3712892177</integer>
		</dict>
		<key>tile-type</key>
		<string>file-tile</string>
	</dict>
	<dict>
		<key>GUID</key>
		<integer>2100041412</integer>
		<key>tile-data</key>
		<dict>
			<key>book</key>
			<data>
			Ym9va0gCAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAA
			AAAAAAAAAAAAAAAAAAAAaAEAAAQAAAADAwAAAAAAIAYA
			AAABAQAAU3lzdGVtAAAMAAAAAQEAAEFwcGxpY2F0aW9u
			cw0AAAABAQAAUmVtaW5kZXJzLmFwcAAAAAwAAAABBgAA
			EAAAACAAAAA0AAAACAAAAAQDAAAVAAAA////DwgAAAAE
			AwAAFwAAAP///w8IAAAABAMAAHIOAQD///8PDAAAAAEG
			AABgAAAAcAAAAIAAAAAIAAAAAAQAAEHDbGIIgAAAGAAA
			AAECAAACAAAAAAAAAA8AAAAAAAAAAAAAAAAAAAAIAAAA
			AQkAAGZpbGU6Ly8vCgAAAAEBAABtYWNPUyAtIEhEAAAI
			AAAABAMAAAAAhxE5AAAAJAAAAAEBAAA3NzdCMTI1My0x
			NUMwLTRGQzEtOTU1NS0wQTkyNkUxQ0RENzUYAAAAAQIA
			AIEAAAABAAAA7xMAAAEAAAAAAAAAAAAAAAEAAAABAQAA
			LwAAAAAAAAABBQAAqAAAAP7///8BAAAAAAAAAA0AAAAE
			EAAATAAAAAAAAAAFEAAAkAAAAAAAAAAQEAAAtAAAAAAA
			AABAEAAApAAAAAAAAAACIAAAVAEAAAAAAAAFIAAA1AAA
			AAAAAAAQIAAA5AAAAAAAAAARIAAACAEAAAAAAAASIAAA
			+AAAAAAAAAATIAAApAAAAAAAAAAgIAAANAEAAAAAAAAw
			IAAAYAEAAAAAAAAQ0AAABAAAAAAAAAA=
			</data>
			<key>bundle-identifier</key>
			<string>com.apple.reminders</string>
			<key>dock-extra</key>
			<false/>
			<key>file-data</key>
			<dict>
				<key>_CFURLString</key>
				<string>file:///System/Applications/Reminders.app/</string>
				<key>_CFURLStringType</key>
				<integer>15</integer>
			</dict>
			<key>file-label</key>
			<string>Reminders</string>
			<key>file-mod-date</key>
			<integer>3712892177</integer>
			<key>file-type</key>
			<integer>41</integer>
			<key>is-beta</key>
			<false/>
			<key>parent-mod-date</key>
			<integer>3712892177</integer>
		</dict>
		<key>tile-type</key>
		<string>file-tile</string>
	</dict>
	<dict>
		<key>GUID</key>
		<integer>2100041413</integer>
		<key>tile-data</key>
		<dict>
			<key>book</key>
			<data>
			Ym9va0QCAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAA
			AAAAAAAAAAAAAAAAAAAAZAEAAAQAAAADAwAAAAAAIAYA
			AAABAQAAU3lzdGVtAAAMAAAAAQEAAEFwcGxpY2F0aW9u
			cwkAAAABAQAATm90ZXMuYXBwAAAADAAAAAEGAAAQAAAA
			IAAAADQAAAAIAAAABAMAABUAAAD///8PCAAAAAQDAAAX
			AAAA////DwgAAAAEAwAA7KcAAP///w8MAAAAAQYAAFwA
			AABsAAAAfAAAAAgAAAAABAAAQcNsYgiAAAAYAAAAAQIA
			AAIAAAAAAAAADwAAAAAAAAAAAAAAAAAAAAgAAAABCQAA
			ZmlsZTovLy8KAAAAAQEAAG1hY09TIC0gSEQAAAgAAAAE
			AwAAAACHETkAAAAkAAAAAQEAADc3N0IxMjUzLTE1QzAt
			NEZDMS05NTU1LTBBOTI2RTFDREQ3NRgAAAABAgAAgQAA
			AAEAAADvEwAAAQAAAAAAAAAAAAAAAQAAAAEBAAAvAAAA
			AAAAAAEFAACoAAAA/v///wEAAAAAAAAADQAAAAQQAABI
			AAAAAAAAAAUQAACMAAAAAAAAABAQAACwAAAAAAAAAEAQ
			AACgAAAAAAAAAAIgAABQAQAAAAAAAAUgAADQAAAAAAAA
			ABAgAADgAAAAAAAAABEgAAAEAQAAAAAAABIgAAD0AAAA
			AAAAABMgAACgAAAAAAAAACAgAAAwAQAAAAAAADAgAABc
			AQAAAAAAABDQAAAEAAAAAAAAAA==
			</data>
			<key>bundle-identifier</key>
			<string>com.apple.Notes</string>
			<key>dock-extra</key>
			<false/>
			<key>file-data</key>
			<dict>
				<key>_CFURLString</key>
				<string>file:///System/Applications/Notes.app/</string>
				<key>_CFURLStringType</key>
				<integer>15</integer>
			</dict>
			<key>file-label</key>
			<string>Notes</string>
			<key>file-mod-date</key>
			<integer>3712892177</integer>
			<key>file-type</key>
			<integer>41</integer>
			<key>is-beta</key>
			<false/>
			<key>parent-mod-date</key>
			<integer>3712892177</integer>
		</dict>
		<key>tile-type</key>
		<string>file-tile</string>
	</dict>
	<dict>
		<key>GUID</key>
		<integer>2100041415</integer>
		<key>tile-data</key>
		<dict>
			<key>book</key>
			<data>
			Ym9va0QCAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAA
			AAAAAAAAAAAAAAAAAAAAZAEAAAQAAAADAwAAAAAAIAYA
			AAABAQAAU3lzdGVtAAAMAAAAAQEAAEFwcGxpY2F0aW9u
			cwkAAAABAQAATXVzaWMuYXBwAAAADAAAAAEGAAAQAAAA
			IAAAADQAAAAIAAAABAMAABUAAAD///8PCAAAAAQDAAAX
			AAAA////DwgAAAAEAwAAn5EAAP///w8MAAAAAQYAAFwA
			AABsAAAAfAAAAAgAAAAABAAAQcN+9mSAAAAYAAAAAQIA
			AAIAAAAAAAAADwAAAAAAAAAAAAAAAAAAAAgAAAABCQAA
			ZmlsZTovLy8KAAAAAQEAAG1hY09TIC0gSEQAAAgAAAAE
			AwAAAACHETkAAAAkAAAAAQEAADc3N0IxMjUzLTE1QzAt
			NEZDMS05NTU1LTBBOTI2RTFDREQ3NRgAAAABAgAAgQAA
			AAEAAADvEwAAAQAAAAAAAAAAAAAAAQAAAAEBAAAvAAAA
			AAAAAAEFAACoAAAA/v///wEAAAAAAAAADQAAAAQQAABI
			AAAAAAAAAAUQAACMAAAAAAAAABAQAACwAAAAAAAAAEAQ
			AACgAAAAAAAAAAIgAABQAQAAAAAAAAUgAADQAAAAAAAA
			ABAgAADgAAAAAAAAABEgAAAEAQAAAAAAABIgAAD0AAAA
			AAAAABMgAACgAAAAAAAAACAgAAAwAQAAAAAAADAgAABc
			AQAAAAAAABDQAAAEAAAAAAAAAA==
			</data>
			<key>bundle-identifier</key>
			<string>com.apple.Music</string>
			<key>dock-extra</key>
			<false/>
			<key>file-data</key>
			<dict>
				<key>_CFURLString</key>
				<string>file:///System/Applications/Music.app/</string>
				<key>_CFURLStringType</key>
				<integer>15</integer>
			</dict>
			<key>file-label</key>
			<string>Music</string>
			<key>file-mod-date</key>
			<integer>3715327433</integer>
			<key>file-type</key>
			<integer>41</integer>
			<key>is-beta</key>
			<false/>
			<key>parent-mod-date</key>
			<integer>3715327433</integer>
		</dict>
		<key>tile-type</key>
		<string>file-tile</string>
	</dict>
	<dict>
		<key>GUID</key>
		<integer>2100041416</integer>
		<key>tile-data</key>
		<dict>
			<key>book</key>
			<data>
			Ym9va0QCAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAA
			AAAAAAAAAAAAAAAAAAAAZAEAAAQAAAADAwAAAAAAIAYA
			AAABAQAAU3lzdGVtAAAMAAAAAQEAAEFwcGxpY2F0aW9u
			cwwAAAABAQAAUG9kY2FzdHMuYXBwDAAAAAEGAAAQAAAA
			IAAAADQAAAAIAAAABAMAABUAAAD///8PCAAAAAQDAAAX
			AAAA////DwgAAAAEAwAAp+8AAP///w8MAAAAAQYAAFwA
			AABsAAAAfAAAAAgAAAAABAAAQcNsYgiAAAAYAAAAAQIA
			AAIAAAAAAAAADwAAAAAAAAAAAAAAAAAAAAgAAAABCQAA
			ZmlsZTovLy8KAAAAAQEAAG1hY09TIC0gSEQAAAgAAAAE
			AwAAAACHETkAAAAkAAAAAQEAADc3N0IxMjUzLTE1QzAt
			NEZDMS05NTU1LTBBOTI2RTFDREQ3NRgAAAABAgAAgQAA
			AAEAAADvEwAAAQAAAAAAAAAAAAAAAQAAAAEBAAAvAAAA
			AAAAAAEFAACoAAAA/v///wEAAAAAAAAADQAAAAQQAABI
			AAAAAAAAAAUQAACMAAAAAAAAABAQAACwAAAAAAAAAEAQ
			AACgAAAAAAAAAAIgAABQAQAAAAAAAAUgAADQAAAAAAAA
			ABAgAADgAAAAAAAAABEgAAAEAQAAAAAAABIgAAD0AAAA
			AAAAABMgAACgAAAAAAAAACAgAAAwAQAAAAAAADAgAABc
			AQAAAAAAABDQAAAEAAAAAAAAAA==
			</data>
			<key>bundle-identifier</key>
			<string>com.apple.podcasts</string>
			<key>dock-extra</key>
			<false/>
			<key>file-data</key>
			<dict>
				<key>_CFURLString</key>
				<string>file:///System/Applications/Podcasts.app/</string>
				<key>_CFURLStringType</key>
				<integer>15</integer>
			</dict>
			<key>file-label</key>
			<string>Podcasts</string>
			<key>file-mod-date</key>
			<integer>3712892177</integer>
			<key>file-type</key>
			<integer>41</integer>
			<key>is-beta</key>
			<false/>
			<key>parent-mod-date</key>
			<integer>3712892177</integer>
		</dict>
		<key>tile-type</key>
		<string>file-tile</string>
	</dict>
	<dict>
		<key>GUID</key>
		<integer>2100041418</integer>
		<key>tile-data</key>
		<dict>
			<key>book</key>
			<data>
			Ym9va0gCAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAA
			AAAAAAAAAAAAAAAAAAAAaAEAAAQAAAADAwAAAAAAIAYA
			AAABAQAAU3lzdGVtAAAMAAAAAQEAAEFwcGxpY2F0aW9u
			cw0AAAABAQAAQXBwIFN0b3JlLmFwcAAAAAwAAAABBgAA
			EAAAACAAAAA0AAAACAAAAAQDAAAVAAAA////DwgAAAAE
			AwAAFwAAAP///w8IAAAABAMAABkAAAD///8PDAAAAAEG
			AABgAAAAcAAAAIAAAAAIAAAAAAQAAEHDbGIIgAAAGAAA
			AAECAAACAAAAAAAAAA8AAAAAAAAAAAAAAAAAAAAIAAAA
			AQkAAGZpbGU6Ly8vCgAAAAEBAABtYWNPUyAtIEhEAAAI
			AAAABAMAAAAAhxE5AAAAJAAAAAEBAAA3NzdCMTI1My0x
			NUMwLTRGQzEtOTU1NS0wQTkyNkUxQ0RENzUYAAAAAQIA
			AIEAAAABAAAA7xMAAAEAAAAAAAAAAAAAAAEAAAABAQAA
			LwAAAAAAAAABBQAAqAAAAP7///8BAAAAAAAAAA0AAAAE
			EAAATAAAAAAAAAAFEAAAkAAAAAAAAAAQEAAAtAAAAAAA
			AABAEAAApAAAAAAAAAACIAAAVAEAAAAAAAAFIAAA1AAA
			AAAAAAAQIAAA5AAAAAAAAAARIAAACAEAAAAAAAASIAAA
			+AAAAAAAAAATIAAApAAAAAAAAAAgIAAANAEAAAAAAAAw
			IAAAYAEAAAAAAAAQ0AAABAAAAAAAAAA=
			</data>
			<key>bundle-identifier</key>
			<string>com.apple.AppStore</string>
			<key>dock-extra</key>
			<true/>
			<key>file-data</key>
			<dict>
				<key>_CFURLString</key>
				<string>file:///System/Applications/App%20Store.app/</string>
				<key>_CFURLStringType</key>
				<integer>15</integer>
			</dict>
			<key>file-label</key>
			<string>App Store</string>
			<key>file-mod-date</key>
			<integer>3712892177</integer>
			<key>file-type</key>
			<integer>41</integer>
			<key>is-beta</key>
			<false/>
			<key>parent-mod-date</key>
			<integer>3712892177</integer>
		</dict>
		<key>tile-type</key>
		<string>file-tile</string>
	</dict>
	<dict>
		<key>GUID</key>
		<integer>2100041419</integer>
		<key>tile-data</key>
		<dict>
			<key>book</key>
			<data>
			Ym9va1ACAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAA
			AAAAAAAAAAAAAAAAAAAAcAEAAAQAAAADAwAAAAAAIAYA
			AAABAQAAU3lzdGVtAAAMAAAAAQEAAEFwcGxpY2F0aW9u
			cxYAAAABAQAAU3lzdGVtIFByZWZlcmVuY2VzLmFwcAAA
			DAAAAAEGAAAQAAAAIAAAADQAAAAIAAAABAMAABUAAAD/
			//8PCAAAAAQDAAAXAAAA////DwgAAAAEAwAA2ioBAP//
			/w8MAAAAAQYAAGgAAAB4AAAAiAAAAAgAAAAABAAAQcN+
			9mSAAAAYAAAAAQIAAAIAAAAAAAAADwAAAAAAAAAAAAAA
			AAAAAAgAAAABCQAAZmlsZTovLy8KAAAAAQEAAG1hY09T
			IC0gSEQAAAgAAAAEAwAAAACHETkAAAAkAAAAAQEAADc3
			N0IxMjUzLTE1QzAtNEZDMS05NTU1LTBBOTI2RTFDREQ3
			NRgAAAABAgAAgQAAAAEAAADvEwAAAQAAAAAAAAAAAAAA
			AQAAAAEBAAAvAAAAAAAAAAEFAACoAAAA/v///wEAAAAA
			AAAADQAAAAQQAABUAAAAAAAAAAUQAACYAAAAAAAAABAQ
			AAC8AAAAAAAAAEAQAACsAAAAAAAAAAIgAABcAQAAAAAA
			AAUgAADcAAAAAAAAABAgAADsAAAAAAAAABEgAAAQAQAA
			AAAAABIgAAAAAQAAAAAAABMgAACsAAAAAAAAACAgAAA8
			AQAAAAAAADAgAABoAQAAAAAAABDQAAAEAAAAAAAAAA==
			</data>
			<key>bundle-identifier</key>
			<string>com.apple.systempreferences</string>
			<key>dock-extra</key>
			<true/>
			<key>file-data</key>
			<dict>
				<key>_CFURLString</key>
				<string>file:///System/Applications/System%20Preferences.app/</string>
				<key>_CFURLStringType</key>
				<integer>15</integer>
			</dict>
			<key>file-label</key>
			<string>System Preferences</string>
			<key>file-mod-date</key>
			<integer>3715327433</integer>
			<key>file-type</key>
			<integer>41</integer>
			<key>is-beta</key>
			<false/>
			<key>parent-mod-date</key>
			<integer>3715327433</integer>
		</dict>
		<key>tile-type</key>
		<string>file-tile</string>
	</dict>
	<dict>
		<key>GUID</key>
		<integer>2100041422</integer>
		<key>tile-data</key>
		<dict>
			<key>book</key>
			<data>
			Ym9va3ACAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAA
			AAAAAAAAAAAAAAAAAAAAkAEAAAQAAAADAwAAAAAAIAYA
			AAABAQAAU3lzdGVtAAAMAAAAAQEAAEFwcGxpY2F0aW9u
			cwkAAAABAQAAVXRpbGl0aWVzAAAADAAAAAEBAABUZXJt
			aW5hbC5hcHAQAAAAAQYAABAAAAAgAAAANAAAAEgAAAAI
			AAAABAMAABUAAAD///8PCAAAAAQDAAAXAAAA////DwgA
			AAAEAwAA10ABAP///w8IAAAABAMAAB2tAQD///8PEAAA
			AAEGAAB0AAAAhAAAAJQAAACkAAAACAAAAAAEAABBw372
			ZIAAABgAAAABAgAAAgAAAAAAAAAPAAAAAAAAAAAAAAAA
			AAAACAAAAAEJAABmaWxlOi8vLwoAAAABAQAAbWFjT1Mg
			LSBIRAAACAAAAAQDAAAAAIcROQAAACQAAAABAQAANzc3
			QjEyNTMtMTVDMC00RkMxLTk1NTUtMEE5MjZFMUNERDc1
			GAAAAAECAACBAAAAAQAAAO8TAAABAAAAAAAAAAAAAAAB
			AAAAAQEAAC8AAAAAAAAAAQUAAKgAAAD+////AQAAAAAA
			AAANAAAABBAAAFwAAAAAAAAABRAAALQAAAAAAAAAEBAA
			ANwAAAAAAAAAQBAAAMwAAAAAAAAAAiAAAHwBAAAAAAAA
			BSAAAPwAAAAAAAAAECAAAAwBAAAAAAAAESAAADABAAAA
			AAAAEiAAACABAAAAAAAAEyAAAMwAAAAAAAAAICAAAFwB
			AAAAAAAAMCAAAIgBAAAAAAAAENAAAAQAAAAAAAAA
			</data>
			<key>bundle-identifier</key>
			<string>com.apple.Terminal</string>
			<key>dock-extra</key>
			<false/>
			<key>file-data</key>
			<dict>
				<key>_CFURLString</key>
				<string>file:///System/Applications/Utilities/Terminal.app/</string>
				<key>_CFURLStringType</key>
				<integer>15</integer>
			</dict>
			<key>file-label</key>
			<string>Terminal</string>
			<key>file-mod-date</key>
			<integer>3715327433</integer>
			<key>file-type</key>
			<integer>41</integer>
			<key>is-beta</key>
			<false/>
			<key>parent-mod-date</key>
			<integer>3715327433</integer>
		</dict>
		<key>tile-type</key>
		<string>file-tile</string>
	</dict>
</array>
'
defaults write com.apple.dock "persistent-others" '
<array>
	<dict>
		<key>GUID</key>
		<integer>2100041421</integer>
		<key>tile-data</key>
		<dict>
			<key>arrangement</key>
			<integer>2</integer>
			<key>book</key>
			<data>
			Ym9va4ACAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAA
			AAAAAAAAAAAAAAAAAAAAfAEAAAQAAAADAwAAAAAAIAUA
			AAABAQAAVXNlcnMAAAAGAAAAAQEAAG1heGltZQAACQAA
			AAEBAABEb3dubG9hZHMAAAAMAAAAAQYAABAAAAAgAAAA
			MAAAAAgAAAAEAwAAeWQAAAAAAAAIAAAABAMAADiNAAAA
			AAAACAAAAAQDAABrjQAAAAAAAAwAAAABBgAAWAAAAGgA
			AAB4AAAACAAAAAAEAABBw2xiCIAAABgAAAABAgAAAgAA
			AAAAAAAPAAAAAAAAAAAAAAAAAAAACAAAAAQDAAABAAAA
			AAAAAAQAAAADAwAA9QEAAAgAAAABCQAAZmlsZTovLy8K
			AAAAAQEAAG1hY09TIC0gSEQAAAgAAAAEAwAAAACHETkA
			AAAkAAAAAQEAADc3N0IxMjUzLTE1QzAtNEZDMS05NTU1
			LTBBOTI2RTFDREQ3NRgAAAABAgAAgQAAAAEAAADvEwAA
			AQAAAAAAAAAAAAAAAQAAAAEBAAAvAAAAAAAAAAEFAADM
			AAAA/v///wEAAAAAAAAAEAAAAAQQAABEAAAAAAAAAAUQ
			AACIAAAAAAAAABAQAACsAAAAAAAAAEAQAACcAAAAAAAA
			AAIgAABoAQAAAAAAAAUgAADoAAAAAAAAABAgAAD4AAAA
			AAAAABEgAAAcAQAAAAAAABIgAAAMAQAAAAAAABMgAACc
			AAAAAAAAACAgAABIAQAAAAAAADAgAAB0AQAAAAAAAAHA
			AADMAAAAAAAAABHAAAAgAAAAAAAAABLAAADcAAAAAAAA
			ABDQAAAEAAAAAAAAAA==
			</data>
			<key>displayas</key>
			<integer>0</integer>
			<key>file-data</key>
			<dict>
				<key>_CFURLString</key>
				<string>file:///Users/maxime/Downloads/</string>
				<key>_CFURLStringType</key>
				<integer>15</integer>
			</dict>
			<key>file-label</key>
			<string>Downloads</string>
			<key>file-mod-date</key>
			<integer>61155460440755</integer>
			<key>file-type</key>
			<integer>2</integer>
			<key>is-beta</key>
			<false/>
			<key>parent-mod-date</key>
			<integer>268842899006140</integer>
			<key>preferreditemsize</key>
			<integer>-1</integer>
			<key>showas</key>
			<integer>1</integer>
		</dict>
		<key>tile-type</key>
		<string>directory-tile</string>
	</dict>
</array>
'
defaults write com.apple.dock "recent-apps" '<array/>'
defaults write com.apple.dock "region" -string 'FR'
defaults write com.apple.dock "show-recents" -boolean false
defaults write com.apple.dock "trash-full" -boolean false
defaults write com.apple.dock "version" -integer 1
defaults write com.apple.dock "wvous-br-corner" -integer 1
defaults write com.apple.dock "wvous-br-modifier" -integer 1048576
defaults write com.apple.dock "wvous-tl-corner" -integer 2
defaults write com.apple.dock "wvous-tl-modifier" -integer 0
defaults write com.apple.dock "wvous-tr-corner" -integer 2
defaults write com.apple.dock "wvous-tr-modifier" -integer 0
